### PR TITLE
fix(mcdu): AOC RCVD MSGS scrolling, add arrows, and update on receipt

### LINKED ISSUE #2073: [BUG] AOC RCVD MSGS page navigation
**Mod Version**

{ "built": "2020-11-20T22:55:09+00:00", "ref": "refs/heads/master", "sha": "2665e17d24ac35a2b72bdc005ef1d9df087d6ef9", "actor": "wpine215", "event_name": "push" }

**Describe the bug**

when in AOC RCVD MSGS with multiple pages of received messages, the left and right arrows only work once, then become inop

**To Reproduce**

1. receive multiple aoc messages (atis, wxr, free text, anything) until you have at least 2 pages.
2. enter AOC RCVD MSGS and hit left or right arrow to navigate to next or previus page
3. try navigating back to page 1 with right or left arrow respectively

**Expected behavior**

being able to navigate through the pages correctly and multiple times

**Actual behavior**

only turns page once, then inop

**References**

https://www.youtube.com/watch?v=L1AekLgzjjY

**Additional context**

Was this working before/when did the issue start occurring?
n.a.

Is this a problem in the vanilla unmodded game?
n.a.

Discord username (if different from GitHub): oddsobriquet#0011

### PR DESCRIPTION
**Pull request by tracernz**
Fixes #2073

## Summary of Changes

- Fix scrolling of AOC RCVD MSGS pages per #2073.
- Add arrows to indicate which direction page can be scrolled.
- Update the page on receipt of a new message if it is active.

## Screenshots (if necessary)

Scroll available to the left:
image

## References

Unaware of any references for this functionality, so excerised judgment.

## Additional context

Discord username (if different from GitHub): tracernz#3313

## Testing instructions

Send multiple ATIS and/or METAR requests, and navigate to received messages page.
- Observe the messages appearing in the list as they are received
- Check scrolling back and forth between pages always works, and cannot scroll past first/last pages
- Delete all messages on the last page (with multiple pages available) and ensure the display scrolls back to the new last page
- Correct messages are displayed or deleted (with CLR in scratchpad) when pressing LSK next to a message

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_MessagesReceived.js [hunk 1]
```diff
@@ -23,6 +23,10 @@ class CDUAocMessagesReceived {
         }
         mcdu.clearDisplay();
 
+        mcdu.refreshPageCallback = () => {
+            this.ShowPage(mcdu);
+        };
```
Comment (tracernz) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_MessagesReceived.js:30]: Note: this will return to the first page, showing the new message. I think this would usually be desirable but it's debatable.

**Comment by tracernz** [comment]
Push to fix lint CI check:
```
A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_MessagesReceived.js
  32:13  error  'offset' is never reassigned. Use 'const' instead  prefer-const
```

**Comment by Lazarus320** [comment]
Category: QA Tester
Name: Lazarus#4286
Date of testing: 30/1/2021
Version of the sim: 1.12.13.0
PR Tested: #3239 
Tier of testing: 1
Changes to observe:
- Scrolling of AOC RCVD MSGS pages. 
- Arrows to indicate the direction where the page can be scrolled.
- Update the page on receipt of a new message if it is active.

Testing technique: Loaded c/d and connected to Vatsim. 
Steps you've made to test the Pull Request:
1.  Loaded and connected to Vatsim. 
2. Sent multiple atis requests 
3. Tested the changes

Flight notes: N/A

Media: 
New message update 

https://user-images.githubusercontent.com/74972083/106356136-3d23b200-6338-11eb-9f0d-f246fd8e3a61.mp4

Scrolling and arrows 

https://user-images.githubusercontent.com/74972083/106356051-80315580-6337-11eb-9d89-ea74d8bb5969.mp4

Scrolling back to last page when a whole page is deleted 

https://user-images.githubusercontent.com/74972083/106356069-a8b94f80-6337-11eb-8cd1-4d9d97faceca.mp4

The intended message is deleted 

https://user-images.githubusercontent.com/74972083/106356085-c686b480-6337-11eb-8013-7effd3b1b329.mp4

Issues: N/A

Overall Rating: Good 
Conclusions of the testing: Great QoL addition good job!

**Comment by BritishAvgeek** [comment]
Test in Progress however after getting a Direct To on this flight so far on departure, it wiped around 10 waypoints completely for no reason... not had it in any other PRs before so unsure if it is linked to this? Still testing... this will be edited later

image

**Comment by sidnov** [comment]
Category: QA Tester
Name: sidnov#8337
Date of testing: 30.1.2021
Version of the sim: 1.12.13.0
PR Tested: #3239 
Tier of testing: 1
Changes to observe: AOC RCVD Scrolling

### Testing technique: Tryout

### Steps you've made to test the Pull Request:

1. Spawned on RWY27, VABB.
2. Added flight route VABB-VAPO
3. Sent multiple requests from ATIS/TAF/METAR options
4. Waited for a minute and checked received messages
5. Checked scrolling between pages

### Media:
ezgif com-gif-maker

### Issues (If Any): None

### Overall Rating: Good

### Conclusions of the testing: Scrolling back and forth worked as expected on the AOC RCVD page. Media attached

**Comment by tracernz** [comment]
>  Dependent on code review etc and other tests it needs to be mentioned if this code changes anything else or _could_ change anything else, as I had adverse bugs appear by just using this PR which confused me a little (but it was all MCDU related issues). Clarification for this would be good.

Thanks for the report. I can't see how it would be related but I'll take another look at the only piece of code that touches anything outside of the messages page (the updatePage callback).

**Comment by BritishAvgeek** [comment]
Cheers, it might have just been some bad Navigraph data though conflicting (which seems more likely) but I wasn't sure if it was one or the other... I'll remove the Nav data today and check it again... If it's the Navigraph Nav data then I'll edit the test writeup

**Comment by tjburni** [comment]
Category: QA Tester
Name: [Z+1]tjburni#0409
Date of testing: Current date 31.1.2021
Version of the sim: 1.12.13
PR Tested: #3239
Tier of testing: 1
Changes to observe:AOC RCVD MSGS scrolling, add arrows, and update on receipt

Testing technique:full vatsim flight
Steps you've made to test the Pull Request:
1.spawned on runway
2.Sent multiple atis requests
3.tested described changes


Issues (If Any):none

Overall Rating: Good
Conclusions of the testing:Works as expected. Thanks for the Pr!

**Comment by BritishAvgeek** [comment]
Edited my test writeup above - it seems to have yet again been bad Navigraph Nav Data!

**Comment by tracernz** [comment]
> 
> 
> Edited my test writeup above - it seems to have yet again been bad Navigraph Nav Data!

Thanks for the follow-up! I did get to the bit in the stream where you noticed it went bad. Bit annoying when you've still got a long way to go!

**Comment by ChruutvoLuzi** [comment]
Category: QA Tester
Name: ChruutvoLuzi | SD-PB.ch#8902
Date of testing: 1.2.2021
Version of the sim: 1.12.13.0
PR Tested: #3239 
Tier of testing: 1
Changes to observe: Several Changes in the AOC Page and Behavior

Testing technique: TryOut
Steps you've made to test the Pull Request:
1. Spawned C&D at EDDK
2. Requested alot METARs
3. Scrolled through them and checked the buttons
4. Requested a METAR and checked if it refreshes on the page itself

Media:

https://user-images.githubusercontent.com/70195216/106489157-c06a1280-64b4-11eb-9bce-ffc2e155b272.mp4

Issues (If Any): None 

Overall Rating: Good
Conclusions of the testing: Everything works as described, had no visual issues or bugs

**Review by wpine215 — APPROVED** [review]
