### PR TITLE
fix(ecam): All cycle functionality

### LINKED ISSUE #3123: [BUG] All Button for MCDU bugged
**Mod Version**

{
  "built": "2021-01-20T17:46:30+00:00",
  "ref": "",
  "sha": "",
  "actor": "DerL30N <leon.beeser@yahoo.de>",
  "event_name": "manual"
}

**Describe the bug**

When pressing the All button to cycle through ECAM pages it jumps from page to page and doesn't go in the way its supposed to so Eng then Bleed and so on but instead looks to choose what page it goes to randomly

**To Reproduce**

1.Do a normal flight
2.Hit the All button

**Expected behavior**

Cycle through pages in the right order

**Actual behavior**

Goes to random ECAM Pages

**References**

https://user-images.githubusercontent.com/70103461/105255506-9f7ff400-5b7b-11eb-8460-9d9297549635.mp4

**Additional context**

Was this working before/when did the issue start occurring? Was working before noticed today but some people have it while others don't and just to clarify, I asked the guy who made the pr (#3114) that I was flying with and he said it doesn't have anything to do with it

Is this a problem in the vanilla unmodded game? no

Discord username (if different from GitHub): FlightSimmer7700#3468

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

### PR DESCRIPTION
**Pull request by Saschl**
Fixes #3123

## Summary of Changes

Removed settInterval in favor of using deltatime to fix the page jumping issue. Also switched the statements that control the page and the "active" light of the corresponding button, to keep them better in sync.

## Screenshots (if necessary)

ezgif-7-d66965f0e0c7

## Additional context

Discord username (if different from GitHub): saschl#9432

## Testing instructions

1. Click the ecam ALL button once. The page should switch to the next.
2. Keep the ecam all button pressed: Pages should cycle in order and there should be no jumping back and forth
3. Select an ecam page and after that press and hold the ALL button. Pages should cycle normally.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js [hunk 1]
```diff
@@ -142,12 +145,15 @@ class A320_Neo_EICAS extends Airliners.BaseEICAS {
         super.onUpdate(_deltaTime);
 
         const selfTestCurrentKnobValue = SimVar.GetSimVarValue(this.isTopScreen ? "LIGHT POTENTIOMETER:92" : "LIGHT POTENTIOMETER:93", "number");
+        // ECAM all button
+        const ecamAllButtonState = SimVar.GetSimVarValue("L:A32NX_ECAM_ALL_Push_IsDown", "Bool");
```
Comment (Saschl) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js:149]: I put this before the throttler as otherwise the state only updates when you hold the button long enough (~500ms)  to scroll through the pages with one click. Holding the button would work after the throttle as well

**Review by tracernz — APPROVED** [review]
Changes look okay. It would be good if you could put a bit of context in your pull request as per the template, both for reviewers now, and in the future.

**Comment by Saschl** [comment]
Thanks for the reminder, it’s actually still a draft that’s why I haven’t added a description yet. Anyhow I added it but I need to test a bit more as some things were strange :)

**Comment by tracernz** [comment]
> 
> 
> Thanks for the reminder, it’s actually still a draft that’s why I haven’t added a description yet. Anyhow I added it but I need to test a bit more as some things were strange :)

I missed that sorry! I'll take another look when it's done. :)

**Comment by Saschl** [comment]
I'll check with the React ECAM this afternoon 👍

**Comment by Saschl** [comment]
Took a bit longer.. works fine with the current versions!

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js [hunk 2]
```diff
@@ -156,16 +159,21 @@ class A320_Neo_EICAS extends Airliners.BaseEICAS {
...
+        if (ecamAllButtonState && this.ecamAllButtonTimerStarted) {
+            this.ecamAllButtonTimer -= _deltaTime;
+        }
         const knobChanged = (selfTestCurrentKnobValue >= 0.1 && this.selfTestLastKnobValue < 0.1);
 
         _deltaTime = this.updateThrottler.canUpdate(_deltaTime);
-        if (_deltaTime === -1 && !knobChanged) {
+        if (_deltaTime === -1 && !knobChanged && !ecamAllButtonState) {
```
Comment (davidwalschots) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js:173]: **issue**: having any condition other than `_deltaTime === -1` in this expression is problematic, as code will be executed below with a _deltaTime of `-1` which is never intended.

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js [hunk 3]
```diff
@@ -318,19 +326,22 @@ class A320_Neo_EICAS extends Airliners.BaseEICAS {
...
+                this.ecamAllButtonTimer = 1000;
+            }
         } else if (!this.ecamAllButtonState && this.ecamAllButtonPrevState) { // button release
-            clearInterval(this.ecamCycleInterval);
+            this.ecamAllButtonTimer = 1000;
+            this.ecamAllButtonTimerStarted = false;
         }
 
-        this.ecamAllButtonPrevState = this.ecamAllButtonState;
+        this.ecamAllButtonPrevState = ecamAllButtonState;
```
Comment (davidwalschots) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js:344]: **question**: Does delta time differ from the time "seen" by `setInterval` and is that then the reason to write your own `setInterval`-like implementation?
**suggestion**: If no: use `setInterval`, if yes: extract `DeltaTimeIntervalFn` out into its own type to reduce the "going up and down abstraction levels" here.

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js [hunk 4]
```diff
@@ -156,16 +159,21 @@ class A320_Neo_EICAS extends Airliners.BaseEICAS {
 
     onUpdate() {
         let _deltaTime = this.getDeltaTime();
-
         super.onUpdate(_deltaTime);
 
         const selfTestCurrentKnobValue = SimVar.GetSimVarValue(this.isTopScreen ? "LIGHT POTENTIOMETER:92" : "LIGHT POTENTIOMETER:93", "number");
+        // ECAM all button
+        const ecamAllButtonState = SimVar.GetSimVarValue("L:A32NX_ECAM_ALL_Push_IsDown", "Bool");
```
Comment (davidwalschots) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js:166]: **nitpick**: variable name isn't telling me what it is, comment is used to try and make things clear.
```suggestion
        const ecamAllButtonBeingPushed = SimVar.GetSimVarValue("L:A32NX_ECAM_ALL_Push_IsDown", "Bool");
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js (hunk 2 above)
Comment (Saschl) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js:173]: Good point, I moved it further up to eliminate a possible -1 as delta time

**Review by Saschl — COMMENTED** [review]
Thanks for the review! I'll push the changes once I tested it in a flight.

**Review by davidwalschots — APPROVED** [review]

**Comment by TheSquirtingPantin** [comment]
Category: QA Trial
Name: Discord User Rémi#8871
Date of testing: Current 18/03/2021
Version of the sim: V1.14.5.0
PR Tested: #3131
Tier of testing: 1
Changes to observe:
ALL ECAM pushbutton implementation/logic

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. C/D at KDEN
2. Testing as per given PR procedure
3. General validation

Flight notes (When done a full flight): N/A
Media: N/A

Issues (If Any):
	- On two occasions, with difficulties reproducing: When using the ALL cycle function (holding ALL P/B), the p/b located at position n+2 (i.e: green light is on ENG (n) so n+2 is PRESS) was displaying a brief (less than 0.5s) and dimmed green light as well.

Overall Rating: Good
Conclusions of the testing: ALL ECAM p/b and logic works perfectly well and as expected. Minor issue detected is not preventing usage of the ALL p/b and is very hard to reproduce.

**Comment by Samueleonard** [comment]
Category: QA Trial
Name: 1samueleonard1#0001
Date of testing: 18/03/2021
Version of the sim: 1.14.5.0
PR Tested: #3131
Tier of testing: 1
Changes to observe: ecam all functionality
Testing technique: Tryout

Steps you've made to test the Pull Request:
1. load in on rwy
2. pressed ecam all several times - ecam cycles through pages with each click as expected
3. held ecam all - ecam cycles through ecam pages as expected
4. selected page, then held down ecam all - ecam cycles from selected page

Flight notes (When done a full flight):
N/A

Media: Insert screenshots, recordings, or anything relevant to the review here.
N/A

Issues (If Any):
None - lgtm

Steps to achieve the issue
N/A

Overall Rating: Good

Conclusions of the testing: works fine - good job

**Comment by DavidEGTE** [comment]
Category: QA Tester
Name: David#2177
Date of testing: 18/03/2021
Version of the sim: 1.14.5.0
PR Tested: #3131 
Tier of testing: 1

Changes to observe:
Removed settInterval in favor of using deltatime to fix the page jumping issue. Also switched the statements that control the page and the "active" light of the corresponding button, to keep them better in sync.

Testing technique: Try-out

Steps you've made to test the Pull Request:
1. Spawned C&D
2. Tested PR as instructed 
3. Via single click and hold "ALL" button on ECAM

Flight notes (When done a full flight):
N/A
Media: Insert screenshots, recordings, or anything relevant to the review here.
N/A
Issues (If Any): Write any issues
N/A
Steps to achieve the issue:
N/A

Overall Rating: Good
Conclusions of the testing: GTG
