### PR TITLE
[CDU] Constraint improvements

### LINKED ISSUE #2007: [BUG] altitude constraints "At or below" not correctly managed by the AP
)
**Mod Version**
Master

{ "built": "2020-11-18T18:36:51+00:00", "ref": "refs/heads/master", "sha": "2f9200767ccf8e008aa33df02e52021e4010ed01", "actor": "Benjozork", "event_name": "push" }. 
In fact I saw it with the dev version just before this one.

**Describe the bug**

I follow a flight plan at level 150
The next waypoint has a constraint on altitude: AT or Below FL190 (constraint extracted from the navigation database)
In this situation, the A320 will climb to FL190 instead of keeping the altitude of FL150
This waypoint being near an approach phase, the approach becomes problematic.

**To Reproduce**

1. I created a flight plan between LFRN and LFMN via Little Nav Map and loaded it in the sim and the bus. The flight level is FL150.
2. Before LFMN arrival, there are some waypoinbt with constraints "At or below alt" (ABDIL (At or Below 19000), AMFOU (At or Below 16000))
3. Execute the FP and see that the plane climbs before ABDIL (to reach level FL190) instead of keeping the level of FL150

**Expected behavior**

Flying at level FL150, the plane must keep FL150 and not climb to FL190 when the next wp has an alt cst of "at or below FL190"

**Actual behavior**

Flying at level FL150, the plane climbs to level FL190 when the next wp has an alt cst of "at or below FL190"

**References**

**Additional context**

Nothing special. The error is simple to reproduce.

Was this working before/when did the issue start occurring?
Do not know. I do not think so.

Is this a problem in the vanilla unmodded game?
Do not know.

Discord username (if different from GitHub):
PatriceCesson

### PR DESCRIPTION
**Pull request by MisterChocker**
Fixes #2007

## Summary of Changes

The AP respects altitude constraints..
- of upcoming waypoints,
- in climb, descent and approach,
- with range e.g. BELOW FL170, ABOVE FL150,

Climb is limited by at and below constraints, descent is limited by at and above constraints.

corresponding to current flight phase.

The AP respects speed constraints.
On descent it will slow down 5nm + 1nm for 1kt speed difference before the waypoint.

See reference image (waypoint MIQ has 7500ft alt constraint, waypoints before 7000)
I have increased the constraint of MIQ for showcase. Real life constraint would be +5000ft.
The example isn't quite accurate, because AP will follow first constraint found. The scenario I created is unrealistic since on an arrival route the altitude and speed constraints should only reduce, opposite for departure.

## Screenshots (if necessary)

image

## References

image

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Benjozork** [comment]
Could you try to merge the multiple nested `if` statements ? For example when you do

```
if (a) {
    if (b) {

    }
}
```

Do `if (a && b}` instead, it's more readable.

**Comment by rick2909** [comment]
Not only that, but it is also slightly faster, because if one condition is false, it won't even try to match the other conditions after it!

**Comment by MisterChocker** [comment]
@Benjozork better now? Anything else I don't see?

**Comment by MisterChocker** [comment]
I can remove even more lines, but code will get less readable.

**Comment by Benjozork** [comment]
> I can remove even more lines, but code will become less readable.
> 
> Can make this
> ```js
> if (type === 3) { // constraint below
>     return this.altLock > wpt.legAltitude1 ? wpt.legAltitude1 : 0;
> } else { // constraint above
>     return this.altLock < wpt.legAltitude1 ? wpt.legAltitude1 : 0;
> }
> ```
> to this
> 
> ```js
> return type === 3 ? (this.altLock > wpt.legAltitude1 ? wpt.legAltitude1 : 0) : (this.altLock < wpt.legAltitude1 ? wpt.legAltitude1 : 0);
> ```
> 
> not sure if I would need the parentheses.

No that's more readable as is.

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js [hunk 1]
```diff
@@ -320,6 +323,67 @@ class A320_Neo_CDU_MainDisplay extends FMCMainDisplay {
...
+                tmp = wpt.legAltitude1;
+            }
+            if (wpt.legAltitudeDescription === 0) {
+                continue;
+            }
+            if (wpt.legAltitudeDescription === 4) {
+                if (type === 3) {
+                    if (this.altLock < wpt.legAltitude2) {
+                        return wpt.legAltitude2;
+                    }
```
Comment (Benjozork) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js:370]: Here as well

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js [hunk 2]
```diff
@@ -320,6 +323,67 @@ class A320_Neo_CDU_MainDisplay extends FMCMainDisplay {
...
+                } else if (this.altLock > wpt.legAltitude1) {
+                    return wpt.legAltitude1;
+                }
+            } else if (wpt.legAltitudeDescription === 1 || wpt.legAltitudeDescription === type) {
+                if (type === 3) { // constraint below
+                    if (this.altLock > wpt.legAltitude1) {
+                        return wpt.legAltitude1;
+                    }
```
Comment (Benjozork) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js:378]: And here

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js (hunk 1 above)
Comment (MisterChocker) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js:370]: no, would break the logic for the else if. Type 3 must go alone, otherwise I can run into the else if with type 3 as well. Which is no good. Same for the other one.

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js (hunk 2 above)
Comment (MisterChocker) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js]: corrected

**Comment by Carter633** [comment]
Name: British Avgeek UTube -- Carter633 #1436
Date of testing: Current date 18/11/2020
Version of the sim: 1.10.11.0
PR Tested: #1985 
Object of test: AP respecting constraints

Testing technique: Full flight from EGKK to ESGG on VATSIM - with a return to EGKK too
Steps you've made to test the Pull Request:
1. Spawn C&D at EGKK - prepared MCDU with route below including SID and STAR (with constraints)
2. Departed Runway 26L - monitored AP to check new behaviours re:constraints
3. Did not respect any constraints on the STAR at all and kept reverting me to open climb constantly
4. 
5.
Currently running the test but will update this at the end of Sector 1

Flight notes
Route: FRAN1X FRANE M604 LARGA P144 GOLUM N866 AAL N607 MAKUR MAKU3T

Issues (If Any): As mentioned in Step 3 above - did not adhere to any constraints on the STAR in managed or selected alt modes and reverted to open climb on two occasions without input through the STAR

Overall Rating: To be improved
Conclusions of the testing: (see step 3) I've written the report semi-complete as I want to see if I am doing anything wrong during testing by describing what I've found so far - and will edit the report as I go. I'm on the outbound sector currently and will do a turnaround and return to EGKK too.

**Comment by MisterChocker** [comment]
@Carter633 haven't seen that behavior, will look into it.

**Comment by Carter633** [comment]
I've updated my initial test with the full result, just couldn't get it to work sorry

**Comment by MisterChocker** [comment]
@Carter633 thanks for you testing and finding this nasty bug.

Now working like intended.

**Comment by MisterChocker** [comment]
> 5\. Used the DETNA1J departure, this time edited the constraints to select +3000 +4000 and +5000 but again during departure it was totally ignored

Yes, on departure / in climb, I respect at or below constraints, on arrival / descent I respect at or above constraints.

**Comment by MisterChocker** [comment]
I found an issue with the athr tho. looking at that now.

**Comment by MisterChocker** [comment]
I addressed all issues mentioned.

**Comment by Carter633** [comment]
Name: British Avgeek UTube -- Carter633 #1436
Date of testing: Current date 19/11/2020
Version of the sim: 1.10.11.0
PR Tested: #1985
Object of test: AP respecting constraints - Test 2

Testing technique: Full flight from Miami to Providenciales (Turks&Caicos Islands) Livestreamed here https://youtu.be/pw0aAm5vius

Steps you've made to test the Pull Request:

1. Spawned C&D at KMIA, set aircraft and MCDU up with flight plan including SKINS2 departure... no constraints added in by the sim oddly - so manually input them using charts
2. Departed - constraints wiped annoyingly so there was nothing to respect...climbed to FL350 normally
3. Cruise - nothing to note... set up for descent
4. Added a constraint at a waypoint prior to the VOR approach due to the sim locking the values beyond wpt SOLEI - so used SOLEI 4000ft
5. Descent set to 3000ft and v/s used to manage descent - following the descent marker on ND
6. Arrived at 4000ft and aircraft levelled off wonderfully and held that in managed alt until passing the SOLEI WPT as expected - works well!
7. Continued with VOR approach and manual visual landing.

Issues (If Any): Worked very well though was unable to test during departure as the sim weirdly wiped my constraints input for the STAR

Overall Rating: Good
Conclusions of the testing:
All the issues I raised in the first test have not been reproduced and everything seems to work as it should do - nice work thanks!

**Comment by MisterChocker** [comment]
@Carter633 yeah the constraints are annoying if they are not automatically set. Maybe I will look at that in the future to add full support of that features.

**Comment by Carter633** [comment]
Yeah that's another issue though your PR worked nicely for me today! Descent was great reaching 4000 and refusing to drop below until after the wpt - thanks for the work btw!

**Comment by CaptainR3X** [comment]
Category: QA Tester
Name: GustavRex #4347
Date of testing: Current date 23/11/2020
Version of the sim: 1.10.11.0
PR Tested: #1985
Object of test: Test constraint improvements 

Testing technique: Return flight; ESGG-EKCH, EKCH-ESGG
Steps you've made to test the Pull Request:
1. C/D ESGG, Normal flight programming incl. custom constraints and takeoff
2. Arrival programming, custom constraints into EKCH, approach and landing
3. ON APU at EKCH, Normal flight programming incl. custom constraints and takeoff
4. Arrival programming, IRL constraints, approach and landing

Flight notes (If required): Online, VatSim

Issues (If Any): Did not respect or comply with constraints.
Overall Rating: Needs work
Conclusions of the testing: The AP did not respect the constraints on both flights. Also, not sure if this is related to this PR but arriving into ESGG, the constraints were flipped around to -XXXX instead of +XXXX. The AP did not respect a single constraint on both flights

**Comment by MisterChocker** [comment]
@CaptainR3X can you please be more specific? When you try to add constraints to the departure, that will not work because the manually entered constraints will always work as an above limitation. (this is because of the way altitude constraints are manually inserted does not support any other than above)

And no, this pr does not change altitude constraints, it only reads them. When they are wrong in the first place, I don't see a way for this pr to work with wrong/bad input.

FYI altitude constraints can:
A) constraint you to fly at an altitude/FL,
B) constraint you to fly at or above/below an altitude/FL,
C) constraint you to fly at or between two altitudes/FL

**Comment by MisterChocker** [comment]
@CaptainR3X please look at this for reference on how constraints work.
image

**Comment by CaptainR3X** [comment]
Yeah soz I think my brain is a bit fried, can see now that that explanation was absolutely bollocks. Basically, ex. on approach into ESGG, all constraints were flipped to be at/below instead of at/abv. except one. That was at/abv. FL80 which the plane flew right through. I am unsure whether it is something with my sim that causes the constraints to be flipped around. I will have a look later and see if I can find a STAR where the constraints are not flipped to test it again because yeah I realise that the plane will continue to descent if the constraints just say at/below upon descending

**Comment by MisterChocker** [comment]
If you give me the exact RWY and STAR with the correct VIAS and/or TRANSITION I can take a look at the situation myself.

**Comment by CaptainR3X** [comment]
RISMA2S ESGG/21 Routing is as follows
Screenshot 2020-11-23 173930

**Comment by MisterChocker** [comment]
I tested the exact route, the default constraints where a bit off (the ap was following the constraints), I corrected the constraints and the ap then followed the edited constraints.

image
image
image
image
image
image

**Comment by CaptainR3X** [comment]
How are you able to change the constraints? When I tried to change them, the MCDU wouldn't let me. It just defaulted back to the default constraints

**Comment by MisterChocker** [comment]
I selected the the waypoint with the corresponding RK button

**Comment by CaptainR3X** [comment]
Yeah. Did the exact same procedure. My waypoint and constraints were (by default): GG904 (-FL80), GG903 (-5000), GG415 (-K230;-3000)

**Comment by MisterChocker** [comment]
Well the at below won't do anything in descent to the ap. Now the question, why are they this way. I am using mfs default database.

**Comment by CaptainR3X** [comment]
Yeah it also had elbux (FL80), forgot that. That

**Comment by CaptainR3X** [comment]
Shows something different now at Elbux, but i just programmed the flight in. This is how it looks
image

**Comment by MisterChocker** [comment]
Yes getting the same now. Thats odd.

**Comment by CaptainR3X** [comment]
I just restarted the sim and programmed again. If you just select the landing rwy and manually programme the STAR then you can edit the constraints to be a specific alt. Still not +XXXX but that way the constraints can kinda be correct

**Comment by MisterChocker** [comment]
> I just restarted the sim and programmed again. If you just select the landing rwy and manually programme the STAR then you can edit the constraints to be a specific alt. Still not +XXXX but that way the constraints can kinda be correct

Yes we need to implement a proper constraint insert logic. Maybe I will take care of that soo if no one else get's their hands on it fist (cause I am kinda busy)

**Comment by CaptainR3X** [comment]
> > I just restarted the sim and programmed again. If you just select the landing rwy and manually programme the STAR then you can edit the constraints to be a specific alt. Still not +XXXX but that way the constraints can kinda be correct
> 
> Yes we need to implement a proper constraint insert logic. Maybe I will take care of that soo if no one else get's their hands on it fist (cause I am kinda busy)

Wish i could code so i could help :) On the second leg of the second test now. The manual constraints and STAR programming seems to fix it. Repsecting constraints nicely now

**Comment by CaptainR3X** [comment]
Category: QA Tester
Name: GustavRex #4347
Date of testing: Current date 23/11/2020
Version of the sim: 1.10.11.0
PR Tested: #1985
Object of test: Test constraint improvements 

Testing technique: Return flight; EKCH-ESGG, ESGG EKCH 
Steps you've made to test the Pull Request:
1. C/D EKCH, Normal flight programming and takeoff
2. Arrival programming, manual STAR and constraint programming (still IRL values), approach and landing
3. ON APU at ESGG, Normal flight programming and takeoff
4. Arrival programming, manual STAR and constraint programming (still IRL values, approach and landing

Flight notes (If required): Online, VatSim

Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: After baffeling with the constraints all afternoon, the manual STAR and constraint programming did the trick for me. AP respected all constraints nicely and descended as it should from TOD to ILS intercept.
