### PR TITLE
fix(fcu): selected speed LVAR and only active LVAR for V/S and FPA is filled

### LINKED ISSUE #5543: Bad LVAR value for A32NX_AUTOPILOT_FPA_SELECTED
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-04T11:40:50+00:00",
  "ref": "master",
  "sha": "fe97ce409e1f9d55b11185de38ce069915934bc9",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

When setting 0 for Vertical Speed, the LVAR A32NX_AUTOPILOT_VS_SELECTED is set to 0 and the LVAR A32NX_AUTOPILOT_FPA_SELECTED is set to 0 too:
FPA value to 0

When setting a value other than 0 for Vertical Speed (for example +400 or +500), the LVAR A32NX_AUTOPILOT_VS_SELECTED is set to this value but the LVAR A32NX_AUTOPILOT_FPA_SELECTED is always set to 9.8999 and not to 0:
FPA value not 0

Also, it seems that, when changing from VS mode to TRK/FPA mode or vice-versa, the LVAR A32NX_FCU_MODE_REVERSION_TRK_FPA_ACTIVE is always to 0 (This LVAR should indicate if TRK/FPA mode is activated or not right?).

### Expected behavior

The LVAR A32NX_AUTOPILOT_FPA_SELECTED should be always 0 when I am in vertical speed mode and only the LVAR A32NX_AUTOPILOT_VS_SELECTED should be updated.

### Steps to reproduce

1. In VS mode, set the VS to 0 -> The value of both LVARs should be 0
2. Set an other VS value -> The value of A32NX_AUTOPILOT_VS_SELECTED is correct but the value for A32NX_AUTOPILOT_FPA_SELECTED is incorrect (always 9.8999)

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### LINKED ISSUE #5544: Add a LVAR for selected speed
### Aircraft Version

Development

### Description

There is a LVAR for A32NX_AUTOPILOT_HEADING_SELECTED to have the selected heading but it seems that there is no LVAR to have selected speed. Because of that I use AUTOPILOT AIRSPEED HOLD VAR but the value is set in it only when I activate selected mode and not when I select the value in managed mode (by turning the selector with the dot displayed) BEFORE pulling the button to be in selected mode.

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### LINKED ISSUE #5545: Add an event to change altitude increment
### Aircraft Version

Development

### Description

Is it possible to have an event to change the altitude increment from 100 to 1000 or vice-versa please? 

For now, I have to change it in game before turning the selector (I use events A32NX.FCU_ALT_INC and A32NX.FCU_ALT_DEC for selector).

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### PR DESCRIPTION
**Pull request by aguther**
Fixes #5543
Fixes #5544
Fixes #5545

## Summary of Changes
This PR changed/adds:
* add a local variable for selected speed: `L:A32NX_AUTOPILOT_SPEED_SELECTED`
* only fills either `L:A32NX_AUTOPILOT_VS_SELECTED` or `L:A32NX_AUTOPILOT_FPA_SELECTED` depending on the active mode
* add event `A32NX.FCU_ALT_INCREMENT_TOGGLE`
* add event `A32NX.FCU_ALT_INCREMENT_SET`

## Testing instructions
* functions related to speed control and V/S or FPA mode need to function as before
* check with developer mode that variables show values as intended (see documentation)

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

File: flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js [hunk 1]
```diff
@@ -312,6 +312,9 @@ class A320_Neo_FCU_Speed extends A320_Neo_FCU_Component {
             }
             this.showSelectedSpeed = _showSelectedSpeed;
             SimVar.SetSimVarValue("L:A32NX_FCU_SPD_MANAGED_DASHES", "boolean", this.isManaged && !this.showSelectedSpeed);
+            if (this.currentValue != _value) {
+                SimVar.SetSimVarValue("L:A32NX_AUTOPILOT_SPEED_SELECTED", "number", _value);
+            }
             this.currentValue = _machActive ? _value * 100 : _value;
```
Comment (Benjozork) [inline flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js:318]: Shouldn't the calculation here also be done for the simvar, since we are comparing `this.currentValue` and `_value` above ?

Comment (aguther) [reply flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js:318]: You mean for the mach?

I left it out by intention because users might want to have a better readout in the variable (in case of mach you will get 0.78 instead of 78).

**Review by Benjozork — APPROVED** [review]

**Review by tracernz — APPROVED** [review]

**Comment by aguther** [comment]
I will further add another "fix" for an enhancement.

**Review by Benjozork — APPROVED** [review]
