### PR TITLE
Fix: allow inserting landing QNH in inHg

### LINKED ISSUE #1567: [BUG] mcdu performance page QNH only can write number
**Mod Version**

**Describe the bug**

When we prepare approach to airport, we set a mcdu performance page, appr phase.
QNH section only can write integer.

**To Reproduce**

1. Open mcde perf page
2. Go to appr phase, write qnh
3. Only can write integer.

**Expected behavior**

Can insert number like 29.92 

**Actual behavior**

When insert 29.92, mcdu just rounds to 30

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
Yes

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by pessip**
Fixes #1567

## Summary of Changes
Now when you enter for example 29.92 into the perf landing QNH field it instead of just rounding it to 30 it remebers the value like it it.
What the code does:
1. Checks for the formatting 12.34
2. Sets the value as 12.34
If the check fails it just continues using the normal behavior

## References

Discord username: pessimoo#6055

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js [hunk 1]
```diff
@@ -1469,8 +1469,15 @@ class FMCMainDisplay extends BaseAirliners {
         return false;
     }
     setPerfApprQNH(s) {
-        const value = parseFloat(s);
-        if (isFinite(value)) {
+        var value = parseFloat(s);
```
Comment (lukecologne) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js:1472]: Use let instead of var

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js [hunk 2]
```diff
@@ -1469,8 +1469,15 @@ class FMCMainDisplay extends BaseAirliners {
...
+        console.log(value);
+        const patt = /[0-9]{2}.[0-9]{2}/;
+        if (patt.test(value)) {
+            value = Math.round((value * 3386.389) / 100);
+            this.perfApprQNH = value;
+            return true;
+        }
+        else if (isFinite(value)) {
```
Comment (lukecologne) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js:1480]: Move the else if to the same line as the curly bracket

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js [hunk 3]
```diff
@@ -1469,8 +1469,14 @@ class FMCMainDisplay extends BaseAirliners {
         return false;
     }
     setPerfApprQNH(s) {
-        const value = parseFloat(s);
-        if (isFinite(value)) {
+        let value = parseFloat(s);
+        console.log(value);
```
Comment (beheh) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js:1473]: The debug logging is probably unwanted.
```suggestion
```

**Comment by lukecologne** [comment]
Thank you for your contribution. I've got one question about the functionality, currently, when you enter a value in inHg, the converted value in hPa will be displayed. I don't know if this is accurate or not, but I susptect it's not. It would be great if an IRL pilot could confirm

**Comment by pessip** [comment]
@lukecologne I'll look into making it work like that.

**Comment by pessip** [comment]
I have it working both ways now. I think I'll push the version with no conversion here because that seems more realistic to me.

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js [hunk 4]
```diff
@@ -482,8 +482,8 @@ class CDUPerformancePage {
             titleColor = "green";
         }
         let qnhCell = "[ ]";
-        if (isFinite(mcdu.perfApprQNH)) {
-            qnhCell = mcdu.perfApprQNH.toFixed(0);
+        if (isFinite(mcdu.perfApprQNH) | /[0-9]{2}.[0-9]{2}/.test(mcdu.perfApprQNH)) {
```
Comment (Benjozork) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js:485]: 1. can you store that regex in a constant at the top of the file ?

2. it's `||` not `|`. Did you test this ?

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js [hunk 5]
```diff
@@ -1470,7 +1470,10 @@ class FMCMainDisplay extends BaseAirliners {
     }
     setPerfApprQNH(s) {
         const value = parseFloat(s);
-        if (isFinite(value)) {
+        if (/[0-9]{2}.[0-9]{2}/.test(value)) {
```
Comment (Benjozork) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js:1473]: Same for hard-coded regex

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js (hunk 4 above)
Comment (pessip) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js:485]: I'll change the regexes. It did work when testing but I'll switch to the real or operator.

**Comment by pessip** [comment]
Can you review the changes?

**Comment by Benjozork** [comment]
I meant you should put the regexes on the top of the file, as constants, in UPPER_SNAKE_CASE.

**Comment by danbw9** [comment]
Name: danbw9#7028
Date of testing:  08.11.2020
Version of the sim: 1.8.10.0
PR Tested: #1583 
Object of test: Checking QNH field in PERF APP page allows values in inHg to be input

Testing technique: Test a scenario and real practical situations when flying 
Steps you've made to test the Pull Request:

Not been aware of this behaviour so prior to installing this PR, I checked first the '30' input which comes when trying to input 29.92 in QNH field.

Then compared to that of when PR is installed and it accepts the '.' and 29.92 as is described in the PR. 

Fly circuit at KLAX, test functionality whilst doing everything like normal. APP PERF page accepts the inHg values. Tried different examples. No problem

Issues (If Any): None. 
Overall Rating: Good
Conclusions of the testing: LGTM. All fine.

**Comment by lukecologne** [comment]
Does the QNH value have any logic connected to them, or is it just a fake field? From quickly taking a look it seems to me like it's the latter
