### PR TITLE
fix: WX Radar. 180 deg scan (left/right), correct ROSE NAV view, removed from PLAN

### LINKED ISSUE #1104: [BUG] Weather radar scans a 360 degree arc
**Mod Version**

**Describe the bug**
The weather radar scans a 360 degree arc when in reality the weather radar in the neo scans at best maybe 160 degrees.

**To Reproduce**
1. the bug is visible at all times the wx radar is activated
2.
3.

**Expected behavior**

I expect the radar to scan to the edge of the pfd then reverse direction to the other side of the pfd.

**Actual behavior**
The radar refresh scans 360 degrees around the pfd 

**References**

**Additional context**

Was this working before/when did the issue start occurring? unsure

Is this a problem in the vanilla unmodded game? unsure

Discord username (if different from GitHub): ziffel

### PR DESCRIPTION
**Pull request by 2hwk**
Fixes #1104 #1298 

## Summary of Changes

WX
- [x] Scan radius to 180 degrees from 360 degrees
- [x] Correct display in ARC view
- [x] Correct display in ROSE view
- [x] No display in PLAN view

TERR
- [x] Improved TERR display
~~- Correct TERR colours (if possible)~~
- [x] Correct display in ARC view
~~- Correct display in ROSE view~~
- [x] No display in PLAN view

## ARC WX
Original
Original

Fixed
PJJ5HGtlBo

## ROSE WX

Original

fOeraAMzAw

Fixed
Ie70ACX1SD

## PLAN WX

Original
nkqsaQqkow

Fixed
image

## ARC TERR

Original
Original

Fixed
fFB6x7T3e3

## ROSE TERR

Original

UYZXdf4Zvn

Better**
vlI5ozVYPN

## PLAN TERR

Original

jQ5vhvD7I2

Fixed

image

## References

#pilot-feedback channel, FSLabs, Manuals, documentation etc. for WX 
http://www.airbusdriver.net/EFIS5.pdf

https://www.youtube.com/watch?v=TEi-WX08ov8
https://www.youtube.com/watch?v=NE5K7sJN-lQ
https://www.youtube.com/watch?v=PsXhOAYVAGY
https://www.youtube.com/watch?v=asdURoA9vpY
https://www.youtube.com/watch?v=FDn2UQv_7I4
https://www.youtube.com/watch?v=c83k1Zttxpw

## Additional context

This also fixes a minor bug with the plane symbol disappearing from the ND. 

Discord username (if different from GitHub):2Cas#1022

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by lukecologne** [comment]
You cannot change the mask like this. It also masks map elements such as waypoints, airports, traffic aircraft etc.

File: A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_SvgMaskElement.js [hunk 1]
```diff
@@ -55,11 +55,12 @@ class SvgPlanMaskElement extends SvgMaskElement {
             this.path.setAttribute("y", "0");
             this.path.setAttribute("fill", "url(#Backlight)");
             this.path.setAttribute("transform", "translate(" + offsetX + " " + offsetY + ")");
-            const d = "M 0,0 V 1000 H 1000 V 0 Z m 500,282.07812 c 44.58849,0.034 88.09441,13.74154 124.64648,39.27735 H 774.50781 V 778.27148 H 225.49219 V 321.35547 H 375.64062 C 412.1126,295.87541 455.50922,282.16887 500,282.07812 Z";
```
Comment (lukecologne) [inline A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_SvgMaskElement.js:58]: You cannot change the mask like this. It also masks map elements such as waypoints, airports, traffic aircraft etc.

**Comment by Inaxair** [comment]
Can you also work the tilt clicks? Just wondering

File: A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_SvgMaskElement.js (hunk 1 above)
Comment (2hwk) [reply A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_SvgMaskElement.js:58]: True, I'll be looking into this more... The default mask is also wrong from the real airbus however, so this might as well be looked into while I am here.

image

**Comment by 2hwk** [comment]
> 
> 
> Can you also work the tilt clicks? Just wondering

Probably not, given how little is exposed (NetBingMap). Trying to figure out how the configuration file works for that is tricky, and I don't think they have tilt as configurable here. A long term fix is building our own WX/TERR but that will be on the backburner for a while, because then we need to figure out how to ingest terrain and weather data from the sim.

File: A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_SvgMaskElement.js (hunk 1 above)
Comment (2hwk) [reply A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_SvgMaskElement.js:58]: Ok scratch that, I think I'll just open a new issue for this. I'll try not to break it even more with the mask changes.

**Comment by lukecologne** [comment]
Really like these changes, but there is a small issue: For some reason, in Arc mode, waypoints aren't masked at the bottom anymore (this doesn't happen in the rose modes):
grafik

**Comment by 2hwk** [comment]
> 
> 
> Really like these changes, but there is a small issue: For some reason, in Arc mode, waypoints aren't masked at the bottom anymore (this doesn't happen in the rose modes):
> EDIT: It also doesn't happen when TERR ON ND is active, but it does happen without either WX and terr active.
> grafik

This is intentional, there isn't meant to be masking here. 

The masking on the TERR view is wrong, it's like that simply because that was the least worst option of dealing with NetBingMap, it's unfortunate but as terrain will need to be overhauled at some point, I don't consider this a high priority item. (Don't really feel like spending that time sorting through the mess in SvgMap/SvgMapElement etc.)

https://www.youtube.com/watch?v=TEi-WX08ov8

**Comment by lukecologne** [comment]
Alright then, the rest works very nicely. LGTM!

**Review by lukecologne — APPROVED** [review]

**Comment by tareksabet** [comment]
Name: tarek_sabet#7946
Date of testing: Current date 20/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1458 

Testing technique: Tryout
Steps you've made to test the Pull Request:
1. spawn the plane in C & D state and on the runway 
2. spawned in the middle in a bad weather i.e Dubblin 
3. turned on the WX radar
4.
5.

Overall Rating: Good
Conclusions of the testing: Everything works well as described. LGTM
