### PR TITLE
Fix DES phase

### LINKED ISSUE #444: [BUG] FMC not triggering DES phase : Speed remaining at cruise
**Mod Version**
0.2.0 and previous

**Describe the bug**
The FMC doesn't trigger DES phase on PERF page after reaching the top of descent.
As consequence, the FMC remains in CRZ mode for the descent causing the speed to remain at the cruise speed instead of going to descent speed.
Depending on your ILS approach, the flight path might not cross the decel point. See workaround below if happening.

**To Reproduce**
Perform any flight planned via the world map using an ILS approach.

**Expected behavior**
I'm no real pilot. From the FSlabs A320, we should get a Decelerate message when reaching top of descent.
At that point, when setting a lower altitude and pushing the knob, the FMC PERF should change to DES and reach the DES speed instead of remaining at cruise speed.

**Actual behavior**
The speed remains at cruise speed instead of going to descent/approach speed when descending/reaching approach point.

**References**
FSlabs A320 descent video of expected behavior: https://www.youtube.com/watch?v=mGVGOxbtRK8

**Workaround**
When reaching top of descent: manually set the speed on the Flight control Unit to the descent speed and set the altitude according to the ATC : the top of descent looks properly estimated to remain at or close to idle thrust for the descent speed on the DES PERF page.
When coming in range of the localizer (LOC* or LOC), manually trigger the approach phase on the FMC and set back the speed to managed (---) on the FCU.

Example of DECEL point out of flight path requiring to trigger approach manually
93127320-4c5cd880-f693-11ea-9af2-32981764813d

**Extra note**
Thanks guys for all the job done on improving the default A320 :)

### LINKED ISSUE #843: [BUG] wrong appearance of ALT CRZ on the FMA
**Mod Version**

Master, latest one

**Describe the bug**

it shows ALT CRZ on the FMA when descending and getting to an altitude lower than the CRZ level 
ex: descending to FL110 and showing ALT CRZ when maintaining the Altitude   

**To Reproduce**

1.start the flight
2. insert the CRZ LEVEL on the MCDU, start the flight
3. start descent i.e : FL110 and you're going to find ALT CRZ

**Expected behavior**

after the descent to FL110 it should appear ALT not ALT CRZ 

**Actual behavior**

after the descent to FL110 it shows ALT CRZ 

**References**

Desktop Screenshot 2020 09 24 - 16 26 54 76

**Additional context**

tarek_sabet#7946 (if different from GitHub):

### PR DESCRIPTION
**Pull request by AdenFlorian**
Fixes #444
Fixes #843

**Summary of Changes**

Fixes descent phase so that it is at least activated. It's not 100% realistic, it just fixes a small bug in the original asobo code that kept descent phase from activating at all.

Also fixes so Activate appr phase is not an option on the DES page when not actually in the DES phase, but it does show up when in DES phase on the DES page.

Also some more tweaks to the yellow aircraft symbol on the pfd att indicator.
Made the center rect 2 px bigger, and made it so the yellow border goes in front of the green FD bars, but the black rect is behind the green FD bars.

Also sets default brightness for ECAMs to match PFD and ND.

**Screenshots (if necessary)**

image

**Additional context**

Discord username (if different from GitHub):

### CODE REVIEW

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js [hunk 1]
```diff
@@ -442,7 +442,7 @@ class CDUPerformancePage {
         }
         let bottomRowLabels = ["PREV", "NEXT"];
         let bottomRowCells = ["<PHASE", "PHASE>"];
-        if (mcdu.currentFlightPhase === FlightPhase.FLIGHT_PHASE_CLIMB) {
+        if (mcdu.currentFlightPhase === FlightPhase.FLIGHT_PHASE_DESCENT) {
```
Comment (AdenFlorian) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js:445]: this fixes it so the "activate appr phase" action will appear on the DES page when DES phase is active

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js [hunk 2]
```diff
@@ -936,23 +937,26 @@ class A320_Neo_CDU_MainDisplay extends FMCMainDisplay {
...
                     Coherent.call("GENERAL_ENG_THROTTLE_MANAGED_MODE_SET", ThrottleMode.AUTO);
                 }
             }
         }
-        //Default Asobo logic
+        //(Mostly) Default Asobo logic
         if (this.currentFlightPhase === FlightPhase.FLIGHT_PHASE_CRUISE) {
             const altitude = SimVar.GetSimVarValue("PLANE ALTITUDE", "feets");
-            const cruiseFlightLevel = this.cruiseFlightLevel;
+            const cruiseFlightLevel = this.cruiseFlightLevel * 100;
```
Comment (AdenFlorian) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js:949]: this fixes the DES phase so it will actually activate.

**Comment by AdenFlorian** [comment]
2 qa have had successful tests with this.
