### PR TITLE
fix(mcdu): radnav manual ils freq entry no crs set

### LINKED ISSUE #7054: Amber boxes RAD NAV > CRS should not appear without LS frequency
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-04-09T10:04:00+00:00",
  "ref": "HEAD",
  "sha": "1c25455bb17e2a0015cb22c9d9c1ad299bf2bfa5",
  "actor": "Benedict Etzel <developer@beheh.de>",
  "event_name": "manual",
  "pretty_release_name": "rust-fwc:1c25455b"
}
```

### Describe the bug

The empty RAD NAV page currently shows the amber boxes in CRS:

RAD NAV page with amber boxes in CRS

### Expected behavior

The amber boxes should not be show without an LS frequency, and instead the field should display as follows:
```
CRS
[  ]
```

The amber boxes should only appear when the frequency is set manually. When setting an ident, the CRS is set automatically.

### Steps to reproduce

1. Start a flight cold and dark
2. Power up and open the RAD NAV page
3. Observe amber boxes in CRS

### References (optional)

https://discord.com/channels/738864299392630914/748096886531162123/963859784577196102

### Additional info (optional)

Originally reported by FlyingCarpet7

### Discord Username (optional)

_No response_

### PR DESCRIPTION
**Pull request by derl30n**
Fixes #7054

## Summary of Changes

The amber boxes should not be show without an LS frequency, and instead the field should display as follows:
```
CRS
[  ]
```
The amber boxes should only appear when the frequency is set manually. When setting an ident, the CRS is set automatically.

## Screenshots (if necessary)

| image | image |
| --- | --- |
| image | image |

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## Testing instructions

Ensure the above cases can be observed in the sim.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

File: flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_NavRadioPage.js [hunk 1]
```diff
@@ -133,7 +133,9 @@ class CDUNavRadioPage {
                 if (lsCourse >= 0) {
                     ilsCourseCell = `{${mcdu.ilsCourse !== undefined ? 'big' : 'small'}}F${lsCourse.toFixed(0).padStart(3, "0")}{end}`;
                 } else {
-                    ilsCourseCell = "{amber}____{end}";
+                    if (mcdu._ilsFrequencyPilotEntered) {
+                        ilsCourseCell = "{amber}____{end}";
+                    }
```
Comment (tracernz) [inline flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_NavRadioPage.js:138]:
```js
                } else if (mcdu._ilsFrequencyPilotEntered) {
                    ilsCourseCell = "{amber}____{end}";
                }
```

**Review by tracernz — APPROVED** [review]

**Comment by mico975** [comment]
Quality Assurance Tester Report

Discord          : mico#3145
Object of testing: #7056
Tier of Testing  : 1
Date             : 14/04/2022

Testing Process: 
Checked all ways of inputing an ILS as requested.

Negatives:       
Is it supposed to auto set the course but not the identifier with manual frequency input like shown below? It shows the identifier on the PFD with only frequency input.
image
image

Testing Results: 
Passed

Conclusions: 
LGTM

Media:       
image
image
image
image

**Comment by tracernz** [comment]
> Quality Assurance Tester Report
> 
> Discord : mico#3145 Object of testing: #7056 Tier of Testing : 1 Date : 14/04/2022

MSFS does not include course information with localisers in the nav database, only when tuned and received which is when we start displaying the course for manually tuned navaids... for autotuned ones we get the course from the approach navdata, but that isn't really feasible for manually tuned navaids.
