### PR TITLE
fix(fmgc): improve ils auto-tuning

### LINKED ISSUE #5129: ILS Frequency not autopopulating in the RADNAV page/
### Aircraft Version

Development

### Build info

```json
"built": "2021-06-15T09:33:40+00:00",
  "ref": "master",
  "sha": "bcdc52c59d7ec4235aaeb0a6036143b6ac0587a6",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

When I select the ILS in my arrival on the flight plan page, it no longer auto fills the frequency in the RADNAV page. It stopped working after I updated to the latest dev and its not working on the same airports that i can confirm worked before.

### Expected behavior

It should auto populate the ILS Frequency field in the RADNAV page after selecting it in the flight plan page

### Steps to reproduce

Spawn at the gate.
Import or set up a flight plan.
Select arrival ILS
Check RADNAV page

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

Cryptic#4731

### PR DESCRIPTION
**Pull request by tracernz**
Fixes #5129

## Summary of Changes

- only tune when within 300 NM of destination runway
- loosen approach name regex to match multiple approaches of same type

## Additional context

Covered by previous changelog entry: https://github.com/flybywiresim/a32nx/blame/ff9f83e498bfbfd90edd3335f99daf1575fcd5fd/.github/CHANGELOG.md#L112

Discord username (if different from GitHub):

There are further possibilities but they have drawbacks (no ident or course), e.g.
```js
            // If we still didn't find an ILS, fall back to finding the frequency with other spottier methods... this won't give us ident or course
            // some airports have ILS in the named frequencies list, some don't. some have _some_ of the frequencys in primary/secondaryIlsFrequency, some have none
            if (!this.ilsAutoTuned) {
                if (runway.primaryILSFrequency && runway.primaryILSFrequency.freqMHz > 1) {
                    this.connectIlsFrequency(runway.primaryILSFrequency.freqMHz);
                    this.ilsAutoTuned = true;
                    return;
                }

                const rwyPattern = new RegExp(`^(ILS|LOC).+RW${Avionics.Utils.formatRunway(runway.designation)}$`);
                for (let i = 0; i < airport.frequencies.length; i++) {
                    const match = airport.frequencies[i].name.match(rwyPattern);
                    if (match !== null) {
                        this.connectIlsFrequency(airport.frequencies[i].mhValue);
                        this.ilsAutoTuned = true;
                        return;
                    }
                }
            }
```

## Testing instructions

Test some departures and make sure ILS/LOC is auto-tuned once runway selected in flightplan. Test some approaches and make sure ILS/LOC is auto-tuned when within 300 NM of destination. Noted issues are at YPAD, YSSY and YMML.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by Cryptic56** [comment]
Worked great!

File: flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js [hunk 1]
```diff
@@ -1909,10 +1918,12 @@ class FMCMainDisplay extends BaseAirliners {
             runway = this.flightPlanManager.getDepartureRunway();
         }
 
+        // If the airport has correct navdata, the ILS will be listed as the reference navaid (originIcao in MSFS land) on at least the last leg of the
+        // ILS approach procedure(s). Tuning this way gives us the ident, and the course
         if (airport && airport.infos && runway) {
             for (let i = 0; i < airport.infos.approaches.length && !this.ilsAutoTuned; i++) {
                 const appr = airport.infos.approaches[i];
-                const match = appr.name.trim().match(/^(ILS|LOC) (RW)?([0-9]{1,2}[LCR]?)$/);
+                const match = appr.name.trim().match(/^(ILS|LOC) (RW)?([0-9]{1,2}[LCRT]?)(\s+[^LCRT])?$/);
```
Comment (beheh) [inline flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js:1926]: With this regexp growing it would be good to give a little bit of rationale in a comment. What's the T for? When would we expect whitespaces and a non-LCRT at the end?

Comment (tracernz) [reply flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js]: Yep, fair call. I have added some explanation, and improved the regex slightly after another review of ARINC424 and some Navigraph, and Asobo navdata examples.

**Review by wpine215 — APPROVED** [review]

**Comment by St54Kevin** [comment]
The guy in the #5129 Issue said he cannot reproduce after WU5, maybe this PR is obsolete then?

**Comment by tracernz** [comment]
> The guy in the #5129 Issue said he cannot reproduce after WU5, maybe this PR is obsolete then?

No, this is definitely not obsolete. My previous logic did not recognise approaches at airports with multiple ILS approaches for the same runway (where they each get a suffix, usually starting at Z and working back toward A). This is common in Australia in particular. I also discovered an issue with Navigraph's data for some Australian airports which they are fixing (maybe already fixed).

**Comment by BritishAvgeek** [comment]
Quality Assurance Tester Report

Object of testing: #5154
Tier of Testing: 2
Date: 23/06/2021

Testing Process: 
1. Spawned C&D at LGAV and configured for a flight to LCLK using a VOR departure (KEA2L from 03L). RADNAV page checked prior to inputting SID, all blank, checked after inputting SID and it auto-tuned the correct ILS frequency for a return and correct course.
2. Checked a few others on a test flight to LCLK prior to streaming and all worked as expected!
3. Going to fly the route live shortly, replicating everything above - if I come across anything I'll update accordingly with additional info


Negatives: N/A
Testing Results: Passed

Conclusions: Works fine, thanks!
Media: 
image

**Comment by TwitchyShell** [comment]
# Quality Assurance Tester Report

**Discord:** Тайга Мөңгүн#2000
**Object of testing:** #5154
**Tier of Testing:** 2
**Date:** 20/06/2021

# **Testing Process:** 
Premise: Previous experience has been noted that issues with the ILS autotune exist in previous builds as follows.
UHPP - ILS will not autotune
UHWW - ILS will not autotune
UHSS - ILS frequency is incorrect (runways are flipped)
In addition, UHHH has been selected for testing due to multiple ILS approach suffixes, and YSSY selected for testing as it is noted as a problem airport (since been resolved by navigraph)

Full line flights conducted,
UHPP-UHHH
UHHH-UHWW
UHWW-UHSS
YBSU-YSSY

RADNAV page was observed after every departure and approach entry.

In all instances, ILS successfully tuned once departure runway has been selected (for those with an associated ILS). ILS was also successfully filled, and later tuned once within range. Unfortunately, I have not been able to test tuning at the 300nm mark since approach selection was conducted close to top of descent.

I have decided not to include screenshots as in every instance, it has performed as expected with the correct identifier and frequency put in.

## **Negatives:** N/A
## **Testing Results:** Passed

# **Conclusions:** PR works as described and intended.
# **Media:** Omitted
