### PR TITLE
fix(mcdu): amber coloring for efob values

### LINKED ISSUE #3464: [BUG] Fuel for alt arrival airport often shows a negative valuse after some time.
**Mod Version**
 Custom AP, but is also present in dev build i believe

**Describe the bug**

EFOB for alt arrival shows a negative value after not visiting the FUEL PRED page for a while

**To Reproduce**

1. Start any flight that includes an alt arrival airport (preferably one made through simbrief)
2. After setting up the flight and taking off wait around 30-45 mins and go to the FUEL PRED page 
3. Observe how the alt airrival airport first shows a negative or wrong value then updates after a few seconds.

**Expected behavior**

EFOB for alt arrival airport should be upto date and accurate without having to open the FUEL PRED page

**Actual behavior**

EFOB for alt arrival airport is incorrect and sometimes negative

**References**

https://streamable.com/idc0b0

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game? I dont think vanilla has the fuel pred page

Discord username (if different from GitHub): Glitched

### PR DESCRIPTION
**Pull request by erso44**
Fixes #3464 

## Summary of Changes

• alternate dest efob will turn amber when value is bewlow min value
• minus "counting" is still working for dest efob and alt dest efob. It displays how much fuel is needed.

The main question regarding this ticket was, what will happen when alt dest efob value is below zero. It just gets a negative value.

## Screenshots (if necessary)

Before:
image

After:
image

## Additional context

Get in contact with me if something is wrong.

Discord username (if different from GitHub): erso44

## Testing instructions

Just follow the same steps in the issue ticket.
Set your fuel manually until alternate EFOB is >0.2.
Fly.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by davidwalschots — COMMENTED** [review]
There's still an open discussion in #pilot-feedback on whether or not negative values are displayed. https://discord.com/channels/738864299392630914/754851312306487326/854309024715374623
Until we figure that out this PR cannot be completed.

Note that we usually add new items to the CHANGELOG below the existing items.

File: flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js [hunk 1]
```diff
@@ -2593,7 +2593,11 @@ class FMCMainDisplay extends BaseAirliners {
      * @returns {number} Returns EFOB when arriving at the alternate dest
      */
     getAltEFOB(useFOB = false) {
-        return this.getDestEFOB(useFOB) - this._routeAltFuelWeight;
+        const altEFOB = this.getDestEFOB(useFOB) - this._routeAltFuelWeight;
+        if (altEFOB <= 0) {
+            return 0;
+        }
+        return altEFOB;
```
Comment (Lucky38i) [inline flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js:2600]: if this does get approved you can try 
```js
const altEFOB = this.getDestEFOB(useFOB) - this._routeAltFuelWeight;
return altEFOB <= 0 ? 0 : altEFOB
```

**Review by Lucky38i — COMMENTED** [review]
Just a tidbit, in your intial post it's always useful to provide a reference. I do agree with David, without a viable reference this change doesn't seem warranted

**Comment by erso44** [comment]
> There's still an open discussion in #pilot-feedback on whether or not negative values are displayed. https://discord.com/channels/738864299392630914/754851312306487326/854309024715374623
> Until we figure that out this PR cannot be completed.
> 
> Note that we usually add new items to the CHANGELOG below the existing items.

working on the feedback.

**Comment by beheh** [comment]
This is a slightly tangential issue, but touches the same field. One reference I have states this:

> The EFOB value turns amber when the estimatied fuel on board at the destination is below the minimum fuel on board defined in the FUEL PRED page after engine start.

So in your example, as 0.8 is below the 2.1 MIN DEST FOB we should expect the 0.8 to be amber-colored.
The question is still what actually happens when it's below 0. I've seen other references have an amber NEG in that case instead, but I'm not sure if that applies to Honeywell and this specific field. A reference for this change is still required.

**Comment by erso44** [comment]
From reference (private messages with pilots) ALT DST EFOB below 0.8 will be displayed amber.
800 KG of fuel is the min amount of fuel which is needed for alternating.

It is still not clear what will be displayed at or below 0.0.

One pilot said that a negative figure will be displayed when EFOB is below zero.
Two pilots said they are not sure.

a320dp.com (http://www.a320dp.com/A320_DP/nav-flight-management/sys-14.10.1.html) says when extra fuel is negativ dashes will be displayed. For consistency on FUELDPRED side I have decide to display ambered dashes when ALT DST EFOB is at/below zero.

I did not find any documentation about the honeywell pegasus 2.
Thales also does not include informations.
We can later change this behaviour if we get more detailed references.
Also keep in mind that this situation could be very rare.

I can imagine that this case could be documentet in the emergency handling procedures (for example when in mid-flight fuel is leaking) but I do not think that we will get access.

This is the current solution:
image
image

File: .github/CHANGELOG.md [hunk 2]
```diff
@@ -112,6 +112,7 @@
 1. [MCDU] Fixed performance page refresh on flight phase transition - @MisterChocker (Leon)
 1. [ATHR] Fixed permanent A/THR disconnect (15s press) not being able to activate with 3D button on thrust levers - @aguther (Andreas Guther)
 1. [ND] TCAS symbols correctly display in 10, 20, 40nm ARC/ROSE views + bug fixes - @2hwk (2Cas#1022)
+1. [MCDU] When aircraft can not reach alternate destination EFOB value stays positiv - @erso44 (Ersin Karakilic)
```
Comment (beheh) [inline .github/CHANGELOG.md:115]:
```suggestion
1. [MCDU] When aircraft can not reach alternate destination EFOB value stays positive - @erso44 (Ersin Karakilic)
```

File: flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FuelPredPage.js [hunk 3]
```diff
@@ -148,9 +148,17 @@ class CDUFuelPredPage {
                 };
                 if (mcdu.altDestination) {
                     altIdentCell = mcdu.altDestination.ident;
-                    altEFOBCell = (mcdu.getAltEFOB(true) * mcdu._conversionWeight).toFixed(1);
-                    altTimeCellColor = "[color]green";
+                    const altEFOBCellVal = (mcdu.getAltEFOB(true) * mcdu._conversionWeight).toFixed(1);
                     altEFOBCellColor = "[color]green";
+                    altEFOBCell = altEFOBCellVal;
+                    if (altEFOBCellVal < 0.8) {
```
Comment (beheh) [inline flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FuelPredPage.js:154]: As per a reference I have it is not exactly below 0.8, it's below whatever the final reserve is (which comes out to 0.8 by default at the moment, but can be different).

**Review by beheh — CHANGES_REQUESTED** [review]

File: flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FuelPredPage.js (hunk 3 above)
Comment (erso44) [reply flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FuelPredPage.js]: ALT DEST EFOB value turns amber when less than FINAL value.

Please provide next time your references and also provide a possible solution regarding calculations.

**Comment by erso44** [comment]
not clear what result is expected.

**Comment by NitroMaxx72** [comment]
On Wednesday, I will have accurate information with a photo from a real pilot, I think it's worth waiting

**Comment by erso44** [comment]
> On Wednesday, I will have accurate information with a photo from a real pilot, I think it's worth waiting

Did get any information ?

**Comment by erso44** [comment]
Is your post broken ? Can not see it.

**Comment by NitroMaxx72** [comment]
> src ссылки на изображение не работает.

I have corrected the post

**Comment by erso44** [comment]
great ! thank you !

**Comment by tracernz** [comment]
Also note that is a Thales MCDU (split brightness key, and serifs on the Is).

**Comment by erso44** [comment]
currently I have implemented that
- alt dest efob will turn amber when value is below min dest efob.
- dest efob and alt dest efob values can be negative

File: flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FuelPredPage.js (hunk 3 above)
Comment (erso44) [reply flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FuelPredPage.js]: done

File: .github/CHANGELOG.md (hunk 2 above)
Comment (erso44) [reply .github/CHANGELOG.md:115]: what about this ? :D

Comment (erso44) [reply .github/CHANGELOG.md]: changelog message improved

File: flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FuelPredPage.js [hunk 4]
```diff
@@ -148,9 +148,13 @@ class CDUFuelPredPage {
                 };
                 if (mcdu.altDestination) {
                     altIdentCell = mcdu.altDestination.ident;
-                    altEFOBCell = (mcdu.getAltEFOB(true) * mcdu._conversionWeight).toFixed(1);
-                    altTimeCellColor = "[color]green";
+                    const altEFOBCellVal = (mcdu.getAltEFOB(true) * mcdu._conversionWeight).toFixed(1);
```
Comment (Lucky38i) [inline flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FuelPredPage.js:151]: what's the purpose of this const?

Comment (erso44) [reply flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FuelPredPage.js:151]: its the current alt dest efob value or what do you mean ?

Comment (erso44) [reply flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FuelPredPage.js:151]: resolved as we talked.

File: flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js (hunk 1 above)
Comment (erso44) [reply flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js]: not necessary

**Review by beheh — APPROVED** [review]

**Comment by MisterChocker** [comment]
@beheh do we have Honeywell reference on this particular issue or do we use the Thales reference for now?

**Comment by beheh** [comment]
@MisterChocker While I haven't seen one, I strongly suspect this is the same and would be okay to merge unless proven otherwise. But you're right, if possible we should get a Honeywell reference, especially as it seems like this can be relatively easily replicated on the ground.

**Comment by MisterChocker** [comment]
Alright, I'll hand this to QA now while I've also requested references. In the mean time I am okay to use the Thales reference instead until we get Honeywell refs.

**Comment by ShadowFrost3** [comment]
Quality Assurance Trainee Report


Object of testing: #5122
Tier of Testing:1
Date: 01/08/2021

Testing Process: C&D, load aircraft for a flight, get to cruise, adjust fuel values to bring alternate EFOB both into negatives, above 0, and above 2.1 (alternate requirement) to see if turn amber as well as negative. 
Negatives: N/A
Testing Results: Passed

Conclusions: Nice
Media: 
image
image
image
image

**Comment by NUTTTTTTTT** [comment]
Quality Assurance Trainee Report

Discord: █▀█ █▄█ ▀█▀#2123
Object of testing: #PR 5122
Tier of Testing: 1
Date: 02/08/2021

Testing Process: Spawned C+D at the gate, set up plan from EGCC to EHAM filling W+B and fuel pred pages prior to departure. Checked values on the ground using the weight menu, anything below 1.6 EFOB at alternate showed amber where min dest FOB was 1.6.

Adjusted fuel to show 0.2 EFOB at alternate, took off and flew until this was at a negative. Showed -0.7 amber. 

Negatives: N/A

Testing Results: Passed

Conclusions: Worked as expected, all values showed correctly and changed to amber when expected.

Media:
image
image
image
image

**Comment by BritishAvgeek** [comment]
Quality Assurance Tester Report

Object of testing: #5122
Tier of Testing: 1
Date: 02/08/2021

Testing Process: 
1. Spawned Cold and Dark at EPKK, configured for flight to LGIR and fiddled fuel quantities to check Fuel Pred and EFOB values
2. Multiple values displayed minus and amber fonts
3. Normal flight was tested too with a full flight, no issues

Negatives: N/A
Testing Results: Passed

Media: 
image
image

File: flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FuelPredPage.js [hunk 5]
```diff
@@ -148,9 +148,12 @@ class CDUFuelPredPage {
                 };
                 if (mcdu.altDestination) {
                     altIdentCell = mcdu.altDestination.ident;
+                    altEFOBCellColor = "[color]green";
                     altEFOBCell = (mcdu.getAltEFOB(true) * mcdu._conversionWeight).toFixed(1);
+                    if ((mcdu.getAltEFOB(true) * mcdu._conversionWeight).toFixed(1) < (mcdu._minDestFob * mcdu._conversionWeight).toFixed(1)) {
```
Comment (Lucky38i) [inline flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FuelPredPage.js:153]: perhaps 
```js
if (altEFOBCell < (mcdu._minDestFob * mcdu._conversionWeight).toFixed(1)) 
```
otherwise LGTM

**Comment by Samueleonard** [comment]
Quality Assurance Tester Report

Discord: 1samueleonard1
Object of testing: (#5122 )
Tier of Testing: (1)
Date: (03/08/2021)

Testing Process: 
. loaded in, programmed mcdu etc
. tweaked FUEL PRED to get negative value, value went amber

Negatives: n/a

Testing Results: (Passed)

Conclusions: assuming the logic is accurate, PR works as per description
Media: n/a

**Comment by davidnorfolk96** [comment]
Quality Assurance Trainee Report

Discord: !davidn123#0001
Object of testing: 5122
Tier of Testing: 1
Date: 03/08/2021

Testing Process: 
Loaded up C+D stand 4 at LOWI, Using simbrief i pull a test flightplan from LOWI to EGKK & the ALTN being LFPG. I then proceeded to using the fuel & payload given by simbrief using the ATSU.I then went & played with different fuel values to get it into the minus & turn it amber. This was successful & no issues were found  

Negatives: N/A

Testing Results: Passed

Media:
Screenshot_2
Screenshot_4
