### PR TITLE
fix(aoc): WX Request airport list handling

### LINKED ISSUE #3413: [BUG] [AOC] Weather request airports not changeable in flight
**Mod Version**

Current Custom FBW 8th Feb 21, 8419210

**Describe the bug**

Dep and Arr field will turn green in the AOC METAR request page, when taking off. They are not editable

**To Reproduce**

1. Request METARs on ground (Havent tested another airport than Dep Arr)
2. Takeoff
3. Both airports turn green and are not editable

**Expected behavior**

They should stay blue and be able to be deleted or modified.
**NOTE:** Im used to IRL Thales MCDU. But I think this is the same with Honeywell

**Actual behavior**

Stays green 

**References**

image

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by MisterChocker**
Fixes #3413
This pr replaces #3450

## Summary of Changes

- Added airport list initialization with FMGC initialization,
- Airport list gets auto feed FMGC airports such as Departure, Arrival and Alternate (also auto populates with SimBrief!),
- Airport list gets updated (if still possible due to rules) when Arrival or Alternate changes,
- FMGC Airports (the green ones) can be cleared,
- New Airports (the cyan ones) can be entered and cleared.

## References

https://discord.com/channels/738864299392630914/754851312306487326/854716331743117373 and following

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## Testing instructions

- Use MSFS flight planer/simbrief or enter dep/arr/alt manaually,
- Also leave Arrival Airport empty in MSFS menu so FROM/TO on init-a is empty and observe 4 cyan brackets,
- Clear fmgc airports and enter new ones, also clear them.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

File: flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_RequestsWeather.js [hunk 1]
```diff
@@ -19,105 +12,73 @@ class CDUAocRequestsWeather {
...
+                    getMETAR(icaos, lines, sendStatus, updateView);
                 } else {
-                    getTAF(icaos, lines, store, updateView);
+                    getTAF(icaos, lines, sendStatus, updateView);
                 }
             };
 
             getInfo().then(() => {
-                store["sendStatus"] = "SENT";
+                sendStatus = "SENT";
```
Comment (Saschl) [inline flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_RequestsWeather.js:75]: Can't we remove setting `sendStatus` in `getMETAR` and `getTAF` if it's already set here?

File: flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_AirportList.js [hunk 2]
```diff
@@ -0,0 +1,77 @@
+const airportTypes = {
```
Comment (MisterChocker) [inline flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_AirportList.js:1]: We actually don't need airport types since Dep, Arr and Alt have their dedicated row.
It's just important to know whether it's managed or not.

File: flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_RequestsWeather.js (hunk 1 above)
Comment (MisterChocker) [reply flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_RequestsWeather.js:75]: intellij actually marks these two as unused xD

File: flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_AirportList.js (hunk 2 above)
Comment (MisterChocker) [reply flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_AirportList.js]: Replaced airportTypes with isManaged boolean

File: flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_RequestsWeather.js (hunk 1 above)
Comment (Saschl) [reply flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_RequestsWeather.js:75]: Sorry for the nitpicking but then let's remove the parameters in the method as well and I'm happy :D

Comment (MisterChocker) [reply flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_RequestsWeather.js:62]: Do you mean this parameters? `reqID` and `_sendStatus` from `static ShowPage(mcdu, reqID = 0, _sendStatus = "")`?

Comment (Saschl) [reply flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_RequestsWeather.js:62]: Exactly, thanks!

**Review by Saschl — APPROVED** [review]
LGTM!

**Comment by Illuminati270** [comment]
Tested & Approved! Well done!

**Comment by BritishAvgeek** [comment]
Quality Assurance Tester/Trainee Report

Object of testing: #5137
Tier of Testing: 1
Date: 17/06/2021

Testing Process: 
Full Flight from VCBI to VOMM
1. Requested Wx in MCDU, allowed different entries prior to any flight plan being formed
2. Imported simbrief data, checked AOC and it had Dep, Arr and Alt Airports in the Wx Req page
3. Able to delete said entries manually
4. Turned around for second sector VOMM to VCBI and checked again
5. All as above!

Negatives: None!
Testing Results: Passed

File: flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_AirportList.js [hunk 3]
```diff
@@ -0,0 +1,71 @@
+/**
+ * This method assembles the airport data which contains the raw data as well as the OutPut that can be seen on the page
+ * @param _icao {string}
+ * @param _isManaged {boolean}
+ * @returns {{outPut: string, icao: string, isManaged: boolean}}
+ */
+function assembleAirportInfo(_icao = "", _isManaged = false) {
+    return { icao: _icao, isManaged: _isManaged, outPut: `{${!_isManaged || !_icao ? "cyan" : "green"}}${_icao ? _icao : "[ ]"}{end}` };
```
Comment (beheh) [inline flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_AirportList.js:8]: Can we please use `output` instead of `outPut`? :sweat_smile:  I've never seen the latter.

Comment (MisterChocker) [reply flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_AirportList.js:8]: WILCO

**Comment by St54Kevin** [comment]
**Quality Assurance Tester**

Object of testing: #5137 
Tier of Testing: 1
Date: 18/06/2021

**Testing Process:**
1. Loaded C&D -> 4 cyan brackets
2. Loaded random FPL (DEP/ARR) -> two green airfields
3. Put in ALT -> 3 green airfields
4. Tested deletion and overwriting

**Negatives:** 
- Im not familiar with Honeywell but are you sure there are only 4 airports for WX request rather than 5?
- 
**Testing Results:** Passed

**Comment by MisterChocker** [comment]
> - Im not familiar with Honeywell but are you sure there are only 4 airports for WX request rather than 5?

@Illuminati270 what ja your experience?

@St54Kevin FYI I haven't changed the amount of airports that can be entered, but a fifth can be added easily

**Comment by easyjetsimpilot** [comment]
Quality Assurance Tester

Discord: easyjetsimpilot
Object of testing: #5137
Tier of Testing: 1
Date: 18/6/21

Testing Process: 

1. Spawned at EFHK with MSFS Planner route set (EFHK-ESSA (alt EKCH)

All 3 Airports shown correctly in GREEN in the WX request AIRPORTS LIST. ICAO codes editable and turn green when a new code is entered. All 3 can also be CLR out. 


2. Spawned at EFHK with SimBrief route set (EFHK-EKCH) (alt EDDP)

All 3 Airports shown correctly in GREEN in the WX request AIRPORTS LIST. ICAO codes editable and turn green when a new code is entered. All 3 can also be CLR out. 

3 Spawned at EFHK with no route set. All 4 AIRPORTS entries  show blank blue [  ] 



Negatives: N/A
Testing Results: Passed

Conclusions: Works as expected! Thank you. 
Media:

**Comment by Illuminati270** [comment]
> > * Im not familiar with Honeywell but are you sure there are only 4 airports for WX request rather than 5?
> 
> @Illuminati270 what ja your experience?
> 
> @St54Kevin FYI I haven't changed the amount of airports that can be entered, but a fifth can be added easily

As far as I remember, it has only 4 as modeled. Never seen either Honeywell or Thales with 5. Very old ones had only 3.
