### PR TITLE
Fixed issue with self test turning on incorrectly on APU/GPU state change

### LINKED ISSUE #402: [BUG] Self test coming on when starting APU with external power on
**Branch**
master

**Describe the bug**
I think this is causing PFD and MFD to go into self test when turning on the APU, even though I'm on external power.

Also causes self test when leaving external power, even though my apu or engine is up and running.

**To Reproduce**
spawn cold and dark
turn on batteries and external power
turn on PFD/ND/ECAM displays
wait for self test to finish
turn on apu master and starter
wait for lap to open and apu to start spinning up
once that happens the PFD and MFD go into self test, but this shouldn't happen because we are on external power

**Expected behavior**

**Screenshots or Videos**
image

**Additional context**
We think it's caused by #363

### PR DESCRIPTION
**Pull request by ThePilot916**
This PR fixes #402 and changes are inline with soon to be implemented ELEC systems so that no changes/bare minimal changes may be required once ELEC systems are implementede.

### CODE REVIEW

**Comment by ThePilot916** [comment]
May want to include ```&& ACPowerAvailable``` in the if condition to ensure that it only runs when AC power is available and not otherwise.

**Comment by AdenFlorian** [comment]
Any idea why the CI is running on your branch?

**Comment by AdenFlorian** [comment]
@topiek-fs could you give your input on this if you have time?

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js [hunk 1]
```diff
@@ -71,14 +70,15 @@ class A320_Neo_EICAS extends Airliners.BaseEICAS {
...
-        var externalPower = SimVar.GetSimVarValue("EXTERNAL POWER ON", "bool");
-        var apuOn = SimVar.GetSimVarValue("L:APU_GEN_ONLINE", "bool");
-        let apuStatusChanged = (apuOn != this.APULastValue);
-        let externalPowerChanged = (externalPower != this.externalPowerLastValue);
-
-        var isACPowerAvailable = engineOn || apuOn || externalPower;
+        const engineOn = Simplane.getEngineActive(0) || Simplane.getEngineActive(1);
+        const externalPower = SimVar.GetSimVarValue("EXTERNAL POWER ON", "bool");
+        const apuOn = SimVar.GetSimVarValue("L:APU_GEN_ONLINE", "bool");
+        const isACPowerAvailable = engineOn || apuOn || externalPower;
```
Comment (AdenFlorian) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js:76]: Is this going to change once your electricity changes are finished? If so could you start putting comments on lines like that saying something like "This will be replaced with proper electricity logic in the future"?

**Comment by topiek-fs** [comment]
Without having tested it (someone else please do!) I think this is okay!

**Comment by AdenFlorian** [comment]
code looks good to me as well, testing it now!

**Comment by AdenFlorian** [comment]
So far this isn't working when testing from cold and dark
turn on batteris and ext power
turn on pfd brightness, it stays off, the Electricity element has state=off

@ThePilot916 Did you test your fix from cold and dark?

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js [hunk 2]
```diff
@@ -71,14 +70,15 @@ class A320_Neo_EICAS extends Airliners.BaseEICAS {
...
         
-        var engineOn = Simplane.getEngineActive(0) || Simplane.getEngineActive(1);
-        var externalPower = SimVar.GetSimVarValue("EXTERNAL POWER ON", "bool");
-        var apuOn = SimVar.GetSimVarValue("L:APU_GEN_ONLINE", "bool");
-        let apuStatusChanged = (apuOn != this.APULastValue);
-        let externalPowerChanged = (externalPower != this.externalPowerLastValue);
-
-        var isACPowerAvailable = engineOn || apuOn || externalPower;
+        const engineOn = Simplane.getEngineActive(0) || Simplane.getEngineActive(1);
+        const externalPower = SimVar.GetSimVarValue("EXTERNAL POWER ON", "bool");
```
Comment (AdenFlorian) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js:74]: setting this to const is breaking the game because later down in this function there is `var externalPower = ...` which ends up throwing an error.

**Review by AdenFlorian — CHANGES_REQUESTED** [review]

**Comment by AdenFlorian** [comment]
oh, i think CI is running on your branch because you're on the master branch on your fork

**Comment by AdenFlorian** [comment]
Also I pushed a fix to your branch fixing the error that was breaking lots of things.

Now it seems to mostly work, except the upper ECAM screen does not go into self test when turning power off and on, looking into that now.

**Comment by AdenFlorian** [comment]
upper ecam self test is working fine, i think i had some hot reload issue, finishing up testing now

**Review by AdenFlorian — APPROVED** [review]

**Comment by AdenFlorian** [comment]
@ThePilot916 FYI, in the future, please make a new branch for every PR on your fork, using master makes things weird, thanks!

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js (hunk 2 above)
Comment (ThePilot916) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js:74]: Weird, looks like this change wasn't staged somehow, my bad. Nice that you fixed it already.

**Comment by ThePilot916** [comment]
Ahh the CI running it on master makes sense.

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js (hunk 1 above)
Comment (ThePilot916) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js:76]: These lines will get deleted once implementation is complete, while all the conditions that read from the simvars will still remain the same.
