### PR TITLE
fix: large performance loss when using vertical speed sync

### LINKED ISSUE #5698: Vertical speed sync
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-22T09:34:12+00:00",
  "ref": "master",
  "sha": "41c0ae58d650410bcd438f7b020dec641c86be44",
  "actor": "2hwk",
  "event_name": "manual"
}
```

### Describe the bug

I was using flypad when i wanted to predict the descent with the mode "top of descent". then when i clicked on Sync on vertical speed, my fps goes from 60 to 15

### Expected behavior

Nothing, the system worked but my fps fell.

### Steps to reproduce

1. open flypad
2. go in the top of descent mode (near the landing prediction)
3. then go to descent angle and click the red X
4. click SYNC on vertical speed
5. and then the frames will drop

### References (optional)

_No response_

### Additional info (optional)

the issue start occurring from today

### Discord Username (optional)

TheRealEdge#1727

### PR DESCRIPTION
**Pull request by ErickSharp**
Fixes #5698

## Summary of Changes

Fixes issue with too many re-renders caused by inappropriate additional dependencies in a useEffect.

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by 2hwk — APPROVED** [review]

**Comment by NUTTTTTTTT** [comment]
Quality Assurance Tester Report

Discord: █▀█ █▄█ ▀█▀#2123
Object of testing: #PR 5699
Tier of Testing: 1
Date: 22/08/2021

Testing Process:
- Loaded in airborne as done in previous tests to identify the issue.
- Started in gentle descent in V/S - PASS - no fps impact
- Started EFB, opened descent calculator and tested sync functions
- Repeated for FPA - PASS - no fps impact
- Tested all other EFB functions to make sure nothing else had since broken - looks to be okay from testing

Negatives: None observed
Result: PASS

Conclusions: Fixes issue at hand with calculator syncing - gave a quick test over other functions again and no other issues observed.

File: src/instruments/src/EFB/TODCalculator/Data/Data.tsx [hunk 1]
```diff
@@ -63,7 +63,7 @@ const Data = ({
         }
 
         setTodData({ calculation: { input: syncedInput, type: calculationType } });
-    }, [calculationInputSyncEnabled, distance, verticalSpeed, pitchAngle, calculationType, inputValid, syncedInput]);
+    }, [calculationInputSyncEnabled, distance, verticalSpeed, pitchAngle]);
```
Comment (Benjozork) [inline src/instruments/src/EFB/TODCalculator/Data/Data.tsx:66]: I'm pretty sure this would also have been fixed by memoizing `syncedInput` and `inputValid`.

**Comment by oim1** [comment]
Quality Assurance Trainee Report

Object of testing: #5699
Tier of Testing: 1
Date: 23/08/2021

Testing Process: 
Loaded in at 5000ft above YMML
Set AP and ATHR
Started a 500fpm descent
Checked for performance issues
Turned on EFB
Went to performance page and synced V/S 
Checked for performance issues

Negatives: N/A
Testing Results: Passed

Conclusions: No performance issues when syncing V/S. LGTM
