### PR TITLE
feat: efis overlay, fix info, and other huge changes

### LINKED ISSUE #1181: Navigation Fix Info Page
**Describe the feature you'd like to see implemented**

_**FIX INFO Page**_
The Fix Info Page provides the pilots with some neat features that both helps the pilot and increases safety.

**What is it for?**
This feature enables pilots do draw circles around or radials from (nav) fixes to improve visuals on the ND and/or directly assist the pilots in stressful situations. This "lines" can be used as guidance and reference.

**What does it do?**
It draws dashed blue circles and lines from and around navigation fixes.

**When is this used in real life?**
This feature is mostly used on take-off, descend, approach and landing phases.

**How is it used?**

- **Take-off**
For take-off an extended runway center line from the departing runway is used.
_This line is used as guidance for an straight out departure in case of engine failure._
Also an 10nm (maybe also an 5nm) range circle around the arrival runway of the secondary flight plan is used.
_This will be used as reference when to start the final approach as most airports use a standardized approach with an 3° glide path angle that starts at 10nm from runway threshold._
**Why is this done?**
This reduces the workload of the pilots in an emergency at or shortly after v1.
At most standardized airports an 3° glide path starting at 10nm before the runway threshold is a common approach procedure.

- **Descend**
An 100nm range circle around the arrival runway is used to create an breath reference for the TOD.
_In real life it's common to not have a fully programmed (final) approach, therefore the calculated TOD by the FMS might be off or completely wrong._

- **Approach**
A 10nm range circle is used to visualize the beginning of the final approach.
A 5nm range circle can also be used as visual reference for landing config or speed, etc.
An extended center line is used for an straight out in case of engine failure.
An extended center line can be used to assist on short final at non standard ILS approaches.

**Additional context / reference**

image
image
image
image

Discord username DerL30N#3751

### PR DESCRIPTION
**Pull request by tracernz**
Fixes #1181

## Summary of Changes

- EFIS symbols are transmitted to the ND from the FMGC
  - `MAP PARTLY DISPLAYED` when too many words to send
  - Various other fixes as part of the implementation
- Waypoint, VOR/DME, NDB, and Airport overlay supported on ND (backed by temporary nearest facility impl. until FBW nav db available)
- Fix info partially implemented (radials and radii shown on ND, but no flightplan intercepts calculated)
- FA leg if no SID selected has correct bearing
- Runway loading code fixed
  - DER leg on SIDs works again
-  VOR reminder symbol not shown on ND for DME-only stations (bottom corners)
- TO waypoint data only shows when valid
- Speed constraints treated per the AMM for descent and approach
- Transition altitudes work correctly for constraint display on ND
- Various small fixes for ND

## Screenshots (if necessary)

image

## Additional context

Discord username (if different from GitHub):

## Testing instructions

- Make sure EFIS filters work.
- Make sure EFIS filters cause `MAP PARTIALLY DISPLAYED` message in an area with a lot of waypoints.
- Make sure FIX INFO feature works properly.
- Make sure there are no other regressions in ND symbology.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

File: src/fmgc/src/components/FmsMessages.ts [hunk 1]
```diff
@@ -155,6 +169,7 @@ enum FMMessageUpdate {
  */
 abstract class FMMessageSelector {
     abstract message: FMMessage;
+    abstract ndSide?: 'L' | 'R';
```
Comment (Benjozork) [inline src/fmgc/src/components/FmsMessages.ts:172]: **thought:** maybe rename this to `efisSide` since it can also be transmitted to the PFD

File: src/fmgc/src/efis/NearbyFacilities.ts [hunk 2]
```diff
@@ -0,0 +1,128 @@
...
+
+    private airportSessionId: number;
+    private ndbSessionId: number;
+    private vorSessionId: number;
+    private waypointSessionId: number;
+
+    private lastPpos = { lat: 0, long: 0 };
+    private throttler = new UpdateThrottler(10000);
+    private radius = 381 * 1852; // metres
+    private limit = 160;
```
Comment (Benjozork) [inline src/fmgc/src/efis/NearbyFacilities.ts:27]: **suggestion:** Move those factors to `MathUtils`

**Review by Benjozork — CHANGES_REQUESTED** [review]
LGTM, couple minor things (also fix lint 😉)

File: src/fmgc/src/efis/NearbyFacilities.ts (hunk 2 above)
Comment (tracernz) [reply src/fmgc/src/efis/NearbyFacilities.ts:27]: We should do that in the new nav database, which will entirely replace this file.

Comment (Benjozork) [reply src/fmgc/src/efis/NearbyFacilities.ts:27]: Hm? Unit conversions are not really related to the nav database.

Comment (Benjozork) [reply src/fmgc/src/efis/NearbyFacilities.ts:27]: I'm talking about whatever part of `381 * 1852` is a unit factor

File: src/fmgc/src/components/FmsMessages.ts (hunk 1 above)
Comment (tracernz) [reply src/fmgc/src/components/FmsMessages.ts:172]: I think we really need to treat ND, PFD, and MCDU messages separately in general. Because there are some messages that go to the MCDU, some that go to the ND, some that go to the PFD, and some that go to combination of those. That said, this is probably one that can be shared.

**Comment by tracernz** [comment]
> also fix lint 😉

Yeah, nah. 😛 We are either going to have to change the lint rules or do a __huge__ reformat of CFMS at some stage. 😩

File: src/fmgc/src/efis/NearbyFacilities.ts (hunk 2 above)
Comment (tracernz) [reply src/fmgc/src/efis/NearbyFacilities.ts]: I'd prefer to not do this in this PR, and instead bring in `uom-ts` and a suitable set of units defined on top of that in a future PR.

**Review by Benjozork — APPROVED** [review]

**Comment by Samueleonard** [comment]
Quality Assurance Tester/Trainee Report

Discord: 1samueleonard1
Object of testing: (#5908 )
Tier of Testing: (1)
Date: (30/09/2021)

Testing Process: 
. loaded on rwy at EGCC

**EFIS FILTERS**
. played with EFIS filters - all seem to work and react instantly now, unlike before
. entered SID - CSTR filter works still
. entered STAR + plan mode - CSTR filter works still

**FIX INFO**
. entered fix in fpln 
     . entered radials - appeared on ND as expected
     . entered radius - appeared on ND as expected
. entered 3 more waypoints to fill all pages
     . entered radials and radii - edited and deleted values to try different combinations - all works
. entered runway
     . entered reciprocal to create extended centerline - worked as intended
     . entered range rings for approach

Negatives:
. WPT filter seems limited in range? only extends a short distance around acft (may be an API issue)
Testing Results: (Passed)

Conclusions: I LOVE IT (will need more testing on a variety of locations and situations) 
Media: image here is some nice art i drew

**Comment by Mack674** [comment]
Quality Assurance Tester Report

Discord: Mack#674
Object of testing: #5908
Tier of Testing  : 1
Date: 01/10/2021

Testing Process: Full flight EGKK - LSZH:
- Spawned C&D at gate 105 at EGKK
- Checked all ND modes
- Departure RWY26L SID BOGN1X
- Cruise FL390
- Descend to GIPOL - 7000ft - STAR BLM2G
- GIPOL34 RNAV Transition
- ILS34 Landing
- Taxi to gate E45

Negatives: 
- missing Fix Info page (after departure)
- constraint at UTIXO is FL60 (should be 6000ft)      

Testing Results: Passed

Conclusions: The whole thing of this PR is very good, the main assumptions are met. All constraints of EGKK SID BOGNA1X displayed correctly, waypoint display and number of waipoints restriction is correct, 
VOR NDB and Airport displayed correctly (all modes are on screenshots), almost everything is correct. Very good PR, it adds good functionality to ND!

Media:

**Comment by jcalor** [comment]
Quality Assurance Tester Report

Discord          : Jorge#6816
Object of testing: #5908 
Tier of Testing  : 2
Date             : 1/10/2021

Testing Process: 

Full flight EGLL-EDDF:

- WP enabled on EFIS and MAP PARTLY DISPLAYED displayed on ND if there´s a lot of WPT to show - checked
- VOR.D, NDB A displayed on ND - checked
- Reviewed all ND and EFIS modes looking for issues - checked
- Normal flight to EDDF

Negatives:       

- FIX INFO page not available on arrival - known bug

Testing Results: Passed

Conclusions: Despite the known bug, PR has no issues - work as intended.

Media:
WPT
image
VOR.D
image
NDB
image
FIX INFO page (on departure)
image

**Comment by jcalor** [comment]
Quality Assurance Trainee Report

Discord          : Jorge#6816
Object of testing: #5908
Tier of Testing  : 1
Date             : 01/10/2021

Testing Process: 

- Same steps as previous test - all good
- Additional checked if FIX INFO displays on PPOS

Negatives: N/A

Testing Results: Passed

Conclusions: PR works as expected- no issues were found
