### PR TITLE
fix(mcdu): init-a tropo entry validation

### LINKED ISSUE #5032: [FMGS] TROPO field INIT A
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-06T15:12:39+00:00",
  "ref": "master",
  "sha": "ff9425ae19d607662e1e8adb6732dd0509aacb9f",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

The TROPO field (INIT A) doesn't accept values it should.

### Expected behavior

On Honeywell systems, whenever you enter any value from 0 - 60000 on TROPO field (INIT A), it will accept as is.

600 = 600ft.

### Steps to reproduce

Many values aren't accepted displaying a "NOT ALLOWED" on the scratchpad.

### References (optional)

tracerZ posted a quote at Discord FMS section stating the following:

"Any tropopause altitude up to 60,000 ft is able to be entered. The tropopause altitude cannot be entered as a flight level. Feet must be entered (i.e., do not enter 380 for FL380, the FMS interprets as 380 ft)"

### Additional info (optional)

_No response_

### Discord Username (optional)

Illuminati

### PR DESCRIPTION
**Pull request by MisterChocker**
Fixes #5032

## Summary of Changes

- Fixed tropo field input handling as per reference

## References

See linked issue

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## Testing instructions

Manipulate tropo field/value on init-a
_allowed format is NNNN or NNNNN_

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

File: flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js [hunk 1]
```diff
@@ -1301,22 +1301,27 @@ class FMCMainDisplay extends BaseAirliners {
...
+                return true;
+            } else {
+                this.addNewMessage(NXSystemMessages.notAllowed);
+                return false;
             }
         }
-        this.addNewMessage(NXSystemMessages.notAllowed);
+
+        const value = parseInt(tropo);
+        if (isFinite(value) && value >= 0 && value <= 60000) {
```
Comment (beheh) [inline flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js:1319]: Dropping the RegExp is not good enough, as this now incorrectly allows the user to enter `5.0`, which should be a format error instead.

**Review by beheh — CHANGES_REQUESTED** [review]

File: flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js (hunk 1 above)
Comment (MisterChocker) [reply flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js:1319]: you are right, maybe we should create general format filters so we don't have to "write" them for every entry check.

I'll add the regex part again to check for the format.

Comment (beheh) [reply flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js:1323]: Yep, we should if we could! I'm hoping this will eventually be abstracted away by React/the MCDU framework where there is presets for integers etc. that just handle this sensibly by default.

**Review by beheh — APPROVED** [review]

File: flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js [hunk 2]
```diff
@@ -1301,22 +1301,31 @@ class FMCMainDisplay extends BaseAirliners {
...
+            if (this.tropo) {
+                this.tropo = "";
+                return true;
             }
+            this.addNewMessage(NXSystemMessages.notAllowed);
+            return false;
         }
-        this.addNewMessage(NXSystemMessages.notAllowed);
+
+        if (!tropo.match(/^(?=(\D*\d){4,5}\D*$)/g)) {
```
Comment (beheh) [inline flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js:1317]: So, hm, this actually enforces 4 or 5 chars, which matches the reference:

image

That seems to contradict the motivation for this PR?

Comment (MisterChocker) [reply flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js:1317]: hmm, actually no, this is also what this pr does.

Right now the pr allows to clear a defined tropo and define the tropo with an entry inside 0-60000.
The entry will then be rounded to the nearest 10.
And the entry needs to be 4 or 5 digits long.

Comment (beheh) [reply flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js:1317]: Well, but doesn't the issue state

> "Any tropopause altitude up to 60,000 ft is able to be entered. The tropopause altitude cannot be entered as a flight level. Feet must be entered (i.e., do not enter 380 for FL380, the FMS interprets as 380 ft)"

...which doesn't really make sense if 380 is an invalid value.

Comment (MisterChocker) [reply flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js:1317]: True, I assume Honeywell did that to prevent these issues where the pilot thought he entered a flight level but in reality he entered an altitude.

Anyways this is what the manual says...

Comment (tracernz) [reply flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js:1317]: The Honeywell documentation contradicts itself in different sections, so that's fun.

**Comment by frankkopp** [comment]
Quality Assurance Tester Report

Discord: Cdr_Maverick#6475
Object of testing: #5044
Tier of Testing: 1
Date: 7.6.2021

Testing Process: (Detail is needed)
- c&d at gate / import simbrief
- edit tropo
  - 1 digit - 3 digits 
  - 4 - 5 digits
  - letters
  - negative 
  - <0, =0, >60.000
  - testing rounding with 36975, 36974, 36976

Negatives: None
Testing Results: Passed
Conclusions: LGTM

**Comment by TheSquirtingPantin** [comment]
Quality Assurance Tester

Discord: Remi#8871
Object of testing: #5044
Tier of Testing: 1
Date: 7/06/2021

Testing Process:
1) CD at KIAD
2) INIT A page. Checked TROPO value logic (negatives, decimal, range...)

Negatives: None. The documentation is not specifying anything regarding the use of decimal. When using decimal, the logic is still being respected.
Testing Results: Passed. 

Conclusions: LGTM. 
Media: N/A
