### PR TITLE
fix(mcdu/init): do not round CRZ FL to nearest 5

### LINKED ISSUE #1561: [BUG] Can't assign "strange" altitudes to FMC
**Mod Version**
Master

**Describe the bug**
China uses it's own "meters" version of RVSM which leads to strange flight levels, examples being FL341/FL351 etc, see the full list from VATPRC here: https://www.vatprc.net/wp-content/uploads/2019/11/China_RVSM-1024x593.jpg

When I attempt to add FL341 in the INIT page on the FMC, it inserts FL340

**To Reproduce**
1. Start at ZSPD
2. Go to the FMC and select INIT
3. Type ZSPD/ZBAA into FROM/TO
4. in CRZ FL type FL341
5. It'll then show FL340 in the FMC instead

**Expected behavior**
FL341 to appear as the CRZ FL

**Actual behavior**
FL340 appears as the CRZ FL

**References**
image

Was this working before/when did the issue start occurring?
Never worked

Is this a problem in the vanilla unmodded game?
Seems to be, unfortunately

### PR DESCRIPTION
**Pull request by Benjozork**
Fixes #1561

## Summary of Changes

- Do not round flight level to nearest 5

## Screenshots (if necessary)

image

## References

See #1561

Discord username (if different from GitHub): someperson#4953

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by Benjozork** [comment]
@Lucky38i you've worked on the MCDU a lot, can you check this ?

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js [hunk 1]
```diff
@@ -271,20 +287,24 @@ class FMCMainDisplay extends BaseAirliners {
...
+
     get cruiseFlightLevel() {
         return this._cruiseFlightLevel;
     }
+
     set cruiseFlightLevel(fl) {
-        this._cruiseFlightLevel = Math.round(fl / 5) * 5;
+        this._cruiseFlightLevel = fl;
         SimVar.SetSimVarValue("L:AIRLINER_CRUISE_ALTITUDE", "number", this._cruiseFlightLevel * 100);
     }
```
Comment (Benjozork) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js:298]: Relevant lines, sorry for the mess 😆

Comment (MisterChocker) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js:298]: no round on decimals?

Comment (Lucky38i) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js:298]: you need a conditional check to ensure the pilot hasn't entered any decimals so on the proceeding `setCruiseFlightLevelAndTemperature()` put a conditon like `if (fl === Math.round(fl))` then if true then assign the cruise level otherwise print the error message

Comment (Benjozork) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js:298]: > you need a conditional check to ensure the pilot hasn't entered any decimals so on the proceeding setCruiseFlightLevelAndTemperature() put a conditon like if (fl === Math.round(fl)) then if true then assign the cruise level otherwise print the error message

I did not change anything other than the `round` to 5, error message is unrelated to this PR. I can re-add the `round` without rounding to 5 though.

Comment (Lucky38i) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js:298]: yeah I'd add back the round then

**Comment by Lucky38i** [comment]
What about the linting corrections?

**Comment by Benjozork** [comment]
It was agreed upon to reformat files as we touch them.

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js [hunk 2]
```diff
@@ -271,20 +287,24 @@ class FMCMainDisplay extends BaseAirliners {
...
         SimVar.SetSimVarValue("L:AIRLINER_MCDU_CURRENT_FPLN_WAYPOINT", "number", this.currentFlightPlanWaypointIndex);
     }
+
     get cruiseFlightLevel() {
         return this._cruiseFlightLevel;
     }
+
     set cruiseFlightLevel(fl) {
-        this._cruiseFlightLevel = Math.round(fl / 5) * 5;
+        this._cruiseFlightLevel = Math.round(fl);
```
Comment (davidwalschots) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js:296]: **question**: I can understand why rounding is needed when doing division. However, if `fl` is always an integer rounding is no longer necessary. Did you check whether or not it is?

Comment (Benjozork) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js:296]: Decimal numbers can be entered and even if the entry appears as an integer after the fact, it seems to be internally stored as a decimal value still, and only formatted as an integer. This ensures the stored value is an integer.

**Comment by St54Kevin** [comment]
Tested. Went as expected. Could put in every FL i want. Temp also changes approriately. LGTM

**Comment by starvingjavi** [comment]
Name: Javi#2557
Date of testing: Current date 31/10/2020
Version of the sim: 1.10.8
PR Tested: #000
Object of test: altitude does not round to nearest 5

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1.  Start C&D
2.  Try to set up a flight plan
3.  Enter various altitudes and FL and in altitude form


Flight notes

Startup: Normal

Taxi/Takeoff : N/A

Cruise: N/A

Descent/Landing : N/A

Shutdown: N/A

Issues (If Any): 
Overall Rating: Good
Conclusions of the testing: Works as intended according to PR description

**Comment by ImenesFBW** [comment]
Name: Imenes#8739
Date of testing: 31/10/2020
Version of the sim: 1.10.8.0
PR Tested: #1565
Object of test: Testing if the CRZ FL no longer rounds up to nearest 5

Testing technique: Try-out (multiple tests)
Steps you've made to test the Pull Request:

1. Started cold and entered the FL in the MCDU page (both XXX and XXXXX format)
2. Started in the air and entered the FL in the MCDU page  (both XXX and XXXXX format)


Flight notes

Startup: Working as documented

Taxi/Takeoff : N/A

Cruise: Working as documented

Descent/Landing: N/A

Shutdown: N/A

Overall Rating: Good

Conclusions of the testing: The CRZ FL now doesn't get rounded to the closest 5 and works correctly, LGTM! Thank you!
