### PR TITLE
fix(hyd): autobrake key events handling for rotating knob type inputs

### LINKED ISSUE #5272: TCA autobrake keybind not working
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-05T11:26:37+00:00",
  "ref": "master",
  "sha": "fc3d05f309dc4d1e366701402e9ee76ba6e36f8f",
  "actor": "2hwk",
  "event_name": "manual"
}
```

### Describe the bug

After https://github.com/flybywiresim/a32nx/pull/4970 the keybindings of my TCA throttle do not work anymore... When selecting LOW of MEDIUM the autobrake illuminate for a second and then go out again. Autobrake max does not work at all.

### Expected behavior

I would expect the key bindings of my TCA throttle to work for LOW MED and MAX.

### Steps to reproduce

1. Spawn on the runway
2. Test autobrake functionality using the TCA throttle
3. Compare this to the default A320 behaviour.

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### PR DESCRIPTION
**Pull request by crocket63**
Fixes #5272

## Summary of Changes

When a key input is continuously pressed, we receive from FS2020 a first press then no press then another continuous press.
This is an issue for autobrake if using controllers such as TCA quadrant that only gives continuous keypress commands.

This PR adds a debounce mechanism in low level event handling to only allow a new event after a period of time (500ms). This is actually masking to the system implementation the wrong TRUE/FALSE/TRUE transition received from FS2020.

Drawback of this is that any autobrake input will be unresponsive if pressed up to 500ms after a first press.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

-Normal cockpit push buttons and LO MED HI key events are working as before.
-Autobrake functions can be selected using a knob selector type input that is continuously sending key pressed events
-Selection through rotating knob should be robust to system load (low fps). This will check if 500ms delay is not too agressive
-Disarm event from TCA quadrant is working

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

File: src/systems/a320_systems_wasm/src/lib.rs [hunk 1]
```diff
@@ -204,13 +238,13 @@ impl SimulatorAspect for Autobrakes {
         }
     }
 
-    fn pre_tick(&mut self, delta: Duration) {
+    fn pre_tick(&mut self, _delta: Duration) {
```
Comment (davidwalschots) [inline src/systems/a320_systems_wasm/src/lib.rs:241]: When unused, prefer `_` over `_delta`, unless on the default fn implementation on a trait.
```suggestion
    fn pre_tick(&mut self, _: Duration) {
```

File: src/systems/a320_systems_wasm/src/lib.rs [hunk 2]
```diff
@@ -204,13 +238,13 @@ impl SimulatorAspect for Autobrakes {
...
         self.synchronise_with_sim();
     }
 
     fn post_tick(
         &mut self,
-        sim_connect: &mut Pin<&mut SimConnect>,
+        _sim_connect: &mut Pin<&mut SimConnect>,
```
Comment (davidwalschots) [inline src/systems/a320_systems_wasm/src/lib.rs:247]: As above.

```suggestion
        _: &mut Pin<&mut SimConnect>,
```

File: src/systems/a320_systems_wasm/src/lib.rs [hunk 3]
```diff
@@ -157,9 +172,16 @@ impl Autobrakes {
...
-        self.low_mode_requested = false;
+        if self.last_button_press.elapsed() > Self::DEFAULT_REARMING_DURATION {
+            self.max_mode_requested = false;
+            self.med_mode_requested = false;
+            self.low_mode_requested = false;
+            self.disarm_requested = false;
+        }
+    }
+
+    fn key_event_is_received(&mut self) {
```
Comment (davidwalschots) [inline src/systems/a320_systems_wasm/src/lib.rs:183]: **thought**: `key_event_is_received` sounds like it will return a boolean.

```suggestion
    fn on_receive_key_event(&mut self) {
```

**Review by davidwalschots — APPROVED** [review]

**Comment by ErikNL80** [comment]
I really appreciate your efforts guys!!!

**Comment by tracernz** [comment]
> I really appreciate your efforts guys!!!

Does it work for you? Worked perfectly for me with the latest commits here and default MSFS bindings for the TCA.

**Comment by ErikNL80** [comment]
How can I download the file to test?

**Comment by 2hwk** [comment]
> How can I download the file to test?

https://github.com/flybywiresim/a32nx/suites/3198021446/artifacts/73888258

**Comment by ErikNL80** [comment]
Just did some extensive testing and performed a flight from EGKK to LOWS. I mad autobrake keybindings on the TCA Sidestick, and used the ones from the throttle:

1. Take-off config [OK] Was able to set the autobrakes with the throttle knob. (DISARM=OFF, BTV=not used, LO=LO, 2/3=MED, HI=MAX). Only note when you set the autobrakes via the knob, you can not overwrite the values using the mouse or other keybindings. The other way round is possible. No issue at all, maybe worth to put it in a ReadMe file

2. After take-off [OK] Autobrakes MAX is automatically switched off, have to put the knob to disarm manually.

3. Approach [OK] I am able to set autobrakes using the knob, same as with take-off config.

4. After landing {Will follow after I have landed}

**Comment by nyhmbo** [comment]
Non QA Associated Testing

Object of testing: #5290
Tier of Testing: 1
Date: 10/07/2021

Testing Process: load in C/D, setup plane
test different autobrake settings including disarm on ground using the TCA rotary knob and pushbuttons in the cockpit and check for performance impact
takeoff, test autobrake settings in the air using the TCA rotary knob and pushbuttons
landing, check for decel activation and disarm even with the knob still in armed position
Negatives: none
Testing Results: Passed

Conclusions: Works as described, no performance impact noticeable during autobrake selection

**Comment by flyingpaul1980** [comment]
It seems to be fixed, thanks to all :)
