### PR TITLE
[FIX] LDG/TO Memo

### LINKED ISSUE #687: [BUG] T.O. ECAM Memo comes back on after landing and vacating runway
**Describe the bug**

After landing, vacating the runway and cleaning up the aircraft the T.O. Ecam memo comes back on

**To Reproduce**

1. land fully configured at any airport in the world
2. after vacating the runway clean up the aircraft
3. notice how the t.o. ecam memo returns to the upper ecam

**Expected behavior**

t.o. ecam memo shouldn't come back after you initially take off at your departure airport

**Actual behavior**

t.o. ecam memo comes back on after vacating and cleaning up the aircraft after you've landed

**References**

https://imgur.com/F47ZydG

**Additional context**

Discord username:

### PR DESCRIPTION
**Pull request by MMontalto**
Fixes #687 #942 #1067 #1194

## Summary of Changes
- T.O memo in ECAM visible 2min after Engines Start, once taken off it will not reappear until engines are turned on again
- LDG memo change conditions
- Check on go around, when engines pass the Climb mode it hides the LND memo

## Screenshots (if necessary)
image

## References

image
image

## Additional context

Discord username (if different from GitHub): PiCcy

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js [hunk 1]
```diff
@@ -1172,24 +1175,32 @@ var A320_Neo_UpperECAM;
...
+                    this.showTakeoffMemo = false;
+                }
+                this.showTOMemoDisabled = eng2Running;
             }
 
             //Show landing memo at 2000ft
             //Hides after slowing down to 80kts
-            if (SimVar.GetSimVarValue("RADIO HEIGHT", "Feet") < 2000 && SimVar.GetSimVarValue("L:AIRLINER_FLIGHT_PHASE", "number") == 6 && SimVar.GetSimVarValue("AIRSPEED INDICATED", "knots") > 80 && !this.leftEcamMessagePanel.hasActiveFailures) {
+            const inGoAround = (numberPhase == 6 || numberPhase == 7) ? (Simplane.getEngineThrottleMode(0) > Simplane.getEngineThrottleMode(1)) ? Simplane.getEngineThrottleMode(0) : Simplane.getEngineThrottleMode(1) >= ThrottleMode.CLIMB : false;
+            if ((numberPhase >= 6 || numberPhase <= 7) && !inGoAround && SimVar.GetSimVarValue("RADIO HEIGHT", "Feet") < 2000 && !this.leftEcamMessagePanel.hasActiveFailures) {
```
Comment (beheh) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js:1200]: `(numberPhase >= 6 || numberPhase <= 7)`

This part will always evaluate to true.

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js [hunk 2]
```diff
@@ -83,6 +83,9 @@ var A320_Neo_UpperECAM;
         get templateID() {
             return "UpperECAMTemplate";
         }
+        static refresh() {
+            console.log("REFRESH");
```
Comment (beheh) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js]: This looks like forgotten debug logging.

Comment (MMontalto) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js]: Pushed - Remove refresh function

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js (hunk 1 above)
Comment (MMontalto) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js:1200]: yeah is (== || ==) ... I change immediately

**Comment by camilo625** [comment]
Name: Camilo625 #5575
Date of testing: Current date 14/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1322 

Testing technique: Short flight
Steps you've made to test the Pull Request:
1. Spawn C&D
2. Setup the plane
3. Takeoff
4. Short pattern
5. Land

Overall Rating: Good
Conclusions of the testing: Works as described, no memo appears after landing

**Comment by Benjozork** [comment]
Hello,

Seems like your reference comes from an EIS1 manual.

Please find references for EIS2.

**Comment by Benjozork** [comment]
I found one in ESLD:

image

Note that you won't be able to implement all logic here until the FWC is modeled.

Don't hesitate to contact us if you have any difficulty reading those schemas, they are quite intricate.

**Comment by jcalor** [comment]
Name: Jorge#6816
Date: 14/10/2020
Sim version: Latest - 1.9.5.0
PR Tested: #1322

Testing technique:

1. Spawned on RWY

2. Power up and setup MCDU

3. Takeoff

4. Did ILS

5. Land

6. Vacated RWY

Overall rating: Good
Conclusions of the testing: All looks good to me. After landing, no memo appears. Great work, keep going!

**Comment by starvingjavi** [comment]
I tested it before it was noted that it came from another manual. I have to point out I didn't get any LDG memo

**Comment by Benjozork** [comment]
@tyler58546 can you take a look at this ?

**Review by tyler58546 — CHANGES_REQUESTED** [review]
Nice work, just a few things that need to be fixed.

**Comment by MMontalto** [comment]
Thanks tyler changed as you suggested! :)

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js [hunk 3]
```diff
@@ -1154,6 +1155,12 @@ var A320_Neo_UpperECAM;
             this.isInitialised = true;
         }
         update(_deltaTime) {
+
```
Comment (Benjozork) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js:1158]:
```suggestion
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js [hunk 4]
```diff
@@ -1329,10 +1310,71 @@ var A320_Neo_UpperECAM;
...
+                }
+
+                this.showTOMemoDisabled = engsStarted || toConfig;
+            }
+
+            if (this.takeoffMemo != null) {
+                this.takeoffMemo.divMain.style.display = this.showTakeoffMemo ? "block" : "none";
+            }
+        }
+        updateLDGMemo(numberPhase, highestThrottleDetent, _deltaTime) {
```
Comment (Benjozork) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js:1348]:
```suggestion
        }
        
        updateLDGMemo(numberPhase, highestThrottleDetent, _deltaTime) {
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AltimeterIndicator.js [hunk 5]
```diff
@@ -441,6 +441,8 @@ class Jet_PFD_AltimeterIndicator extends HTMLElement {
         }
 
         const groundReference = indicatedAltitude - Simplane.getAltitudeAboveGround();
+        SimVar.SetSimVarValue("L:A32NX_ALTIMETER_GROUND_REFERENCE", "feet", groundReference);
```
Comment (Benjozork) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AltimeterIndicator.js:444]: Why are we setting this simvar if we could just use the same calculation instead of the simvar ?

Comment (MMontalto) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AltimeterIndicator.js:444]: How much does it impact on performance?
I thought that setting it from where it was calculated and then picking it up where it was needed would not give problems of any kind

Comment (Benjozork) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AltimeterIndicator.js:444]: Setting a simvar inside an instrument view is bad for separation of concerns.

If you wanna create this simvar, you should create an `A32NX_GroundReference.js` module in `A32NX_Core`.

Comment (MMontalto) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AltimeterIndicator.js]: Interesting ... I moved the ground reference logic into its specific module it can be useful to centralize this part. Can you check if it's correct?
Another question, is it right that the core part scripts are included inside "A320_Neo / CDU / A320_Neo_CDU.html" ?? Sorry for my bad English, it's my big problem :(

**Comment by Benjozork** [comment]
I'd say the smoothing should be in the PFD, but we can change this later. LGTM.

**Comment by MMontalto** [comment]
Oh ... Right ..
I check out PFD with the master version.
Better to keep the logic as it is

File: .github/CHANGELOG.md [hunk 6]
```diff
@@ -71,4 +72,3 @@
 1. [ND] Add DME distances, VOR/ADF needles and functioning ADF2 - @blitzcaster (bltzcstr)
 1. [OVHD] Fixed Battery Indicator Colour - @nathaninnes (Nathan Innes)
 1. [MISC] Removed Fuel Patch from MSFS Update 1.8.3 - @nathaninnes (Nathan Innes)
-
```
Comment (beheh) [inline .github/CHANGELOG.md:74]: This commit changes the end of the file, probably inadvertantly. Editor setting for trailing newline?

File: A32NX/html_ui/Pages/A32NX_Core/A32NX_GroundReference.js [hunk 7]
```diff
@@ -0,0 +1,12 @@
+class A32NX_GroundReference {
+    constructor() {
+        console.log('A32NX_GroundReference constructed');
+    }
+    init() {
+        console.log('A32NX_GroundReference init');
+    }
```
Comment (beheh) [inline A32NX/html_ui/Pages/A32NX_Core/A32NX_GroundReference.js:7]: Are the console log statements supposed to end up in master?

File: A32NX/html_ui/Pages/A32NX_Core/A32NX_GroundReference.js [hunk 8]
```diff
@@ -0,0 +1,12 @@
...
+    update(_dTime, _core) {
+        const groundReference = Simplane.getAltitude() - Simplane.getAltitudeAboveGround();
+        SimVar.SetSimVarValue("L:A32NX_ALTIMETER_GROUND_REFERENCE", "feet", groundReference);
+    }
+}
```
Comment (beheh) [inline A32NX/html_ui/Pages/A32NX_Core/A32NX_GroundReference.js:12]: This file does not have a trailing newline, similar to what you did to the CHANGELOG above. Maybe check your editor settings? (although I'm not a contributor, so I'm not aware of a style guide).

File: A32NX/html_ui/Pages/A32NX_Core/A32NX_GroundReference.js (hunk 7 above)
Comment (MMontalto) [reply A32NX/html_ui/Pages/A32NX_Core/A32NX_GroundReference.js:7]: I followed the scheme of the other modules and logs are present.
PR has already been revised and ready to test, I think they must be present at the moment in that part...

File: A32NX/html_ui/Pages/A32NX_Core/A32NX_GroundReference.js (hunk 8 above)
Comment (MMontalto) [reply A32NX/html_ui/Pages/A32NX_Core/A32NX_GroundReference.js:12]: Same as the other modules

File: .github/CHANGELOG.md (hunk 6 above)
Comment (MMontalto) [reply .github/CHANGELOG.md:74]: Removed although I don't think it was a problem ... It probably depends on my editor, yes ...

**Comment by Carter633** [comment]
Name: British Avgeek YT -- Carter633 #1436
Date of testing: Current date 12/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1322

Testing technique: Full flight from Cold and Dark
Steps you've made to test the Pull Request:

1. Spawned on stand Cold and Dark for full flight
2. Monitored TO Memo - works as described
3. Descent phase - Landing Memo came on at appropriate time and worked as described.

Overall Rating: Good
Conclusions of the testing: No issues found and worked as described above.

File: .github/CHANGELOG.md (hunk 6 above)
Comment (beheh) [reply .github/CHANGELOG.md:74]: Yeah, it's probably not an issue, it's just that in a repository as large as this if people casually commit these changes in completely unrelated PRs it may lead to unnecessary merge conflicts in future.

Comment (MMontalto) [reply .github/CHANGELOG.md:74]: Yes, more than fair!

**Comment by ImenesFBW** [comment]
Name: Imenes#8739
Date of testing: 18/10/2020
Version of the sim: 1950
PR Tested: #1322

Testing technique: Try-out
Steps made to test the Pull Request:

1. Loaded the plane in C&D
2. Flew an ILS missed approach
3. Full stop landing



Overall Rating: Good
Conclusions of the testing: Working as documented! Thank you for your work!
