### PR TITLE
Close engine start valves at N2 50% #1196

### LINKED ISSUE #1196: [BUG] Engine Start Valves do not close, NO AVAIL indication when stabilized, ENGINE ECAM PAGE does not change
**Mod Version**

master

**Describe the bug**

After engine is stabilized the engine start valve is not closed.
At about 50% N2 the engine start valve stays does not close and stays open.
Also the engines dont show AVAIL when stabilized. However the Indication "A" and "B" at the engine start valves disappear when stabilized.

**To Reproduce**

1. Shut Engines and APU running with APU Bleed open
2. Engine Mode Selector to Ignition
3. Set Engine Master 2 to ON

**Expected behavior**

(FOR A320 CFM56 Engines but I assume engine start procedure is similar for NEO Engines LEAP and PW1100G)
(Aircraft is ready for Engine Start with APU AVAIL and APU BLEED OPEN)
Set Engine Mode Selector set to IGNITION.
_Now PSI on Engine Start Valves increase to about 40 PSI_
Then Set Engine Master 2 to ON
_Now Engine 2 Start Valve is OPEN and PSI on Engine Start Valves decrease to about 32 PSI_
At about 50% N2 the start valve will close.
_Now PSI on Engine Start Valves rise back to 40 PSI._
When the engine is stabilized, the text "AVAIL" can be seen for 10 seconds above its N1 % number readout. (as seen in the picture)
As soon as BOTH engines are stabilized the Engine Start Valve indication disappears from the ENGINE PAGE as seen in the second picture.
image

**Actual behavior**
Engine 2 start valve stays open.
(Both Valves will stay open)

AS soon as BOTH engines are stabilized the IGN disapperes from the ENGINE PAGE however the Engine Start Valve indication still is visible.
imageimage

**References**

good reference video https://youtu.be/O1AQHlZLN30?t=327
image

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username DerL30N#3751

### PR DESCRIPTION
**Pull request by RichardPilbery**
Fixes #1196 

## Summary of Changes

Simple fix, check for n2Percent value and then call function once n2Percent exceeds 50: setEngineBleedValveState(false, false). Code appears twice, once for each engine. 

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Engine.js [hunk 1]
```diff
@@ -74,6 +78,11 @@ var A320_Neo_LowerECAM_Engine;
                     ignRightTargetState = A320_Neo_LowerECAM_Engine.Definitions.IGN_STATE.A;
                 }
             }
+            if (n2Percent > 50) {
+                // Close right valve
+                //console.log("Right engine N2 >50%");
```
Comment (NathanInnes) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Engine.js:83]: Remove console log comment
```suggestion
```

**Comment by NathanInnes** [comment]
Can you include reference?

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Engine.js [hunk 2]
```diff
@@ -63,6 +63,10 @@ var A320_Neo_LowerECAM_Engine;
                     ignLeftTargetState = A320_Neo_LowerECAM_Engine.Definitions.IGN_STATE.A;
                 }
             }
+            if (n2Percent > 50) {
+                // Close left valve
+                this.engineLeft.setEngineBleedValveState(false, false);
+            }
```
Comment (NathanInnes) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Engine.js:69]: This can all be made into one arg, no need for 2 seperate n2Percent.
```suggestion
            if (n2Percent > 50) {
                // Close left & right valve
                this.engineLeft.setEngineBleedValveState(false, false);
                this.engineRight.setEngineBleedValveState(false, false);
            }
```

Comment (NathanInnes) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Engine.js:69]: No need for seperate args, just put it all into 1 if statement.
```suggestion
            if (n2Percent > 50) {
                // Close left & right valve
                this.engineLeft.setEngineBleedValveState(false, false);
                this.engineRight.setEngineBleedValveState(false, false);
            }
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Engine.js [hunk 3]
```diff
@@ -74,6 +78,11 @@ var A320_Neo_LowerECAM_Engine;
                     ignRightTargetState = A320_Neo_LowerECAM_Engine.Definitions.IGN_STATE.A;
                 }
             }
+            if (n2Percent > 50) {
+                // Close right valve
+                //console.log("Right engine N2 >50%");
+                this.engineRight.setEngineBleedValveState(false, false);
+            }
```
Comment (NathanInnes) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Engine.js:85]:
```suggestion
```

**Review by NathanInnes — CHANGES_REQUESTED** [review]

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Engine.js (hunk 2 above)
Comment (RichardPilbery) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Engine.js:69]: I don't think you can do this since n2Percent refers to the left engine at line 58, but is then subsequently redefined as the value for the right engine on line 73.

Comment (NathanInnes) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Engine.js:69]: Ahh yes.. In that case I will suggest something else.

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Engine.js (hunk 1 above)
Comment (NathanInnes) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Engine.js:83]: Remove console log comment.
```suggestion
```

**Comment by RichardPilbery** [comment]
Re: references. I have to admit that since the issue was open and had been labelled, I assumed that someone had considered that the request was valid. Is there an A320neo technical manual or similar that can be checked? Certainly, it was something that A320SimPilot (who is an A320 pilot IRL) commented on: https://www.youtube.com/channel/UCAILTiWNai7Y2zsO8ECFxcA

**Review by Benjozork — CHANGES_REQUESTED** [review]

**Review by Benjozork — APPROVED** [review]

**Comment by NathanInnes** [comment]
Tested and when turning off engines, engine bleed valve closes below 50% N2. Working as stated.

**Comment by lousybyte** [comment]
Igniters turn off at 55% atm, maybe lineup the valves to that?

**Comment by MisterChocker** [comment]
maybe little advice because I have seen `n2Percent > 50`, wouln't it be smarter to change it to `n2Percent >= 50`?

**Comment by NathanInnes** [comment]
image
posting this as reference

**Comment by MisterChocker** [comment]
ah okay then, I was replying cause they said it does not close fast enough. Bit it clearly states N2 > 50%.

**Comment by lousybyte** [comment]
Seems like IGN percentages need to be adjusted based on that reference.
