### PR TITLE
Optimize performance by sequencing updates (+ ~50% fps)

### LINKED ISSUE #1341: [BUG] Performance degradation with mod since MSFS 1.9.5.0
**Mod Version**
master

**Describe the bug**
I am getting low performance (5-15 fps less) compared to the vanilla; this didn’t happen some days ago.

**To Reproduce**
Compare fps with mod and without mod

1.
2.
3.

**Expected behavior**
The mod should not affect performance so much.

**Actual behavior**
 Mod affect performance (5-15 fps less compared to the vanilla)

**References**

**Additional context**

Was this working before/when did the issue start occurring?
I noticed it today for the first time.

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

### PR DESCRIPTION
**Pull request by XSJoJo**
Fixes #1341

## Summary of Changes
Instead of updating everything in the same frame, this introduces
UpdateThrottler that aims to throttle updates depending on the context.

Example: While the Speed indicator needs to very snappy, other things
like information about the electric system can update at a much reduced
rate.

## References
n/a

## Additional context
This is a little bit like the in-game option to change the glass cockpit
refresh rate, however:
- With this patch, we do it individually, such that we have different
refresh rates as mentioned above.
- Furthermore, this tries to space out updates from different elements
among different frames. With the in-game setting, everything updates in
one frame, but then nothing updates in the next frame. With this patch,
we try to space out updates for different instrument among all frames,
leading to a lot less spikey frame times. In other words, the refresh rate
setting does absolutely not improve 90-percentile frame times, while
there is a significant improvement with frame time evenness with this
patch. This leads to a much better experience in VR and VRR
(variable refresh rate (G-Sync or FreeSync)) capable monitors.

It's recommended to set in-game glass cockpit refresh rate to high for
this to work best, but it also works for lower refresh rates.

On my system (9900k, 2080 Ti), I'm getting about + 16fps against ToT and +7fps against ToT (medium refresh rate). Sensitive instruments are configured to run at 20fps, so it's about the same as medium glass cockpit refresh rate setting.

In particular, compare ToT (medium refresh rate) with ToT+Patch and observe how the frame times (the bars at the top) are a lot less spikey with my patch, leading to an overall smoother experience.

ToT (Tip of tree):
Screenshot 2021-01-10 200900

ToT(medium refresh rate):
Screenshot 2021-01-10 200938

ToT + Patch:
Screenshot 2021-01-10 200434

Slow motion videos:
- ToT: https://photos.google.com/photo/AF1QipP9p-YClwT5FgDhENpNQtO19I12nVopIEunPy6g
- ToT (medium refresh rate): https://photos.google.com/photo/AF1QipNhjb5GJwPn6FvN41ZR40ggg4l70UfvTyQlAn2N
- ToT+ This patch: https://photos.google.com/photo/AF1QipNES_bP0fRm8Pmtzltg1UqRLK7LRNMQnRFLes2w

Discord username (if different from GitHub): JoJo

## Testing instructions
Start any flight and enable in-game FPS monitor. Inspect "CoherentGTDraw" times using a slow motion video captured from your phone to see the reduced draw times.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Comment by davidwalschots** [comment]
It's important to note that gauges contain code which depends on the `deltaTime`. For example `A320_Neo_LowerECAM_APU.js` contains this line:

```javascript
this.apuInactiveTimer -= _deltaTime / 1000;
```

If this code would only run once every 20 frames, the `apuInactiveTimer` would decrease at a 20 times slower rate.

Therefore, the `UpdateThrottler` needs to provide the deltaTime of the current frame plus previous skipped frames, such that the calculations can be performed successfully. Thus if it runs every 20 frames, and each frame is 10ms, then `UpdateThrottler` must provide `200`.

Even then care needs to be taken, as certain formulae in the code might not respond well to sudden bigger time changes, e.g. a polynomial regression which gives wrong results if time between frames becomes bigger... Things like that.

An example (pseudo) solution would be:

```javascript
    canUpdate(deltaTime) {
        if (shouldRun) {
           return //sum of all skipped frames delta time + current frame delta time;
        } else {
          return 0;
        }
    }
```

**Comment by MisterChocker** [comment]
I hate to say that but this would brake a lot of stuff.
And I don't really like this approach.
Since we are already recoding almost everything this becomes obsolete.

**Comment by XSJoJo** [comment]
> It's important to note that gauges contain code which depends on the `deltaTime`. For example `A320_Neo_LowerECAM_APU.js` contains this line:
> 
> ```js
> this.apuInactiveTimer -= _deltaTime / 1000;
> ```
> 
> If this code would only run once every 20 frames, the `apuInactiveTimer` would decrease at a 20 times slower rate.
> 
> Therefore, the `UpdateThrottler` needs to provide the deltaTime of the current frame plus previous skipped frames, such that the calculations can be performed successfully. Thus if it runs every 20 frames, and each frame is 10ms, then `UpdateThrottler` must provide `200`.

Ah yes you're right. I also noticed that some places have a "manual" frame counter at the moment, so I'll likely need to adjust this as well.

> 
> Even then care needs to be taken, as certain formulae in the code might not respond well to sudden bigger time changes, e.g. a polynomial regression which gives wrong results if time between frames becomes bigger... Things like that.

Yes that's true, although not very different if the sim runs at a lower FPS. Do you know which places a super low frame rate would have a negative impact already? I can make sure to test these functions manually, and ensure that the rate we send isn't too low.

> 
> An example (pseudo) solution would be:
> 
> ```js
>     canUpdate(deltaTime) {
>         if (shouldRun) {
>            return //sum of all skipped frames delta time + current frame delta time;
>         } else {
>           return 0;
>         }
>     }
> ```

Right, that works. I guess we should return -1 in order not to collide when the deltaTime is actually 0ms, but I guess that doesn't happen in practice.

**Comment by davidwalschots** [comment]
> Yes that's true, although not very different if the sim runs at a lower FPS.

Indeed.

> Do you know which places a super low frame rate would have a negative impact already?

No. I've not done a lot of work on the JS side of the FBW project. The reason I mention it is because in the Rust aircraft systems code I'm working on there are such sensitive cases.

**Comment by wpine215** [comment]
> Yes that's true, although not very different if the sim runs at a lower FPS. Do you know which places a super low frame rate would have a negative impact already? I can make sure to test these functions manually, and ensure that the rate we send isn't too low.

The ADIRS ON BAT light and align process use a linear countdown timer, but low frame rate shouldn't be an issue there. The places I would take a close look out would be the APU ecam page (startup/shutdown), the COND & CRUISE ecam page (try changing cabin temp selector knobs), and WHEEL ecam page (brake temperature calculations, especially during/right after decel).

**Comment by XSJoJo** [comment]
> > Yes that's true, although not very different if the sim runs at a lower FPS. Do you know which places a super low frame rate would have a negative impact already? I can make sure to test these functions manually, and ensure that the rate we send isn't too low.
> 
> The ADIRS ON BAT light and align process use a linear countdown timer, but low frame rate shouldn't be an issue there. The places I would take a close look out would be the APU ecam page (startup/shutdown), the COND & CRUISE ecam page (try changing cabin temp selector knobs), and WHEEL ecam page (brake temperature calculations, especially during/right after decel).

Thanks, I did some smoke testing on these and they seem to work fine still.

**Comment by XSJoJo** [comment]
Ok this is ready for review.

There are still some performance issues, but this is a good start:
- Once you enter a flight plan I get about a 5 FPS drop
- Occasional long frame time (> 20ms CoherentGTDraw) leading to a janky feeling with TrackIR. This is probably one of the things that only runs every 1-2 seconds but for really long. Needs more investigation.

**Comment by Benjozork** [comment]
> Once you enter a flight plan I get about a 5 FPS drop

This will need investigation, I assume a badly made/repetitive `forEach`

**Comment by ErickSharp** [comment]
Category: QA Tester
Name: Erick [Z-6]#6484
Date of testing: Current date 14/01/2021
Version of the sim: 1.12.13.0
PR Tested: #2976
Object of test: Update throttle sim performance boost

Testing technique: Installed PR through installer, tried twice, with each time the sim crashed. Re-installed the PR through the installer and tried to test again. 
Steps you've made to test the Pull Request:
1. Install PR through the installer
2. Get loaded into the main menu, go to world map and spawn in at a runway at KLAX.  
3.  PR Crashes sim and Discord crashes, as well as an apparent out of memory error on my web browser.
4. Re-launch the simulator, go to the world map and spawn in at a runway at KLAX. 
5. PR Crashes sim, this time returning an error window shown below. 
6. Re-install the PR through the installer. 
7. Re-launch the simulator, go to world map and spawn in at a runway at KLAX. 
8. PR crashes sim, this time returning no error and without crashing other programs. 
9. Re-launch simulator, go to world map and spawn in at a KLAX ramp at this time. 
10. PR crashes sim, no errors and no programs crashed. 
Screenshot 2021-01-14 011316
Flight notes (If required): All testing done with selecting KLAX ICAO 
Issues (If Any): PR does not allow for you to spawn in at a runway nor a gate. PR crashed the sim everytime I tried to spawn in. 
Overall Rating: Needs improvement 
Conclusions of the testing: The PR consistently crashed the sim, and therefore I was not able to test any prospective FPS/Performance improvements. Further testing and adaptations to the PR are still needed.

**Comment by Benjozork** [comment]
As additional context, I have not experienced crashes spawning on the runway at CYUL.

**Comment by FlightSimmer7700** [comment]
I loaded in at KLAX with similar specs and similar Sim Settings but with 32gb of ram instead of the 16gb that ErickSharp has and had no crashes

**Comment by XSJoJo** [comment]
Hmm I'll check whether this patch causes memory to go up or not.

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/A32NX_BaseAirliners.js [hunk 1]
```diff
@@ -188,7 +188,7 @@ var Airliners;
             }
         }
         onUpdate() {
-            const _deltaTime = this.getDeltaTime();
+            var _deltaTime = this.getDeltaTime();
```
Comment (beheh) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/A32NX_BaseAirliners.js:191]: No reason to change this one.

```suggestion
            const _deltaTime = this.getDeltaTime();
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/A32NX_BaseAirliners.js [hunk 2]
```diff
@@ -225,7 +225,7 @@ var Airliners;
...
```
Comment (beheh) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/A32NX_BaseAirliners.js:228]:
```suggestion
            const _deltaTime = this.getDeltaTime();
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js [hunk 3]
```diff
@@ -136,13 +136,17 @@ class A320_Neo_EICAS extends Airliners.BaseEICAS {
         SimVar.SetSimVarValue("LIGHT POTENTIOMETER:93", "FLOAT64", 0.1);
 
         this.ecamAllButtonPrevState = false;
+        this.updateThrottler = new UpdateThrottler(500);
     }
 
     onUpdate() {
-        const _deltaTime = this.getDeltaTime();
+        var _deltaTime = this.getDeltaTime();
```
Comment (beheh) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js:143]:
```suggestion
        let _deltaTime = this.getDeltaTime();
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js [hunk 4]
```diff
@@ -164,9 +167,16 @@ class A320_Neo_MFD_MainPage extends NavSystemPage {
             this.selfTestLastKnobValue = currentKnobValue;
             return;
         }
-        const _deltaTime = this.getDeltaTime();
+        var _deltaTime = this.getDeltaTime();
```
Comment (beheh) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js:170]:
```suggestion
        let _deltaTime = this.getDeltaTime();
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js [hunk 5]
```diff
@@ -106,7 +110,7 @@ class A320_Neo_PFD_MainPage extends NavSystemPage {
         this.electricity = document.querySelector('#Electricity');
     }
     onUpdate() {
-        const _deltaTime = this.getDeltaTime();
+        var _deltaTime = this.getDeltaTime();
```
Comment (beheh) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js:113]:
```suggestion
        const _deltaTime = this.getDeltaTime();
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js [hunk 6]
```diff
@@ -232,11 +242,16 @@ class A320_Neo_PFD_VSpeed extends NavSystemElement {
         const url = document.getElementsByTagName("a320-neo-pfd-element")[0].getAttribute("url");
         this.disp_index = parseInt(url.substring(url.length - 1));
         this.pot_index = this.disp_index == 1 ? 88 : 90;
+        this.updateThrottler = new UpdateThrottler(this.disp_index == 1 ? 50 : 100);
     }
     onEnter() {
     }
     onUpdate() {
-        const _deltaTime = this.getDeltaTime();
+        var _deltaTime = this.getDeltaTime();
```
Comment (beheh) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js:250]:
```suggestion
        const _deltaTime = this.getDeltaTime();
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js [hunk 7]
```diff
@@ -296,11 +316,17 @@ class A320_Neo_PFD_Altimeter extends NavSystemElement {
         const url = document.getElementsByTagName("a320-neo-pfd-element")[0].getAttribute("url");
         this.disp_index = parseInt(url.substring(url.length - 1));
         this.pot_index = this.disp_index == 1 ? 88 : 90;
+        this.updateThrottler = new UpdateThrottler(this.disp_index == 1 ? 25 : 100);
     }
     onEnter() {
     }
     onUpdate() {
-        const _deltaTime = this.getDeltaTime();
+        var _deltaTime = this.getDeltaTime();
```
Comment (beheh) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js:324]:
```suggestion
        const _deltaTime = this.getDeltaTime();
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js [hunk 8]
```diff
@@ -413,11 +449,16 @@ class A320_Neo_PFD_NavStatus extends NavSystemElement {
         const url = document.getElementsByTagName("a320-neo-pfd-element")[0].getAttribute("url");
         this.disp_index = parseInt(url.substring(url.length - 1));
         this.pot_index = this.disp_index == 1 ? 88 : 90;
+        this.updateThrottler = new UpdateThrottler(this.disp_index == 1 ? 200 : 500);
     }
     onEnter() {
     }
     onUpdate() {
-        const _deltaTime = this.getDeltaTime();
+        var _deltaTime = this.getDeltaTime();
```
Comment (beheh) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js:457]:
```suggestion
        const _deltaTime = this.getDeltaTime();
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js [hunk 9]
```diff
@@ -440,11 +481,16 @@ class A320_Neo_PFD_ILS extends NavSystemElement {
         const url = document.getElementsByTagName("a320-neo-pfd-element")[0].getAttribute("url");
         this.disp_index = parseInt(url.substring(url.length - 1));
         this.pot_index = this.disp_index == 1 ? 88 : 90;
+        this.updateThrottler = new UpdateThrottler(this.disp_index == 1 ? 150 : 300);
     }
     onEnter() {
     }
     onUpdate() {
-        const _deltaTime = this.getDeltaTime();
+        var _deltaTime = this.getDeltaTime();
```
Comment (beheh) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js:489]:
```suggestion
        const _deltaTime = this.getDeltaTime();
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js [hunk 10]
```diff
@@ -268,11 +283,16 @@ class A320_Neo_PFD_Airspeed extends NavSystemElement {
         const url = document.getElementsByTagName("a320-neo-pfd-element")[0].getAttribute("url");
         this.disp_index = parseInt(url.substring(url.length - 1));
         this.pot_index = this.disp_index == 1 ? 88 : 90;
+        this.updateThrottler = new UpdateThrottler(this.disp_index == 1 ? 50 : 100);
     }
     onEnter() {
     }
     onUpdate() {
-        const _deltaTime = this.getDeltaTime();
+        var _deltaTime = this.getDeltaTime();
```
Comment (beheh) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js:291]:
```suggestion
        const _deltaTime = this.getDeltaTime();
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js [hunk 11]
```diff
@@ -164,9 +167,16 @@ class A320_Neo_MFD_MainPage extends NavSystemPage {
...
         super.onUpdate(_deltaTime);
-        this.updateMap(_deltaTime);
+        var mapDeltaTime = this.mapUpdateThrottler.canUpdate(_deltaTime);
```
Comment (beheh) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js:172]:
```suggestion
        const mapDeltaTime = this.mapUpdateThrottler.canUpdate(_deltaTime);
```

File: A32NX/html_ui/JS/A32NX_Util.js [hunk 12]
```diff
@@ -45,3 +45,45 @@ A32NX_Util.createMachine = (machineDef) => {
...
+        var update = number > this.refreshNumber;
+        this.refreshNumber = number;
+        if (update) {
+            var accumulatedDelta = this.currentTime - this.lastUpdateTime;
+            this.lastUpdateTime = this.currentTime;
+            return accumulatedDelta;
+        } else {
+            return -1;
+        }
+    }
```
Comment (beheh) [inline A32NX/html_ui/JS/A32NX_Util.js:88]:
```suggestion
    canUpdate(deltaTime) {
        this.currentTime += deltaTime;
        const number = Math.floor((this.currentTime + this.refreshOffset) / this.intervalMs);
        const update = number > this.refreshNumber;
        this.refreshNumber = number;
        if (update) {
            const accumulatedDelta = this.currentTime - this.lastUpdateTime;
            this.lastUpdateTime = this.currentTime;
            return accumulatedDelta;
        } else {
            return -1;
        }
    }
```

**Review by beheh — CHANGES_REQUESTED** [review]
Please use `const` and `let` over `var`.

**Comment by XSJoJo** [comment]
> Please use `const` and `let` over `var`.

Thanks for the suggestions. PTAL

**Comment by ErickSharp** [comment]
In my PR review, I talked about how the sim always crashes at KLAX, which is usually taxing, anyways. I tried testing the PR at CYUL, and the PR did in fact stabilize the frames of the simulator, and even gave me 10 or so more frames. I have 16gb of DDR4 RAM, and most large airports like KLAX are very RAM hungry. Normally, spawning into the airport will result in low frames for a while until the frames stabilize, whereas with the PR the sim crashes.  I believe the issue here is that with the PR, the sim will go through all of the available RAM and won't "throttle" down so as to prevent a crash.

**Comment by St54Kevin** [comment]
Category: QA Tester
Name: St54Kevin#3583
Date of testing: 15/01/2021
Version of the sim: 1.12.13.0
PR Tested: #2976
Object of test: Performance improvements
Testing technique: Compare performance to current dev version
Ryzen 7 5800X
RTX2070Super
32GB RAM

Steps you've made to test the Pull Request:

1. Loaded up current dev version at KLAX
2. 3x30s Afterburner benchmark with two 360 degree camera turns
3. 17GB RAM usage (just MSFS (steam), discord, 1 chrome tab)
**Average framerate  :   34.3 FPS
Minimum framerate  :   29.4 FPS
Maximum framerate  :   37.5 FPS
1% low framerate   :   16.1 FPS
0.1% low framerate :   14.1 FPS**
image

4. Loaded PR via qa installer
5. Reload into same situation
6. 17GB RAM usage (same)
**Average framerate  :   48.4 FPS
Minimum framerate  :   44.4 FPS
Maximum framerate  :   52.7 FPS
1% low framerate   :   29.1 FPS
0.1% low framerate :   20.8 FPS**
image

Flight notes (If required): 
Display Refresh Rate HIGH 
KLAX 25R with auto route to KLAS
1200 local
Broken clouds

Issues (If Any): Both PFDs were in test mode with this PR
image

Overall Rating: Besides the PFD issue LGTM

Conclusions of the testing: **40%** improvement in average framerate and more importantly fluent 1% and 0.1% lows. Way smoother experience. But I dont know wether this is due to the not working PFDs

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js [hunk 13]
```diff
@@ -413,11 +449,16 @@ class A320_Neo_PFD_NavStatus extends NavSystemElement {
         const url = document.getElementsByTagName("a320-neo-pfd-element")[0].getAttribute("url");
         this.disp_index = parseInt(url.substring(url.length - 1));
         this.pot_index = this.disp_index == 1 ? 88 : 90;
+        this.updateThrottler = new UpdateThrottler(this.disp_index == 1 ? 200 : 500);
     }
     onEnter() {
     }
     onUpdate() {
         const _deltaTime = this.getDeltaTime();
```
Comment (beheh) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js:457]:
```suggestion
        let _deltaTime = this.getDeltaTime();
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js [hunk 14]
```diff
@@ -440,11 +481,16 @@ class A320_Neo_PFD_ILS extends NavSystemElement {
         const url = document.getElementsByTagName("a320-neo-pfd-element")[0].getAttribute("url");
         this.disp_index = parseInt(url.substring(url.length - 1));
         this.pot_index = this.disp_index == 1 ? 88 : 90;
+        this.updateThrottler = new UpdateThrottler(this.disp_index == 1 ? 150 : 300);
     }
     onEnter() {
     }
     onUpdate() {
         const _deltaTime = this.getDeltaTime();
```
Comment (beheh) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js:489]:
```suggestion
        let _deltaTime = this.getDeltaTime();
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js [hunk 15]
```diff
@@ -382,11 +413,16 @@ class A320_Neo_PFD_Compass extends NavSystemElement {
         const url = document.getElementsByTagName("a320-neo-pfd-element")[0].getAttribute("url");
         this.disp_index = parseInt(url.substring(url.length - 1));
         this.pot_index = this.disp_index == 1 ? 88 : 90;
+        this.updateThrottler = new UpdateThrottler(this.disp_index == 1 ? 60 : 200);
     }
     onEnter() {
     }
     onUpdate() {
-        const _deltaTime = this.getDeltaTime();
+        var _deltaTime = this.getDeltaTime();
```
Comment (beheh) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js:421]:
```suggestion
        let _deltaTime = this.getDeltaTime();
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js [hunk 16]
```diff
@@ -333,11 +359,16 @@ class A320_Neo_PFD_Attitude extends NavSystemElement {
         const url = document.getElementsByTagName("a320-neo-pfd-element")[0].getAttribute("url");
         this.disp_index = parseInt(url.substring(url.length - 1));
         this.pot_index = this.disp_index == 1 ? 88 : 90;
+        this.updateThrottler = new UpdateThrottler(this.disp_index == 1 ? 50 : 100);
     }
     onEnter() {
     }
     onUpdate() {
-        const _deltaTime = this.getDeltaTime();
+        var _deltaTime = this.getDeltaTime();
```
Comment (beheh) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js:367]:
```suggestion
        let _deltaTime = this.getDeltaTime();
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js [hunk 17]
```diff
@@ -296,11 +316,17 @@ class A320_Neo_PFD_Altimeter extends NavSystemElement {
         const url = document.getElementsByTagName("a320-neo-pfd-element")[0].getAttribute("url");
         this.disp_index = parseInt(url.substring(url.length - 1));
         this.pot_index = this.disp_index == 1 ? 88 : 90;
+        this.updateThrottler = new UpdateThrottler(this.disp_index == 1 ? 25 : 100);
     }
     onEnter() {
     }
     onUpdate() {
         const _deltaTime = this.getDeltaTime();
```
Comment (beheh) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js:324]:
```suggestion
        let _deltaTime = this.getDeltaTime();
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js [hunk 18]
```diff
@@ -268,11 +283,16 @@ class A320_Neo_PFD_Airspeed extends NavSystemElement {
         const url = document.getElementsByTagName("a320-neo-pfd-element")[0].getAttribute("url");
         this.disp_index = parseInt(url.substring(url.length - 1));
         this.pot_index = this.disp_index == 1 ? 88 : 90;
+        this.updateThrottler = new UpdateThrottler(this.disp_index == 1 ? 50 : 100);
     }
     onEnter() {
     }
     onUpdate() {
         const _deltaTime = this.getDeltaTime();
```
Comment (beheh) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js:291]:
```suggestion
        let _deltaTime = this.getDeltaTime();
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js [hunk 19]
```diff
@@ -232,11 +242,16 @@ class A320_Neo_PFD_VSpeed extends NavSystemElement {
...
```
Comment (beheh) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js:250]:
```suggestion
        let _deltaTime = this.getDeltaTime();
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js [hunk 20]
```diff
@@ -116,6 +120,19 @@ class A320_Neo_PFD_MainPage extends NavSystemPage {
...
+
+        if (this.yokePositionThrottler.canUpdate(_deltaTime) != -1) {
+            const YokeXPosition = 40.45 + (18.4 * SimVar.GetSimVarValue("YOKE X POSITION", "Position"));
+            const YokeYPosition = 47.95 - (14.45 * SimVar.GetSimVarValue("YOKE Y POSITION", "Position"));
+
+            this.groundCursor.style.left = YokeXPosition.toString() + "%";
+            this.groundCursor.style.top = YokeYPosition.toString() + "%";
+        }
+
+        _deltaTime = this.updateThrottler.canUpdate(_deltaTime);
```
Comment (beheh) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js:132]: This will need a let _deltaTime at the start of this function.

**Review by beheh — CHANGES_REQUESTED** [review]
Something still isn't quite right. There is at least one usage of `var` remaining, and I might've missed a few assignments in my last review, so some of the `const`s were not correct and should be `let` instead. This is what's causing the screen crash in the QA test.

I would suggest to double-check the proposed changes in the Sim to make sure they make sense and that I haven't missed any more.

**Comment by tjburni** [comment]
Category: QA Tester
Name: [Z+1]tjburni#0409
Date of testing: 15.1.2021
Version of the sim: 1.12.13
PR Tested: #000
Object of test:Optimize performance by sequencing updates
Testing technique: tested?
Steps you've made to test the Pull Request:full IFR C&D	
1. started at gate
2. took off
3. observed the fps 
4.landed


Flight notes (If required):

Issues (If Any): PFDs are not working
Overall Rating: Good if the PFDs are working
Conclusions of the testing: I got about 15 FPS more. Thanks for that PR!

**Comment by XSJoJo** [comment]
Sorry about the broken PFD I probably broke that while addressing changes
from code-review without retesting it. I'll fix it tonight.

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js (hunk 20 above)
Comment (XSJoJo) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js:132]: done

File: A32NX/html_ui/JS/A32NX_Util.js (hunk 12 above)
Comment (XSJoJo) [reply A32NX/html_ui/JS/A32NX_Util.js:88]: done

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js [hunk 21]
```diff
@@ -1382,16 +1382,25 @@ var A320_Neo_UpperECAM;
...
+            this.engUpdateThrottler = new UpdateThrottler(50);
             this.isInitialised = true;
         }
         update(_deltaTime) {
             if (!this.isInitialised || !A320_Neo_EICAS.isOnTopScreen()) {
                 return;
             }
 
+            var newDeltaTime = this.updateThrottler.canUpdate(_deltaTime);
+            var deltaTimeEng = this.engUpdateThrottler.canUpdate(_deltaTime);
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js:1395]:
```suggestion
            const newDeltaTime = this.updateThrottler.canUpdate(_deltaTime);
            const deltaTimeEng = this.engUpdateThrottler.canUpdate(_deltaTime);
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js [hunk 22]
```diff
@@ -58,6 +58,10 @@ class A320_Neo_PFD_MainPage extends NavSystemPage {
             this.navStatus,
             this.ils
         ]);
+        const url = document.getElementsByTagName("a320-neo-pfd-element")[0].getAttribute("url");
+        var dispIndex = parseInt(url.substring(url.length - 1));
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js:62]:
```suggestion
        const dispIndex = parseInt(url.substring(url.length - 1));
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js (hunk 20 above)
Comment (MisterChocker) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js:132]: at the very first line of onUpdate() function, const _deltaTime declaration needs to be let _deltaTime

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js [hunk 23]
```diff
@@ -232,11 +242,16 @@ class A320_Neo_PFD_VSpeed extends NavSystemElement {
...
         this.pot_index = this.disp_index == 1 ? 88 : 90;
+        this.updateThrottler = new UpdateThrottler(this.disp_index == 1 ? 50 : 100);
     }
     onEnter() {
     }
     onUpdate() {
-        const _deltaTime = this.getDeltaTime();
+        let _deltaTime = this.getDeltaTime();
+        _deltaTime = this.updateThrottler.canUpdate(_deltaTime);
+        if (_deltaTime == -1) {
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js:252]:
```suggestion
        if (this.updateThrottler.canUpdate(this.getDeltaTime()) === -1) {
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js [hunk 24]
```diff
@@ -268,11 +283,16 @@ class A320_Neo_PFD_Airspeed extends NavSystemElement {
...
         this.disp_index = parseInt(url.substring(url.length - 1));
         this.pot_index = this.disp_index == 1 ? 88 : 90;
+        this.updateThrottler = new UpdateThrottler(this.disp_index == 1 ? 50 : 100);
     }
     onEnter() {
     }
     onUpdate() {
-        const _deltaTime = this.getDeltaTime();
+        let _deltaTime = this.getDeltaTime();
+        _deltaTime = this.updateThrottler.canUpdate(_deltaTime);
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js:292]:
```suggestion
        const _deltaTime = this.updateThrottler.canUpdate(this.getDeltaTime());
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js [hunk 25]
```diff
@@ -296,11 +316,17 @@ class A320_Neo_PFD_Altimeter extends NavSystemElement {
...
+        if (_deltaTime == -1) {
+            return;
+        }
+        console.log(_deltaTime);
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js:329]:
```suggestion
        const _deltaTime = this.updateThrottler.canUpdate(this.getDeltaTime());
        if (_deltaTime == -1) {
            return;
        }
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js [hunk 26]
```diff
@@ -333,11 +359,16 @@ class A320_Neo_PFD_Attitude extends NavSystemElement {
...
         this.disp_index = parseInt(url.substring(url.length - 1));
         this.pot_index = this.disp_index == 1 ? 88 : 90;
+        this.updateThrottler = new UpdateThrottler(this.disp_index == 1 ? 50 : 100);
     }
     onEnter() {
     }
     onUpdate() {
-        const _deltaTime = this.getDeltaTime();
+        let _deltaTime = this.getDeltaTime();
+        _deltaTime = this.updateThrottler.canUpdate(_deltaTime);
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js:368]:
```suggestion
        const _deltaTime = this.updateThrottler.canUpdate(this.getDeltaTime());
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js [hunk 27]
```diff
@@ -382,11 +413,16 @@ class A320_Neo_PFD_Compass extends NavSystemElement {
...
         this.disp_index = parseInt(url.substring(url.length - 1));
         this.pot_index = this.disp_index == 1 ? 88 : 90;
+        this.updateThrottler = new UpdateThrottler(this.disp_index == 1 ? 60 : 200);
     }
     onEnter() {
     }
     onUpdate() {
-        const _deltaTime = this.getDeltaTime();
+        let _deltaTime = this.getDeltaTime();
+        _deltaTime = this.updateThrottler.canUpdate(_deltaTime);
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js:422]:
```suggestion
        const _deltaTime = this.updateThrottler.canUpdate(this.getDeltaTime());
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js [hunk 28]
```diff
@@ -413,11 +449,16 @@ class A320_Neo_PFD_NavStatus extends NavSystemElement {
...
         this.disp_index = parseInt(url.substring(url.length - 1));
         this.pot_index = this.disp_index == 1 ? 88 : 90;
+        this.updateThrottler = new UpdateThrottler(this.disp_index == 1 ? 200 : 500);
     }
     onEnter() {
     }
     onUpdate() {
-        const _deltaTime = this.getDeltaTime();
+        let _deltaTime = this.getDeltaTime();
+        _deltaTime = this.updateThrottler.canUpdate(_deltaTime);
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js:458]:
```suggestion
        const _deltaTime = this.updateThrottler.canUpdate(this.getDeltaTime());
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js [hunk 29]
```diff
@@ -440,11 +481,16 @@ class A320_Neo_PFD_ILS extends NavSystemElement {
...
         this.disp_index = parseInt(url.substring(url.length - 1));
         this.pot_index = this.disp_index == 1 ? 88 : 90;
+        this.updateThrottler = new UpdateThrottler(this.disp_index == 1 ? 150 : 300);
     }
     onEnter() {
     }
     onUpdate() {
-        const _deltaTime = this.getDeltaTime();
+        let _deltaTime = this.getDeltaTime();
+        _deltaTime = this.updateThrottler.canUpdate(_deltaTime);
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js:490]:
```suggestion
        const _deltaTime = this.updateThrottler.canUpdate(this.getDeltaTime());
```

File: A32NX/html_ui/JS/A32NX_Util.js [hunk 30]
```diff
@@ -45,3 +45,45 @@ A32NX_Util.createMachine = (machineDef) => {
...
+     * configured update interval.
+     *
+     * @param {*} deltaTime
+     * @returns -1 if the instrument should not update, or the time elapsed since the last
+     *          update in milliseconds
+     */
+    canUpdate(deltaTime) {
+        this.currentTime += deltaTime;
+        var number = Math.floor((this.currentTime + this.refreshOffset) / this.intervalMs);
+        var update = number > this.refreshNumber;
```
Comment (MisterChocker) [inline A32NX/html_ui/JS/A32NX_Util.js:79]:
```suggestion
        const number = Math.floor((this.currentTime + this.refreshOffset) / this.intervalMs);
        const update = number > this.refreshNumber;
```

File: A32NX/html_ui/JS/A32NX_Util.js [hunk 31]
```diff
@@ -45,3 +45,45 @@ A32NX_Util.createMachine = (machineDef) => {
...
+        this.refreshNumber = number;
+        if (update) {
+            var accumulatedDelta = this.currentTime - this.lastUpdateTime;
```
Comment (MisterChocker) [inline A32NX/html_ui/JS/A32NX_Util.js:82]:
```suggestion
            const accumulatedDelta = this.currentTime - this.lastUpdateTime;
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BAT/A320_Neo_BAT.js [hunk 32]
```diff
@@ -16,7 +17,10 @@ var A320_Neo_BAT;
         }
         onUpdate(_deltaTime) {
             super.onUpdate(_deltaTime);
-
+            _deltaTime = this.updateThrottler.canUpdate(_deltaTime);
+            if (_deltaTime == -1) {
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BAT/A320_Neo_BAT.js:21]:
```suggestion
            if (this.updateThrottler.canUpdate(_deltaTime) === -1) {
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BRK/A320_Neo_BRK.js [hunk 33]
```diff
@@ -67,9 +67,14 @@ var A320_Neo_BRK;
             this.rightGauge.addMarker(2.5, true);
             this.rightGauge.addMarker(3, false);
             this.electricity = this.querySelector("#Electricity");
+            this.updateThrottler = new UpdateThrottler(100);
         }
         onUpdate(_deltaTime) {
             super.onUpdate(_deltaTime);
+            _deltaTime = this.updateThrottler.canUpdate(_deltaTime);
+            if (_deltaTime == -1) {
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BRK/A320_Neo_BRK.js:75]:
```suggestion
            if (this.updateThrottler.canUpdate(_deltaTime) === -1) {
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Clock/A320_Neo_Clock.js [hunk 34]
```diff
@@ -28,7 +29,10 @@ class A320_Neo_Clock extends BaseAirliners {
     }
     onUpdate(_deltaTime) {
         super.onUpdate(_deltaTime);
-
+        _deltaTime = this.updateThrottler.canUpdate(_deltaTime);
+        if (_deltaTime == -1) {
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Clock/A320_Neo_Clock.js:33]:
```suggestion
        if (this.updateThrottler.canUpdate(_deltaTime) === -1) {
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js [hunk 35]
```diff
@@ -136,13 +136,17 @@ class A320_Neo_EICAS extends Airliners.BaseEICAS {
...
     }
 
     onUpdate() {
-        const _deltaTime = this.getDeltaTime();
+        let _deltaTime = this.getDeltaTime();
 
         super.onUpdate(_deltaTime);
-
+        _deltaTime = this.updateThrottler.canUpdate(_deltaTime);
+        if (_deltaTime == -1) {
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js:147]:
```suggestion
        if (_deltaTime === -1) {
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_APU.js [hunk 36]
```diff
@@ -53,13 +53,19 @@ var A320_Neo_LowerECAM_APU;
...
+            this.updateThrottler = new UpdateThrottler(75);
             this.isInitialised = true;
         }
         update(_deltaTime) {
             if (!this.isInitialised || !A320_Neo_EICAS.isOnBottomScreen()) {
                 return;
             }
 
+            _deltaTime = this.updateThrottler.canUpdate(_deltaTime);
+            if (_deltaTime == -1) {
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_APU.js:65]:
```suggestion
            if (_deltaTime === -1) {
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_BLEED.js [hunk 37]
```diff
@@ -128,7 +130,10 @@ var A320_Neo_LowerECAM_BLEED;
             if (!this.isInitialised || !A320_Neo_EICAS.isOnBottomScreen()) {
                 return;
             }
-
+            _deltaTime = this.updateThrottler.canUpdate(_deltaTime);
+            if (_deltaTime == -1) {
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_BLEED.js:134]:
```suggestion
            if (this.updateThrottler.canUpdate(_deltaTime) === -1) {
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_COND.js [hunk 38]
```diff
@@ -45,13 +45,18 @@ var A320_Neo_LowerECAM_COND;
...
+            this.updateThrottler = new UpdateThrottler(500);
         }
 
         update(_deltaTime) {
             if (!this.isInitialised || !A320_Neo_EICAS.isOnBottomScreen()) {
                 return;
             }
-
+            _deltaTime = this.updateThrottler.canUpdate(_deltaTime);
+            if (_deltaTime == -1) {
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_COND.js:57]:
```suggestion
            if (this.updateThrottler.canUpdate(_deltaTime) === -1) {
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_CRZ.js [hunk 39]
```diff
@@ -105,13 +105,18 @@ var A320_Neo_LowerECAM_CRZ;
...
+
             this.isInitialised = true;
         }
         update(_deltaTime) {
             if (!this.isInitialised || !A320_Neo_EICAS.isOnBottomScreen()) {
                 return;
             }
-
+            _deltaTime = this.updateThrottler.canUpdate(_deltaTime);
+            if (_deltaTime == -1) {
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_CRZ.js:117]:
```suggestion
            if (this.updateThrottler.canUpdate(_deltaTime) === -1) {
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_DOOR.js [hunk 40]
```diff
@@ -40,13 +40,18 @@ var A320_Neo_LowerECAM_DOOR;
...
+
             this.isInitialised = true;
         }
         update(_deltaTime) {
             if (!this.isInitialised || !A320_Neo_EICAS.isOnBottomScreen()) {
                 return;
             }
-
+            _deltaTime = this.updateThrottler.canUpdate(_deltaTime);
+            if (_deltaTime == -1) {
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_DOOR.js:52]:
```suggestion
            if (this.updateThrottler.canUpdate(_deltaTime) === -1) {
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Elec.js [hunk 41]
```diff
@@ -255,13 +255,19 @@ var A320_Neo_LowerECAM_Elec;
...
+
             this.isInitialised = true;
 
             this.updateVariables();
             this.systemDraw();
         }
 
         update(_deltaTime) {
+            _deltaTime = this.updateThrottler.canUpdate(_deltaTime);
+            if (_deltaTime == -1) {
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Elec.js:268]:
```suggestion
            if (this.updateThrottler.canUpdate(_deltaTime) === -1) {
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Engine.js [hunk 42]
```diff
@@ -39,12 +39,17 @@ var A320_Neo_LowerECAM_Engine;
...
             this.ignRightCurrentState = A320_Neo_LowerECAM_Engine.Definitions.IGN_STATE.NONE;
+            this.updateThrottler = new UpdateThrottler(200);
             this.isInitialised = true;
         }
         update(_deltaTime) {
             if (!this.isInitialised || !A320_Neo_EICAS.isOnBottomScreen()) {
                 return;
             }
+            _deltaTime = this.updateThrottler.canUpdate(_deltaTime);
+            if (_deltaTime == -1) {
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Engine.js:50]:
```suggestion
            if (_deltaTime === -1) {
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_FTCL.js [hunk 43]
```diff
@@ -77,6 +79,11 @@ let A320_Neo_LowerECAM_FTCL;
                 return;
             }
 
+            _deltaTime = this.updateThrottler.canUpdate(_deltaTime);
+            if (_deltaTime == -1) {
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_FTCL.js:83]:
```suggestion
            if (this.updateThrottler.canUpdate(_deltaTime) === -1) {
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Fuel.js [hunk 44]
```diff
@@ -89,12 +89,17 @@ var A320_Neo_LowerECAM_Fuel;
...
             }
+            this.updateThrottler = new UpdateThrottler(500);
             this.isInitialised = true;
         }
         update(_deltaTime) {
             if (!this.isInitialised || !A320_Neo_EICAS.isOnBottomScreen()) {
                 return;
             }
+            _deltaTime = this.updateThrottler.canUpdate(_deltaTime);
+            if (_deltaTime == -1) {
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Fuel.js:100]:
```suggestion
            if (this.updateThrottler.canUpdate(_deltaTime) === -1) {
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_PRESS.js [hunk 45]
```diff
@@ -210,7 +211,10 @@ var A320_Neo_LowerECAM_PRESS;
             if (!this.isInitialised || !A320_Neo_EICAS.isOnBottomScreen()) {
                 return;
             }
-
+            _deltaTime = this.updateThrottler.canUpdate(_deltaTime);
+            if (_deltaTime == -1) {
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_PRESS.js:215]:
```suggestion
            if (this.updateThrottler.canUpdate(_deltaTime) === -1) {
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Status.js [hunk 46]
```diff
@@ -352,19 +351,21 @@ var A320_Neo_LowerECAM_Status;
...
                 return;
             }
-            this.frameCount++;
-            if (this.frameCount % 8 == 0) {
-                this.statusMessageArea.update();
-                this.inopSystemsMessageArea.update();
-                this.statusNormal.setAttribute("visibility", (this.statusMessageArea.hasActiveFailures || this.inopSystemsMessageArea.hasActiveMessages) ? "hidden" : "visible");
-                this.inopSysTitle.setAttribute("visibility", (this.statusMessageArea.hasActiveFailures || this.inopSystemsMessageArea.hasActiveMessages) ? "visible" : "hidden");
+            _deltaTime = this.updateThrottler.canUpdate(_deltaTime);
+            if (_deltaTime == -1) {
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Status.js:362]:
```suggestion
            if (this.updateThrottler.canUpdate(_deltaTime) === -1) {
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_WHEEL.js [hunk 47]
```diff
@@ -243,7 +245,10 @@ var A320_Neo_LowerECAM_WHEEL;
             if (!this.isInitialised || !A320_Neo_EICAS.isOnBottomScreen()) {
                 return;
             }
-
+            _deltaTime = this.updateThrottler.canUpdate(_deltaTime);
+            if (_deltaTime == -1) {
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_WHEEL.js:249]:
```suggestion
            if (_deltaTime === -1) {
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js [hunk 48]
```diff
@@ -1382,16 +1382,25 @@ var A320_Neo_UpperECAM;
...
+
             for (let i = 0; i < this.allPanels.length; ++i) {
                 if (this.allPanels[i] != null) {
-                    this.allPanels[i].update(_deltaTime);
+                    var isEng = this.allPanels[i] instanceof A320_Neo_UpperECAM.EnginePanel;
+                    var panelDeltaTime = isEng ? deltaTimeEng : newDeltaTime;
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js:1400]:
```suggestion
                    const isEng = this.allPanels[i] instanceof A320_Neo_UpperECAM.EnginePanel;
                    const panelDeltaTime = isEng ? deltaTimeEng : newDeltaTime;
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js [hunk 49]
```diff
@@ -164,9 +167,16 @@ class A320_Neo_MFD_MainPage extends NavSystemPage {
...
-        const _deltaTime = this.getDeltaTime();
+        let _deltaTime = this.getDeltaTime();
         super.onUpdate(_deltaTime);
-        this.updateMap(_deltaTime);
+        const mapDeltaTime = this.mapUpdateThrottler.canUpdate(_deltaTime);
+        if (mapDeltaTime != -1) {
+            this.updateMap(mapDeltaTime);
+        }
+        _deltaTime = this.updateThrottler.canUpdate(_deltaTime);
+        if (_deltaTime == -1) {
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js:177]:
```suggestion
        if (_deltaTime === -1) {
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js [hunk 50]
```diff
@@ -575,10 +585,15 @@ class A320_Neo_MFD_Compass extends NavSystemElement {
         const url = document.getElementsByTagName("a320-neo-mfd-element")[0].getAttribute("url");
         this.screenIndex = parseInt(url.substring(url.length - 1));
         this.potIndex = this.screenIndex == 1 ? 89 : 91;
+        this.updateThrottler = new UpdateThrottler(this.screenIndex == 1 ? 20 : 100);
     }
     onEnter() {
     }
     onUpdate(_deltaTime) {
+        _deltaTime = this.updateThrottler.canUpdate(_deltaTime);
+        if (_deltaTime == -1) {
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js:594]:
```suggestion
        if (_deltaTime === -1) {
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js [hunk 51]
```diff
@@ -780,10 +795,15 @@ class A320_Neo_MFD_NDInfo extends NavSystemElement {
         const url = document.getElementsByTagName("a320-neo-mfd-element")[0].getAttribute("url");
         this.screenIndex = parseInt(url.substring(url.length - 1));
         this.potIndex = this.screenIndex == 1 ? 89 : 91;
+        this.updateThrottler = new UpdateThrottler(this.screenIndex == 1 ? 200 : 400);
     }
     onEnter() {
     }
     onUpdate(_deltaTime) {
+        _deltaTime = this.updateThrottler.canUpdate(_deltaTime);
+        if (_deltaTime == -1) {
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js:804]:
```suggestion
        if (_deltaTime === -1) {
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/SAI/A320_Neo_SAI.js [hunk 52]
```diff
@@ -62,13 +62,18 @@ class A320_Neo_SAI_Airspeed extends NavSystemElement {
...
+        this.updateThrottler = new UpdateThrottler(50);
     }
     onEnter() {
     }
     isReady() {
         return true;
     }
     onUpdate(_deltaTime) {
+        _deltaTime = this.updateThrottler.canUpdate(_deltaTime);
+        if (_deltaTime == -1) {
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/SAI/A320_Neo_SAI.js:74]:
```suggestion
        if (_deltaTime === -1) {
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/SAI/A320_Neo_SAI.js [hunk 53]
```diff
@@ -387,6 +393,10 @@ class A320_Neo_SAI_Altimeter extends NavSystemElement {
         ;
     }
     onUpdate(_deltaTime) {
+        _deltaTime = this.updateThrottler.canUpdate(_deltaTime);
+        if (_deltaTime == -1) {
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/SAI/A320_Neo_SAI.js:397]:
```suggestion
        if (_deltaTime === -1) {
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/SAI/A320_Neo_SAI.js [hunk 54]
```diff
@@ -691,10 +701,15 @@ class A320_Neo_SAI_Attitude extends NavSystemElement {
             const aspectRatio = this.gps.getAspectRatio();
             this.attitudeElement.setAttribute("aspect-ratio", aspectRatio.toString());
         }
+        this.updateThrottler = new UpdateThrottler(50);
     }
     onEnter() {
     }
     onUpdate(_deltaTime) {
+        _deltaTime = this.updateThrottler.canUpdate(_deltaTime);
+        if (_deltaTime == -1) {
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/SAI/A320_Neo_SAI.js:710]:
```suggestion
            if (this.updateThrottler.canUpdate(_deltaTime) === -1) {
```
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/SAI/A320_Neo_SAI.js [hunk 55]
```diff
@@ -1043,13 +1058,18 @@ customElements.define('a320-neo-sai-attitude-indicator', A320_Neo_SAI_AttitudeIn
...
+        this.updateThrottler = new UpdateThrottler(500);
     }
     onEnter() {
     }
     isReady() {
         return true;
     }
     onUpdate(_deltaTime) {
+        _deltaTime = this.updateThrottler.canUpdate(_deltaTime);
+        if (_deltaTime == -1) {
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/SAI/A320_Neo_SAI.js:1070]:
```suggestion
        if (_deltaTime === -1) {
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/SAI/A320_Neo_SAI.js [hunk 56]
```diff
@@ -1234,6 +1255,10 @@ class A320_Neo_SAI_SelfTest extends NavSystemElement {
         }
     }
     onUpdate(_deltaTime) {
+        _deltaTime = this.updateThrottler.canUpdate(_deltaTime);
+        if (_deltaTime == -1) {
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/SAI/A320_Neo_SAI.js:1259]:
```suggestion
            if (this.updateThrottler.canUpdate(_deltaTime) === -1) {
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/SAI/A320_Neo_SAI.js [hunk 57]
```diff
@@ -1443,13 +1468,18 @@ class A320_Neo_SAI_AttReset extends NavSystemElement {
...
+        this.updateThrottler = new UpdateThrottler(100);
     }
     onEnter() {
     }
     isReady() {
         return true;
     }
     onUpdate(_deltaTime) {
+        _deltaTime = this.updateThrottler.canUpdate(_deltaTime);
+        if (_deltaTime == -1) {
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/SAI/A320_Neo_SAI.js:1480]:
```suggestion
            if (this.updateThrottler.canUpdate(_deltaTime) === -1) {
```

**Review by MisterChocker — CHANGES_REQUESTED** [review]
Removed unused variables, made comparisons strict using `===`, removed unneeded redeclaration of variables, fixed const being falsely const.

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BRK/A320_Neo_BRK.js (hunk 33 above)
Comment (XSJoJo) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BRK/A320_Neo_BRK.js:75]: Hmm I think this may be a bit dangerous to do in case somebody later adds some code below that would use _deltaTime - in that case, _deltaTime would be wrong. Wdyt?

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js (hunk 20 above)
Comment (XSJoJo) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js:134]: Yes, that's done in the latest version.

**Comment by TwitchyShell** [comment]
**Category:** QA Tester
**Name:** Тайга Мөңгүн#2000
**Date of testing:** 2021-01-16
**Version of the sim:** 1.12.13.0
**PR Tested:** #2976
**Object of test:** Testing performance optimisation

# **Testing technique:**
Full line flight, UHSS - UHSK in almost identical scenarios. Meteoblue live weather used.

## **Steps you've made to test the Pull Request:**
Conduct line flight as normal with almost identical set ups and flight paths, noting FPS at specific phases of flight

# **Flight notes:**
Powered up, completed preflight, noted FPS, figure 1.

Start up and taxi as usual, began take off roll. Reached cloud layer on initial climb, noted FPS, figure 2.

Continued climb to cruise, noted FPS, figure 3.

Conducted 2LOC approach IMC, noted FPS.

Broke visual, final approach, noted FPS, figure 4.

Taxi in and shut down as normal.

## Figures as below:
### Parked

Figure 1.1 (Baseline)


Figure 1.1 (#2976)

### Initial climb (in cloud)

Figure 2.1 (Baseline)


Figure 2.2 (#2976)

### Cruise

Figure 3.1 (Baseline)


Figure 3.2 (#2976)

### Approach

Figure 4.1 (Baseline)


Figure 4.2 (#2976)

Maximum of 2 FPS improvement observed, noted improved smoothness and resolved jitter with view 'whips'. Additional notes in conclusions.

# **Issues (If Any):** 
Minor issue with ISIS baro setting. 1 second delay with any control input, causing possible nuisance when attempting to change baro setting.

### **Overall Rating:** Good

# **Conclusions of the testing:** 
Due to this system being GPU limited, minimal changes observed which is expected behaviour. Acknowledge micro stutters resolved with rapid view movement when 'whipping' head around. Maximum 2 FPS increase. Changes to update rates to avionics have minimal impact on operations; ISIS baro causes some degree of user confusion and nuisance.

System specs:
i7-10700K 4.9GHz
64GB RAM 3200Hz CL16
Nvidia GeForce GTX 1070 (EVGA FTW3)
SATA SSD, Samsung 860

**Comment by XSJoJo** [comment]
Thanks for doing a full flight test! Looks like even on your system
CoherentGT draw times become much more consistent (as indicated by the more
green bars).

Let me fix the ISIS baro issue. That's the additional
attitude/speed/altimeter instrument to the left of the upper ECAM right?

**Comment by MisterChocker** [comment]
@TwitchyShell it's not RTT!

File: A32NX/html_ui/JS/A32NX_Util.js (hunk 30 above)
Comment (XSJoJo) [reply A32NX/html_ui/JS/A32NX_Util.js]: Done.

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js (hunk 35 above)
Comment (XSJoJo) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js]: done.

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Elec.js (hunk 41 above)
Comment (XSJoJo) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Elec.js]: Done.

**Review by MisterChocker — APPROVED** [review]

**Comment by Benjozork** [comment]
> @TwitchyShell it's not RTT!

It's fine I told him he could test it

**Comment by MisterChocker** [comment]
@beheh is there still something that needs to be addressed?

**Review by beheh — APPROVED** [review]

**Comment by TwitchyShell** [comment]
> Thanks for doing a full flight test! Looks like even on your system CoherentGT draw times become much more consistent (as indicated by the more green bars). Let me fix the ISIS baro issue. That's the additional attitude/speed/altimeter instrument to the left of the upper ECAM right?

Yes, that is correct. The standby display is the only outstanding issue. 

Also yes, the FPS increase is minimal, but the GPU draws are more stable, less microstutters, so it's still a win!

**Comment by MisterChocker** [comment]
> the FPS increase is minimal,

The overall FPS increase is depended on your hardware, not generally the same for everyone.

**Comment by XSJoJo** [comment]
> > Thanks for doing a full flight test! Looks like even on your system CoherentGT draw times become much more consistent (as indicated by the more green bars). Let me fix the ISIS baro issue. That's the additional attitude/speed/altimeter instrument to the left of the upper ECAM right?
> 
> Yes, that is correct. The standby display is the only outstanding issue.

Can you retest on the latest version? That should be fixed now.

> 
> Also yes, the FPS increase is minimal, but the GPU draws are more stable, less microstutters, so it's still a win!

**Comment by MapleNAV-TCASFAULT** [comment]
Category: QA Tester
Name: ChristopherXie#3904
Date of testing: Current date 01/16/2021
Version of the sim: 1.12.13.0
PR Tested: #2976 
Object of test: Perf optimization by sequencing updates
PC Specs: 
- Ryzen 5 2600
- 16gb DDR4 3200mhz
- GTX 1650, OC'd to 2000mhz with VRAM OC'd from 4000mhz to 4600mhz

Testing technique: Downloaded artifact and entered the sim, with FPS display
Steps you've made to test the Pull Request:
1. Spawned on a runway at CYYZ with no F-PLN with low refresh rate, changed it medium then high (to test overall FPS / stutter improvements)
2. Spawned on a runway at CYYZ with a long F-PLN (CYYZ - VHHH), and just like step 1, I changed the refresh rate (to test coherent GT draw)
3. Did a takeoff and landing to ensure that the PFD worked (as previous tests had issues with it)
4. 
5.

Flight notes (If required):

Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: For my system I experienced no FPS improvements, still hovering around ~30 fps, but stutters have significantly gone down. Low - Medium - High refresh rates have no effect on FPS, but stuttering does slightly increase when refresh rate is increased. Coherent GT draw is still at the same level when a long flight plan is loaded into the MCDU. Other than that, I'm excited to see this merged into dev soon!

**Comment by e4rthdog** [comment]
Is this in the DEV version now?

**Comment by XSJoJo** [comment]
Yes, this has been merged to dev.
