### PR TITLE
fix: pushback without command

### LINKED ISSUE #5315: Pushback Begins Without Command
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-13T05:36:14+00:00",
  "ref": "master",
  "sha": "faee7a996a5c51708fc4ed76963d58b18bbb59a9",
  "actor": "2hwk",
  "event_name": "manual"
}
```

### Describe the bug

Pushback begins without command if not on the Ground page.

### Expected behavior

Pushback to only begin when command given.

### Steps to reproduce

1. Spawn C&D
2. Use EFB and call a tug
3. Right after calling a pushback navigate and remain to another page

### References (optional)

https://user-images.githubusercontent.com/72807945/125545082-a94ae74b-b98c-44bf-9194-d3e164d2612f.mp4

### Additional info (optional)

_No response_

### Discord Username (optional)

Aviation Spotter#9102

### PR DESCRIPTION
**Pull request by kiemdoder**
This is a fix for the case where the tug started an unintentional push back by calling the tug first from the ground tab in the EFB and then switching to another tab in the EFB while the tug was still on its way.

Fixes #5315

## Summary of Changes

To prevent the tug from starting a push back on its arrival a timer was used to continually set the PushBackWait simvar. This timer got cancelled by the useEffect that started it when the Ground component got unloaded by selecting some other tab in the EFB for instance. 

The handle for the timer is now kept in the redux store and used to clear the timer when the tug is dismissed again.
## Additional context

Discord username (if different from GitHub):

## Testing instructions

1. Select the ground tab in the EFB and click the tug button to request the tug.
2. While the tug is on its way select some other tab in the EFB so that the ground tab is unloaded.
3. Wait for the tug to arrive an connect. I should not start with a push back at this stage.
4. Select the ground tab again and click one of the push back arrows to start a push back. Push back is expected to start.
5. Click the push back stop button. Push back is expected to stop.
6. Click the request tug button again. The tug is expected to be dismissed.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

File: src/instruments/src/EFB/Store/reducer/ground-reducer.tsx [hunk 1]
```diff
@@ -6,19 +6,21 @@ import {
...
+    SET_PUSH_BACK_WAIT_TIMER_HANDLE,
 } from '../actions';
 
 type ButtonSelectionState = {
     activeButtons: any[];
     disabledButtons: string[];
-    tugRequestOnly: boolean,
-
+    tugRequestOnly: boolean;
+    pushBackWaitTimerHandle: number
```
Comment (ErickSharp) [inline src/instruments/src/EFB/Store/reducer/ground-reducer.tsx:16]: Can you add a semicolon to terminate this line, please?

File: src/instruments/src/EFB/Settings/Settings.tsx [hunk 2]
```diff
@@ -1,6 +1,6 @@
 import React, { useState } from 'react';
 import { Slider, Toggle } from '@flybywiresim/react-components';
-import { useSimVar } from '@instruments/common/simVars';
+import { useSimVar } from '../../Common/simVars';
```
Comment (ErickSharp) [inline src/instruments/src/EFB/Settings/Settings.tsx:3]: Please keep the @ import.

**Review by ErickSharp — CHANGES_REQUESTED** [review]
Just some minor things for now.

File: src/instruments/src/EFB/Ground/Ground.tsx [hunk 3]
```diff
@@ -31,7 +32,7 @@ export const Ground = ({
     const [pushBack, setPushBack] = useSplitSimVar('PUSHBACK STATE', 'enum', 'K:TOGGLE_PUSHBACK', 'bool', 1000);
     const [powerActive, setPowerActive] = useSplitSimVar('A:INTERACTIVE POINT OPEN:8', 'Percent over 100', 'K:REQUEST_POWER_SUPPLY', 'bool', 1000);
 
-    const [pushBackWait, setPushBackWait] = useSimVar('Pushback Wait', 'bool', 100);
+    const setPushBackWait = useSimVarSetter('Pushback Wait', 'bool');
```
Comment (ErickSharp) [inline src/instruments/src/EFB/Ground/Ground.tsx:35]: Could we just keep using `useSimvar` to avoid another import? I believe you could do something like this `const [, setPushBackWait] = useSimVar('Pushback Wait', 'bool');`

File: src/instruments/src/EFB/Settings/Settings.tsx (hunk 2 above)
Comment (kiemdoder) [reply src/instruments/src/EFB/Settings/Settings.tsx:3]: For some reason with this specific import it fails when the code is compiled with `npm run serve:efb`. I see the same import has already been changed in some other files to what I have here. I'm not arguing against the change. I'm just explaining why I made the change. I will revert back to the original import which does work when building the whole project with `scripts/build.sh`

File: src/instruments/src/EFB/Store/reducer/ground-reducer.tsx (hunk 1 above)
Comment (kiemdoder) [reply src/instruments/src/EFB/Store/reducer/ground-reducer.tsx:16]: Sure. I missed that. Normally prettier picks that sort of thing up. Odd.

File: src/instruments/src/EFB/Ground/Ground.tsx (hunk 3 above)
Comment (kiemdoder) [reply src/instruments/src/EFB/Ground/Ground.tsx:35]: Will do.

File: src/instruments/src/EFB/Settings/Settings.tsx (hunk 2 above)
Comment (ErickSharp) [reply src/instruments/src/EFB/Settings/Settings.tsx]: > For some reason with this specific import it fails when the code is compiled with `npm run serve:efb`. I see the same import has already been changed in some other files to what I have here. I'm not arguing against the change. I'm just explaining why I made the change. I will revert back to the original import which does work when building the whole project with `scripts/build.sh` 

Very odd, in that case you can opt for what works :)

Comment (kiemdoder) [reply src/instruments/src/EFB/Settings/Settings.tsx]: No problem. I can change it again in future if it is still a problem. I changed back to `@instruments/common/simVars` already. I noticed that intellij/webstorm also suggests @instruments/common/simVars for the import.

**Review by Benjozork — APPROVED** [review]

**Comment by NUTTTTTTTT** [comment]
Quality Assurance Tester Report

Discord: █▀█ █▄█ ▀█▀#2123
Object of testing: #PR 5684
Tier of Testing: 1
Date: 23/08/2021

Testing Process:
- Loaded in C+D at a gate at EGSS.
- Opened EFB, selected ground tab and requested tug.
- While tug was connecting, changed tab, checked a/c pushback not started uncommanded - PASS
- Selected ground tab, started pushback, switched tabs to check pushback as normal - PASS
- Selected ground tab, stopped pushback and dismissed tug, checked functions as intended - PASS

Negatives: N/A
Testing Results: PASS 

Conclusions: Works as described, no other issues noted - had a mess around with the other EFB functions, ground crew and tug directions, all observed to be working.

**Comment by John-UK** [comment]
Quality Assurance Tester (trainee) Report

Discord: john P Maguire#9027
Object of testing: #PR 5684
Tier of Testing: 1
Date: 24/08/2021

Testing Process:

Loaded in C&D at a stand EGLL. Competed a fully correct pre start routine ready to push.
Opened EFB, selected ground tab and requested tug.
Before tug was connected, changed tab to nav. Let the tug connect then selected performance. Push back started uncommanded.  Selected ground the push slowed to a stop. Once stopped pushback did not start on changing tabs. It could be stopped and started with the pushback buttons.

This was repeatable with the same outcome each time.

Negatives: The push back can be started without using the correct process.
Testing Results: Fail

Conclusions:

**Comment by John-UK** [comment]
Quality Assurance Tester Report

Discord: john P Maguire#9027
Object of testing: #PR 5684
Tier of Testing: 1
Date: 24/08/2021

Testing Process:

Loaded in C&D at a stand EGLL. Competed a fully correct pre start to ready to push.
Opened EFB, selected ground tab and requested tug.
Before tug connected changed tab to nav. Let the tug connect and waited. An uncommanded pushback. Fail
The push is not obvious until releasing park brake.
On selecting ground the tug slows to a stop. Selecting other tabs does not restart the push. It can be restarted and stopped using the correct buttons on ground tab.

Negatives: Pushback started with out use of ground pushback buttons.
Testing Results: PASS

Conclusions:

**Comment by John-UK** [comment]
Quality Assurance Tester Report

Discord: john P Maguire#9027
Object of testing: #PR 5684
Tier of Testing: 1
Date: 24/08/2021

Testing Process:

Loaded in C&D at a stand EGLL. Competed a fully correct pre start to ready to push.
Opened EFB, selected ground tab and requested tug.
While tug was connecting, changed tab to nav. Let the tug connect and waited uncommanded pushback. Fail
The push is not obvious until releasing park brake.
On selecting ground the tug slows to a stop. Selecting other tabs does not restart the push. It can be restarted and stopped using the correct buttons on ground tab.

Negatives: Pushback started without use of ground pushback buttons.
Testing Results: PASS

Conclusions:

**Comment by oim1** [comment]
Quality Assurance Trainee Report

Object of testing: #5684
Tier of Testing: 1
Date: 24/08/2021

Testing Process: 
Loaded Cold and Dark YMML
Turned on Flypad
Followed steps in testing instructions

Negatives: N/A
Testing Results: Passed

Conclusions: Everything worked fine. Pushback didn't start until it was told to. LGTM.

**Comment by Benjozork** [comment]
> Negatives: Pushback started without use of ground pushback buttons.
> Testing Results: PASS

Why is this PASS ?

**Comment by 2hwk** [comment]
> While tug was connecting, changed tab to nav. Let the tug connect and waited uncommanded pushback. Fail
> Negatives: Pushback started without use of ground pushback buttons.

@John-UK
This sounds like there are still some issues, did you have AI assist on?

**Comment by kiemdoder** [comment]
I will have a look. Maybe some merging issues. I tested it many times always with the parking brake released and I have no doubt it was working fine. Hopefully the problem is easy to resolve.

**Comment by oim1** [comment]
> I see there are some conflicting test reports. I looks like @NUT and @oim1  had  positive test results. 
> 
> I will have a look. Maybe some merging issues. I tested it many times always with the parking brake released and I have no doubt it was working fine. Hopefully the problem is easy to resolve.

i can always retest if you want - i can probably squeeze one in before i leave for tonight

**Comment by kiemdoder** [comment]
I see that merging has been blocked (towards the end of this page) "The base branch restricts merging to authorized users." Is that not maybe the problem?

**Comment by Benjozork** [comment]
No, this means only dev team members can merge the PR.

**Comment by kiemdoder** [comment]
Has the changes in the PR been merged to master then?

**Comment by oim1** [comment]
I'll try see if I can reproduce the issue with @John-UK's method of testing later on

**Comment by Benjozork** [comment]
No. As long as the green "Open" status is present, it is not merged.

image

It will show a purple "Merged" status here when merged.

**Comment by John-UK** [comment]
A third test of this PR
I deleted my FBW folder from community. Downloaded this PR again. Extracted and copied the FBW folder back into community. 
Is there a line in a JSON file that confirms that I am building the correct artefact? Although I can't see why I would not be.

I have the same results with the following additional observation. On the first test the nav tab did not load my navigraph charts page. It displayed loading and requesting authentication. On this test the tug did not start to push back (coincidence?).  I have not been able to reproduce the requesting authentication.

On subsequent testing the navigation tab displayed the navigraph search bar correctly and the pushback started uncommanded using the same process used in last testing. Call tug, select nav tab immediately and wait. 

I do QA with the community folder in three states. 
1. My base addons which has two non default airports EGTB and EGCC (I use for training and testing) and enhanced ground vehicles for eye candy. Plus the folders shown below.
2. With the minimum addons I would expect many users to have. The folders shown below
3. The FBW folder only.

I test a minimum of 5 times quitting to desktop each time. Using a fully correct flow (major airline procedure not FBW checklist). Before doing a set of different runs with out of order flows and incorrect startups. Before filing a QA report. That's at least 4 hours of testing on the stand even for a small change like this. On this PR I have been testing for around 10 hours.



image

**Comment by oim1** [comment]
All of my failed PR issues were solved by a fresh install of MSFS, although i'm not sure if that's a thing many people want to do

**Comment by NUTTTTTTTT** [comment]
Hi @John-UK - I will retest as well, are you able to verify the build is correct in config.json? worried why I'm getting different results as I did run through various conditions and triggering from different states, although definitely not 10 hours on a PR of the size.

**Comment by oim1** [comment]
Quality Assurance Trainee Report

Object of testing: #5684
Tier of Testing: 1
Date: 24/08/2021

Testing Process:
Followed same steps @John-UK listed in his report

Negatives: N/A
Testing Results: Passed

Conclusions: Same results as last time. It passed. I'm not too sure what the issue is or what's causing the failed pr.

**Comment by NUTTTTTTTT** [comment]
Going to retest this from my end with navigraph and see if I can reproduce the issues - @John-UK has recorded and uploaded https://streamable.com/s91o5e showing the issue again on the Github artifact.

**Comment by John-UK** [comment]
Quality Assurance Tester (trainee) Report

Discord: john P Maguire#9027
Object of testing: #PR 5684
Tier of Testing: 1
Date: 24/08/2021

Testing Process:

Loaded in C&D at a stand EGLL. Competed a fully correct pre start to ready to push.
Opened EFB, selected ground tab and requested tug. No un-commanded pushback seen.

Negatives: Nothing to report
Testing Results: Pass

Conclusions: During the testing process I had exp in a temp folder. Somehow I would see exp or this PR code when only restarting MSFS. Resulting in my confusion over seeing navigraph authentication required on some occasions and not others.

**Comment by Benjozork** [comment]
What is your Discord username so we can give you the Contributor role ?
