### PR TITLE
fix(adirs): ADIRUs not aligned starting on runway

### LINKED ISSUE #4506: A/C spawns in different ADIRS status
**Aircraft Version**
{
  "built": "2021-04-18T16:55:51+00:00",
  "ref": "experimental",
  "sha": "f52894be67d287a02fe2918e9963d7464e5d8d7b",
  "actor": "aguther",
  "event_name": "manual"
}

The aircraft spawns in various configs. Sometimes the ADIRS are aligned, sometimes not.

**To Reproduce**

Hitting the Fly Now button causes the a/c to "reboot" as all relays are clicking again and the engines start to spool up again. They don't shut down but when the aircraft gets spawned from the holding point onto the runway it seems as some systems re-initialize.

**Expected behavior**
Once the a/c has completely loaded it shouldn't re-initialize when the fly now button is clicked.

**Actual behavior**

Hitting the Fly Now button causes the a/c to "reboot" as all relays are clicking again and the engines start to spool up again. They don't shut down but when the aircraft gets spawned from the holding point onto the runway it seems as some systems re-initialize.

**References**

N/A

**Additional context**

Was this working before/when did the issue start occurring?
This issue is relatively new but I can't remember how many updates before this was introduced.

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):
Cpt. Chaos
#3721

### PR DESCRIPTION
**Pull request by davidwalschots**
Fixes #4506 (the issue description states many things and is a bit chaotic, but this seems to be the main issue).

## Summary of Changes
Fixes ADIRUs not always being aligned starting on the runway.

## Additional context

Discord username (if different from GitHub): SjotgunSjonnie#9623

## Testing instructions
- Ensure the ADIRUs are aligned on the runway and in other spawning locations where this is to be expected.
- Ensure the ADIRUs are not aligned at the gate and in other spawning locations where this is to be expected.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

File: flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_ADIRS.js [hunk 1]
```diff
@@ -1,28 +1,34 @@
...
+        this.onBatTimer = 0;
     }
 
     init() {
-        this.knob = SimVar.GetSimVarValue(`L:A32NX_ADIRS_KNOB_${this.num}`, 'Enum');
-        SimVar.SetSimVarValue(`L:A32NX_ADIRS_TIMER_${this.num}`, 'Seconds', -1);
+        this.knob = SimVar.GetSimVarValue(`L:A32NX_ADIRS_KNOB_${this.number}`, 'Enum');
+
+        const startingAligned = this.knob === this.KNOB.NAV;
+        this.timer = startingAligned ? 0 : -1;
```
Comment (davidwalschots) [inline flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_ADIRS.js:25]: This is the actual fix. Previously this would always start with `-1` and therefore the alignment timer would run again. I'm not sure why _sometimes_ the issue didn't occur. That still baffles me 😀.

File: flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_ADIRS.js [hunk 2]
```diff
@@ -1,28 +1,34 @@
...
         this.timer = -1;
-        this.onBatTimer = 0; //start at 0 to prevent light from coming on when starting with ADIRS aligned
+
+        // Start at 0 to prevent light from coming on when starting with ADIRS aligned
+        this.onBatTimer = 0;
     }
 
     init() {
-        this.knob = SimVar.GetSimVarValue(`L:A32NX_ADIRS_KNOB_${this.num}`, 'Enum');
-        SimVar.SetSimVarValue(`L:A32NX_ADIRS_TIMER_${this.num}`, 'Seconds', -1);
```
Comment (davidwalschots) [inline flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_ADIRS.js:18]: As the `L:A32NX_ADIRS_TIMER...` was only used inside the ADIRU, I removed the simvar and just keep it local.

File: flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_ADIRS.js [hunk 3]
```diff
@@ -1,28 +1,34 @@
...
-        this.knob = -1;
+class ADIRU {
+    constructor(number) {
+        this.number = number;
+
+        this.KNOB = Object.freeze({
+            OFF: 0,
+            NAV: 1,
+            ATT: 2
+        });
```
Comment (tracernz) [inline flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_ADIRS.js:9]: 💯 I really hate code with magic numbers.

**Review by tracernz — APPROVED** [review]

**Comment by HPringles** [comment]
Quality Assurance Trainee Report

Object of testing: #4936 
Tier of Testing: 1
Date: 28/05/2020

Testing Process: 
- Tested Spawning in On Runway and on approach
- Observed that ADIRS were aligned for this
- Tested spawning in at a gate (Cold & Dark)
- Adirs was not aligned when starting cold and dark and aligned as normal when knobs placed into NAV position (after time).

Negatives: N/A
Testing Results: Passed

Conclusions: LGTM

**Comment by frankkopp** [comment]
Quality Assurance Tester Report

Discord: Cdr_Maverick#6475
Object of testing: #4936
Tier of Testing: 1
Date: 28.52021

Testing Process:
Spawned c&d at gate: ADIRS aligned OK
Spawned runway 2x: ADIRS aligned OK
Spawned in air for approach  2x:  ADIRS aligned OK
Spawned mid air 2x: ADIRS aligned OK

Negatives: None
Testing Results: Passed
Conclusions: LGTM
