### PR TITLE
fix(rmp): RMP behaviour and lights

### LINKED ISSUE #164: Audio Control Panel lighting
ACP audio and transmittion lights cannot be selected simultaneously for the same radio. IE: VHF1 selected transmitting, VHF2 receiving, switching to VHF2 to transmit deselects VHF2 audio knob.

### LINKED ISSUE #344: Radio control panel is reverse with comms selected
**Describe the bug**
When "Call" button over the VHF1 knob is selected, the VHF2 knob is in use. When "Call" button above VHF2 knob is selected, VHF1 is in use.

**To Reproduce**
Press the Call button above VHF1, you will notice if you try to click on the VHF1 knob to use that it will not work, but the VHF1 knob is able to be used, and vice verse

**Expected behavior**
You should be able to select VHF1 and the "Call" button above it and not have any issues, same goes with VHF2 and the "call" button above that.

**Screenshots or Videos**
https://imgur.com/mZ5ED9U
https://imgur.com/YBv2xjX

### LINKED ISSUE #4591: SEL light on RMP comes on without a cause
**Aircraft Version**
{
  "built": "2021-04-23T22:37:56+00:00",
  "ref": "experimental",
  "sha": "c43d0267084cae66e5cb3950c1c76e9b78bf43d0",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**
The SEL lights of CPT and F/O RMP don't work properly when VHF3 is selected.

**To Reproduce**
Select VHF 3 on CPT or F/O RMP.

**Expected behavior**
The SEL light should only come on on the RMP that has selected another xceifer than its own and on the RMP whose xceiver is being accessed by another RMP. So if I select VHF2 on RMP1 the SEL light on RMP 1 and 2 will come on.

But when I select VHF3 on RMP1 the SEL light on the RMP1 shall come on only. Not the one of RMP2 which controls its own xceifer.

**Actual behavior**
The SEL light comes on on RMP1 and 2 when VHF3 is selected. 

**References**
N/A

**Additional context**
N/A

Was this working before/when did the issue start occurring?
UNKNOWN
Is this a problem in the vanilla unmodded game?
UNKNOWN

Discord username (if different from GitHub):

### LINKED ISSUE #5033: Audio Knob pushing itself down when respective MIC is selected
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-06T15:12:39+00:00",
  "ref": "master",
  "sha": "ff9425ae19d607662e1e8adb6732dd0509aacb9f",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

[ACP/RMP]

- SEL light lights up green

- Whenever I press the microphone button, it presses back the volume knob corresponding to that microphone.

### Expected behavior

- SEL light is amber, and it lights up the whole "key".

- Selecting a microphone shouldn't have any influence on the volume knobs.

### Steps to reproduce

1. Pop the VHF2 volume knob.
2. Press the VHF2 microphone.
3. The volume knob will push itself back in, that's not supposed to happen by no means.

### References (optional)

vhf

### Additional info (optional)

_No response_

### Discord Username (optional)

Illuminati

### PR DESCRIPTION
**Pull request by juliansebline**
Fixes #344 
Fixes #164
Fixes #5033
Fixes #4591

## Summary of Changes
This commit fixes the RMPs/ACPs's behaviour (VHFs only), their electrical power and add VHF 3 voice/data mode.

## Screenshots (if necessary)
image
image

image
image

## References
image
image

## Additional context
 Thanks shomas#2719 for the pîctures in the real aircraft!

My discord: Julian Sebline#8476

## Testing instructions

**Keep in mind both RMPs and ACPs are independent**

1. Open SimvarWatcher and load the config file found in the last comment.
2. At startup:
   - [ ] CALL1 should be active on both sides
   - [ ] VHF1/2 volumes knobs should be on with values 0.8 and 0.4 (respectively)
   - [ ] Left RMP should be set with VHF1
   - [ ] Right RMP should be set with VHF2
   - [ ] Respective SEL light should not be lit
   - [ ] Simvars RECEIVE ALL and RECIEVE ALL should be set to 1 (for vPilot)
3. On the left RMP, press VHF2 then VHF3
   - [ ] The left SEL led AND word should lit in orange on both sides
   - [ ] Back to VHF1, the lights should go off
4. On the right RMP, press VHF1 then VHF3
   - [ ] The right SEL led AND word should lit in orange on both sides
   - [ ] Back to VHF2, the lights should go off
5. On both sides, press VHF1/2/3 volume knobs
   - [ ] Each knob should turn on/off independently
   - [ ] All knobs can be on/off
   - [ ] Respective simvar should be set to 1 IF at least one knob of each side is on
   - [ ] Respective simvar should be set to 0 IF each knob of each side is off
   - [ ] When off, rotate a knob should be harder (to simulate real behaviour)
6. On both sides, rotate VHF1/2/3 volume knobs
   - [ ] Each knob should rotate independently
   - [ ] Respective simvar should be set to the greatest value of both knobs
7. Turn off all volumes knobs
   - [ ] Rotate them should not update their respective simvar
   - [ ] Turn them on, the simvar should be updated with the value of the knob OR the max value between the two knobs if both on
8. On both sides, turn OFF all CALL (related to VHFs) push buttons
   - [ ] Their respective light is off
   - [ ] The simvars COM TRANSMIT are set to 0
   - [ ] The simvars PILOT/COPILOT TRANSMITTER TYPE are set to 4 (None)
9. On both sides, turn ON all CALL (related to VHFs) push buttons
   - [ ] It's NOT possible to have two or more CALL push button active on one RMP
   - [ ] The simvars PILOT/COPILOT TRANSMITTER TYPE are set to 0 for COM1, 1 for COM2, 2 for COM3
   - [ ] The respective simvars COM TRANSMIT are set to 1 if at least one of the respective push buttons is on
10. Push VHF3 on each RMP
    - [ ] The word DATA should appear centered in the active window
    - [ ] A frequency should appear in the standby window
11. Push the transfer key
    - [ ] The text "_VHF 3 VOICE_" should appear on the ECAM (the underlying logic is not implemented yet)
    - [ ] Push the transfer key once gain, the message should disappear
12. Rotate the knobs to change a frequency
    - [ ] Frequency decimal can now return to 0 after .975 even if the integer is 136 (tested irl)

For this part, refer to [this link](http://www.pmgasser.ch/airbus_memos/downloads/A320_ELEC.pdf)

It is very likely points 12 and 13 fail the test. I have just realized I did not implement the "unusable mechanism". I will implement it in the second PR even though I don't know how it is in real life. I will make the frequency windows blank and knobs off.

13. Disconnect DC BUS 1 and AC BUS 1
    - [ ] VHF 3 (knob and push button) should be unusable
14. Disconnect DC BUS 2 and AC BUS 2
    - [ ] VHF 2 (knob and push button) should be unusable
    - [ ] RMP 2 should be unusable

At this point, only VHF 1, RMP 1 and both ACPs should be usable. Engines, APU, GPU off.

15. Disconnect DC ESS BUS and AC ESS BUS
    - [ ] Everything should be unusable

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

File: src/instruments/src/EWD/elements/PseudoFWC.tsx [hunk 1]
```diff
@@ -1349,6 +1351,17 @@ const PseudoFWC: React.FC = () => {
             sysPage: -1,
             side: 'RIGHT',
         },
+        '0000690': // VHF 3 VOICE
+        {
+            flightPhaseInhib: [],
+            simVarIsActive: voiceVHF3 !== 0,
```
Comment (beheh) [inline src/instruments/src/EWD/elements/PseudoFWC.tsx:1357]: This memo should only appear in certain flight phases.

```suggestion
            simVarIsActive: voiceVHF3 !== 0 && [1, 2, 6, 9, 10].includes(flightPhase),
```

**Review by beheh — CHANGES_REQUESTED** [review]

File: src/instruments/src/EWD/elements/PseudoFWC.tsx (hunk 1 above)
Comment (tracernz) [reply src/instruments/src/EWD/elements/PseudoFWC.tsx:1357]: Shouldn't that go in `flightPhaseInhib`?

**Comment by juliansebline** [comment]
Thank you for your comment/

Would you have the precise list of phases affected ? I cannot find it on the internet. I suppose CLB CRZ DESCENT ?

Thank you

De : Michael ***@***.***>
Envoyé le :mercredi 27 avril 2022 00:46
À : ***@***.***>
Cc : Julian ***@***.***>; ***@***.***>
Objet :Re: [flybywiresim/a32nx] fix(rmp): RMP behavior and lights (PR #7105)


@tracernz commented on this pull request.


In src/instruments/src/EWD/elements/PseudoFWC.tsx<https://github.com/flybywiresim/a32nx/pull/7105#discussion_r859204881>:

> @@ -1349,6 +1351,17 @@ const PseudoFWC: React.FC = () => {

             sysPage: -1,

             side: 'RIGHT',

         },

+        '0000690': // VHF 3 VOICE

+        {

+            flightPhaseInhib: [],

+            simVarIsActive: voiceVHF3 !== 0,

Shouldn't that go in flightPhaseInhib?

File: src/instruments/src/EWD/elements/PseudoFWC.tsx (hunk 1 above)
Comment (beheh) [reply src/instruments/src/EWD/elements/PseudoFWC.tsx:1357]: > Shouldn't that go in flightPhaseInhib?

No - inhibit can be overridden by pressing recall during the inhibited flight phases (although not sure that even applies to memos).

**Comment by tracernz** [comment]
> Thank you for your comment/ Would you have the precise list of phases affected ? I cannot find it on the internet. I suppose CLB CRZ DESCENT ?

BehEh provided the code above.

File: src/instruments/src/RMP/Components/RadioPanelDisplay.tsx [hunk 2]
```diff
@@ -23,12 +25,25 @@ const formatFrequency = (frequency: number): string => (frequency / 1000000).toF
...
+        if (props.value !== 0) {
+            value = formatFrequency(props.value);
+        }
+    } else {
+        value = props.value;
+    }
+
+    if (props.value === 0) {
+        offsetx = '85%';
+    }
```
Comment (beheh) [inline src/instruments/src/RMP/Components/RadioPanelDisplay.tsx:42]: This entire component feels a bit messy now. I expect one bug for example to be that if you're in data mode AND enable lights test, offsetx may be incorrectly at 85%.

How about something more like this:

```typescript
interface Props {
    vale: string | number;
    dataMode?: boolean;
}
```

```typescript
if (lightsTest) {
  content =  (
    <text x={offsetx} y="52%">
      8.8.8.8.8.8
    </text>
  );
}
else if (props.dataMode) {
  content =  (
    <text x="85%" y="52%">
     DATA
    </text>
  );
}
else {
  content =  (
    <text x="100%" y="52%">
     {value}
    </text>
  );
}
return  (
  <svg className="rmp-svg">
    {content}
  </svg>
);
```

**Review by beheh — CHANGES_REQUESTED** [review]

File: src/instruments/src/RMP/Components/RadioPanelDisplay.tsx [hunk 3]
```diff
@@ -8,6 +8,8 @@ interface Props {
     value: number | string,
 }
 
+const textDataModeVHF3 = 'DATA';
```
[the remark this answers is not in the document]
Comment (juliansebline) [reply src/instruments/src/RMP/Components/RadioPanelDisplay.tsx]: Commited

File: src/instruments/src/RMP/Components/RadioPanelDisplay.tsx (hunk 2 above)
Comment (juliansebline) [reply src/instruments/src/RMP/Components/RadioPanelDisplay.tsx]: I'm gonna ask Shomas if he can check the behavior in the real airplane

File: src/instruments/src/RMP/Components/StandbyFrequency.tsx [hunk 4]
```diff
@@ -103,29 +103,40 @@ export const StandbyFrequency = (props: Props) => {
...
     }, [props.value]);
 
     // Handle inner knob turned.
     const innerKnobUpdateCallback: UpdateValueCallback = useCallback((offset) => {
         const frequency = Math.round(props.value / 1000);
-        if (Math.sign(offset) === 1 && frequency === 136975) {
-            return;
+        // if (Math.sign(offset) === 1 && frequency === 136975) {
+        //     return;
+        // }
```
[the remark this answers is not in the document]
Comment (juliansebline) [reply src/instruments/src/RMP/Components/StandbyFrequency.tsx:124]: These lines can be deleted.

Because it prevents the decimal value to go beyond 975 if the integer is 136. In real life, there is no such thing. The outer knob is blocked at 136 but the inner one can go to 0. There is a comment line 132.

File: flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/AirlinerCommon.xml [hunk 5]
```diff
@@ -430,7 +431,7 @@
                     <FREQUENCY>3</FREQUENCY>
                     <UPDATE_CODE>
                     (A:COM TRANSMIT:#Radio_ID#, Bool) if{
-                        #Button_ID# (&gt;L:XMLVAR_COM_Transmit_Channel)
+                        <!-- #Button_ID# (&gt;L:XMLVAR_COM_PANEL#ID#_Transmit_Channel) -->
```
[the remark this answers is not in the document]
Comment (juliansebline) [reply flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/AirlinerCommon.xml:434]: I was not able to spot the purpose for these lines of code. To me, it was part of all the problems. 

Thefore, just in case for the future, I left the condition only.

File: .github/CHANGELOG.md [hunk 6]
```diff
@@ -1054,3 +1054,4 @@
 1. [CDU] Full +/- button functionality - @lhoenig (Lukas Hoenig)
 1. [DCDU] Fixed MSG- and MSG+ button labels - @tyler58546 (tyler58546)
 1. [OVHD] Fixed fire push button not being able to be stowed - Julian Sebline (Julian Sebline#8476 on Discord)
+1. [RMP] Fixed the behavior of the RMPs and ACPs (VHFs only) - Julian Sebline (Julian Sebline#8476 on Discord)
```
Comment (beheh) [inline .github/CHANGELOG.md:1057]: This is the wrong place for this (you've added it to the Changelog of 0.4.0). Changelog entries need to go to the end of the first section of the unreleased next version - in this case you should add it to the 0.9.0 section.

**Review by beheh — CHANGES_REQUESTED** [review]

**Review by 2hwk — APPROVED** [review]

**Comment by mico975** [comment]
Quality Assurance Tester Report

Discord          : mico#3145
Object of testing: (#7105
Tier of Testing  : 1
Date             : 08/08/2022

Testing Process: 

At startup:
 CALL1 should be active on both sides - **OK**
 VHF1/2 volumes knobs should be on with values 0.8 and 0.4 (respectively) - **OK**
 Left RMP should be set with VHF1 - **OK**
 Right RMP should be set with VHF2 - **OK**
 Respective SEL light should not be lit - **OK**
 Simvars RECEIVE ALL and RECIEVE ALL should be set to 1 (for vPilot) - **OK**

On the left RMP, press VHF2 then VHF3
 The left SEL led AND word should lit in orange on both sides - **OK**
 Back to VHF1, the lights should go off - **OK**

On the right RMP, press VHF1 then VHF3
 The right SEL led AND word should lit in orange on both sides - **OK**
 Back to VHF2, the lights should go off - **OK**

On both sides, press VHF1/2/3 volume knobs
 Each knob should turn on/off independently - **OK**
 All knobs can be on/off - **OK**
 Respective simvar should be set to 1 IF at least one knob of each side is on - **OK**
 Respective simvar should be set to 0 IF each knob of each side is off - **OK**
 When off, rotate a knob should be harder (to simulate real behaviour) - **OK**

On both sides, rotate VHF1/2/3 volume knobs
 Each knob should rotate independently - **OK**
 Respective simvar should be set to the greatest value of both knobs - **OK**

Turn off all volumes knobs
 Rotate them should not update their respective simvar - **OK**
 Turn them on, the simvar should be updated with the value of the knob OR the max value between the two knobs if both on - **OK**

On both sides, turn OFF all CALL (related to VHFs) push buttons
 Their respective light is off - **OK**
 The simvars COM TRANSMIT are set to 0 - **OK**
 The simvars PILOT/COPILOT TRANSMITTER TYPE are set to 4 (None) - **OK**

On both sides, turn ON all CALL (related to VHFs) push buttons
 It's NOT possible to have two or more CALL push button active on one RMP - **OK**
 The simvars PILOT/COPILOT TRANSMITTER TYPE are set to 0 for COM1, 1 for COM2, 3 for COM3 - **OK**
 The respective simvars COM TRANSMIT are set to 1 if at least one of the respective push buttons is on - **NOT OK**, this get's messed up. I.e. RMP2 CALL3 -> RMP1 CALL2 -> result is active COM TRANSMIT 1+2 instead of 2+3.

Push VHF3 on each RMP
 The word DATA should appear centered in the active window - **OK**
 A frequency should appear in the standby window - **OK**

Push the transfer key
 The text "VHF 3 VOICE" should appear on the ECAM (the underlying logic is not implemented yet) - **OK**
 Push the transfer key once gain, the message should disappear - **OK**

Rotate the knobs to change a frequency
 Frequency decimal can now return to 0 after .975 even if the integer is 136 (tested irl) - **OK**

Disconnect DC BUS 1 and AC BUS 1 - **not tested**
 VHF 3 (knob and push button) should be unusable 

Disconnect DC BUS 2 and AC BUS 2 - **not tested**
 VHF 2 (knob and push button) should be unusable
 RMP 2 should be unusable
At this point, only VHF 1, RMP 1 and both ACPs should be usable. Engines, APU, GPU off.

Disconnect DC ESS BUS and AC ESS BUS - **not tested**
 Everything should be unusable

Negatives:       
See above in testing process

Testing Results: 
Not Passed

Conclusions: 
None atm.

**Comment by juliansebline** [comment]
> 2+3

This is fine. It was my mistake in the test plan. The index starts at 0 for COM1 within the SDK. There's no problem

**Comment by 2hwk** [comment]
Disconnect DC BUS 1 and AC BUS 1 
-[x] VHF 3 (knob and push button) should be unusable

Disconnect DC BUS 2 and AC BUS 2 - not tested
-[x] VHF 2 (knob and push button) should be unusable
-[x] RMP 2 should be unusable
- [x] At this point, only VHF 1, RMP 1 and both ACPs should be usable. Engines, APU, GPU off.

Disconnect DC ESS BUS and AC ESS BUS
- [x] Everything should be unusable

Remaining items passed
