### PR TITLE
fix: ND flight plan removed from ROSE VOR/ILS

### LINKED ISSUE #841: [BUG] ND ILS mode
**Mod Version**

Master, latest one

**Describe the bug**

showing the route in the ND ILS mode 

**To Reproduce**

1. Enter a route in the MCDU 
2. switch ND mode to ILS

**Expected behavior**

 the route must be disappeared on ILS mode plus the ILS bar should be filled not empty 

**Actual behavior**

showing the route in the ND ILS mode 
**References**

Desktop Screenshot 2020 09 24 - 16 18 58 01

**Additional context**

tarek_sabet#7946 (if different from GitHub):

### PR DESCRIPTION
**Pull request by 2hwk**
Fixes #841 #842

## Summary of Changes

- [x] Flight plan removed from ROSE ILS/VOR mfd modes
   - [x] CSTR visual elements and ToD/ToC removed when modes switched
- [x] Minor fix for masking of ND elements

## Screenshots (if necessary)

image
image

## References

#841 

## Additional context

Discord username (if different from GitHub): 2Cas#1022

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

**Review by Benjozork — COMMENTED** [review]
LGTM

**Review by Benjozork — APPROVED** [review]

**Comment by Lazarus320** [comment]
Category: QA Tester
Name: Lazarus#4286
Date of testing: 20/12/2020
Version of the sim: 1.11.7.0
PR Tested: #2555 
Object of test: ND flight plan removed from ROSE VOR/ILS

Testing technique: Did a short flight and tested the ROSE ILS mode. 
Steps you've made to test the Pull Request:
1. Selected ROSE/ILS during approach.  
2. Monitored the mode behaviour all the way to touchdown.  



Flight notes (If required): N/A

Issues (If Any): The deviation line is overlapping with the AC position symbol 
Sim: 
image
IRL:
image

Overall Rating: To be improved 
Conclusions of the testing: Needs adjustment

**Comment by tareksabet** [comment]
also issue #842

**Comment by BritishAvgeek** [comment]
Category: QA Tester
Name: BritishAvgeek#1436
Date of testing: 20/12/2020
Version of the sim: 1.11.7.0
PR Tested: #2555 
Object of test: ND tweaks - flight plan removal from VOR and ILS ND modes

Testing technique: Full Flight - Paro to Kathmandu, turn around then back to Paro livestreamed on my channel
Steps you've made to test the Pull Request:
1. Spawned C&D
2. First headed from Paro to Kathmandu and used an RNAV approach but checking against the VOR data too on the charts and checking the rose anyway... no issues
3. Turnaround after landing at KTM - headed back to Paro
4. Checked systems multiple times for VOR - no issues
5. Noted the above issue Re: the a/c displaying UNDER the ILS ND mode... I didn't have an ILS approach involved but checked the ILS mode myself and did not have that issue though did not have an ILS localiser active for this test

Flight notes (If required): N/A but if you try the route yourself, be warned that the in-sim navigraph nav data is very wrong on both airports!

Issues (If Any): 
Overall Rating: Good
Conclusions of the testing: Everything I tested worked fine - though did not try with any active ILS approach but noted the issued raised in the above test by Lazarus

**Comment by lukecologne** [comment]
This issue is not caused by the PR. If you want you can fix it ofc @2hwk

File: A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/A32NX_MapInstrument.js [hunk 1]
```diff
@@ -259,6 +259,9 @@ class MapInstrument extends ISvgMapRootElement {
                 this.showFlightPlan = true;
                 this.updateFlightPlanVisibility();
             }
+            if (newValue == "false") {
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/A32NX_MapInstrument.js:262]: can we make this a Boolean instead of a string? By the looks of it it seams very obvious, but haven't looked at the entire code.

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js [hunk 2]
```diff
@@ -447,14 +450,34 @@ class A320_Neo_MFD_MainPage extends NavSystemPage {
...
+            this.showFlightPlan = flightPlan;
+            this.map.instrument.attributeChangedCallback("show-flightplan", null, flightPlan ? "true" : "false");
+            if (!flightPlan) {
+                this.map.instrument.showConstraints = false;
+                this.map.removeTopOf();
+            } else {
+                const active = SimVar.GetSimVarValue("L:BTN_CSTR_" + this.screenIndex + "_FILTER_ACTIVE", "number");
+                console.log(active);
+                if (active) {
+                    this.map.instrument.showConstraints = true;
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js:465]: This is nip picking but why not swapping so that the true actually is true?

**Comment by tareksabet** [comment]
Name: tarek_sabet#7946
Date of testing: Current date /12/2020
Version of the sim: 1.11.7.0
PR Tested: #2555 
Object of test: Testing the route removal from ILS and VOR ND mode
Testing technique: Try-out (multiple tests)
 
## Steps you've made to test the Pull Request:
* Did two takeoffs and Landings
* first one ILS landing 
* Second one VOR landing 

## Overall Rating: Good but could be better 
#### Conclusions of the testing:
So it worked well and I love your work, but the aircraft position is wrong as mentioned above 
plus I don't know if related to your PR or not but I couldn't activate LOC mode from the FCU 

Desktop Screenshot 2020 12 21 - 15 31 38 59

Desktop Screenshot 2020 12 21 - 15 31 42 93

Also here some references of the two Modes if you want them : 

Desktop Screenshot 2020 12 21 - 16 31 12 65

Desktop Screenshot 2020 12 21 - 16 31 21 57

File: A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/A32NX_MapInstrument.js (hunk 1 above)
Comment (2hwk) [reply A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/A32NX_MapInstrument.js:262]: This is in line with the rest of the syntax on this page, so I am not inclined to change it.

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js (hunk 2 above)
Comment (2hwk) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js:465]: As it is right now I believe it is more readable and easier to understand. 

If a change occurs in flight plan visibility:
    If there is now no flight plan (off):
        remove CSTR and ToC/ToD from display
    If there is now a flight plan (on):
        only if CSTR is active:
            show constraints on display

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js [hunk 3]
```diff
@@ -447,14 +450,34 @@ class A320_Neo_MFD_MainPage extends NavSystemPage {
...
+    setFlightPlanVisibility(flightPlan) {
+        if (flightPlan != this.showFlightPlan) {
+            this.showFlightPlan = flightPlan;
+            this.map.instrument.attributeChangedCallback("show-flightplan", null, flightPlan ? "true" : "false");
+            if (!flightPlan) {
+                this.map.instrument.showConstraints = false;
+                this.map.removeTopOf();
+            } else {
+                const active = SimVar.GetSimVarValue("L:BTN_CSTR_" + this.screenIndex + "_FILTER_ACTIVE", "number");
+                console.log(active);
```
Comment (Benjozork) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js:463]: Remove `console.log` call

Comment (2hwk) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js:463]: This should be removed in the next commit when pushed

**Comment by 2hwk** [comment]
Issue noted by Lazarus is beyond the scope of this PR, I have investigated and taken to look to see if a fix can be included, but it's a bit more complicated to deal with, haven't had much luck fixing this without causing even worse visual bugs, would be probably be worthy of a PR on its own.
