### PR TITLE
fix(efb): rego setting

### LINKED ISSUE #7438: Dynamic registration decal not work.
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-08-26T09:51:11+00:00",
    "ref": "refs/heads/master",
    "sha": "e46e611d618036e7bca32c5652f4806834665d93",
    "actor": "frankkopp",
    "event_name": "manual",
    "pretty_release_name": "master:e46e611d"
}
```

### Describe the bug

I can't see now the tail number, before it did, I have set in customization airplane -> tail number: EC-ZAB and in flypad dynamic registration decal On.

### Expected behavior

Tail Number is showed in exterior aircraft in both the default library and my custom library, both of which worked correctly before.

### Steps to reproduce

1. Empty community folder except a32nx from installer/launcher
2. Launch sim, go to world
3. Select a32nx and select fbw livery
4. set in customization airplane -> tail number: EC-ZAB
5. In flypad dynamic registration decal On
6. Fly
7. Exterior camera

### References (optional)

imagen
unknown
unknown2
unknown3

### Here you can see how previously this worked:
imagen

### Additional info (optional)

I haven't flown this aircraft for about 5 months and I didn't notice this fault until today. Previously it was working. Other planes, both with default textures and with other textures I have created, work.
imagen

### Discord Username (optional)

Spark_23#2821

### PR DESCRIPTION
**Pull request by tracernz**
Fixes #7438 

## Summary of Changes

Fix registration decal setting broken by flyPadOSv3.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Spawn with FBW livery.
Turn Settings -> Sim Options -> Dynamic Registration Decal On, check the rego is displayed on the rear fuselage.
Turn the setting off and ensure rego is not displayed on rear fuselage.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

File: src/instruments/src/EFB/Settings/Pages/SimOptionsPage.tsx [hunk 1]
```diff
@@ -101,7 +101,7 @@ export const SimOptionsPage = () => {
                     </SettingItem>
 
                     <SettingItem name={t('Settings.SimOptions.DynamicRegistrationDecal')}>
-                        <Toggle value={dynamicRegistration === 'ENABLED'} onToggle={(value) => setDynamicRegistration(value ? 'ENABLED' : 'DISABLED')} />
+                        <Toggle value={dynamicRegistration === '1'} onToggle={(value) => setDynamicRegistration(value ? '1' : '0')} />
```
Comment (frankkopp) [inline src/instruments/src/EFB/Settings/Pages/SimOptionsPage.tsx:104]: Can you also change line 19 - should then also say '0'

**Review by frankkopp — APPROVED** [review]

**Comment by 2hwk** [comment]
QA Report

Discord: 2Cas#1022
Object of testing: #7444
Tier of Testing: 1
Date: 28/08/2022

Testing Process: 
- [x] Spawn with FBW livery.
- [x] Turn Settings -> Sim Options -> Dynamic Registration Decal On, check the rego is displayed on the rear fuselage.
- [x] Turn the setting off and ensure rego is not displayed on rear fuselage.

Negatives: N/A

Testing Results: Passed

Conclusions: LGTM
