### PR TITLE
[ND] Add altitude constraint in flight level (FL) after transition altitude

### LINKED ISSUE #1733: [BUG] Some altitude constraints on the navigation display show in feet instead of flight level, even above transition altitude
**Mod Version**

Master

**Describe the bug**

Some altitude constraints on the navigation display show in feet instead of flight level, even above transition altitude.

image

**To Reproduce**

1. Fly high-altitude IFR flight plan with SID and STAR. Try making changes to SID/STAR or the transition waypoints, as well.

**Expected behavior**

Should display "FL200" next to waypoint.

**Actual behavior**

Displays "20000" next to waypoint

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub): Iceman#5540

### PR DESCRIPTION
**Pull request by ilyeshammadi**
Fixes #1733

## Summary of Changes

- Fix the attitude being shown without FL after 10000 feet in the navigation display
- Refactor the wrong usage of **SimVar** `L:AIRLINER_TRANS_ALT`, this was set to **V2** and it should be set to **Transition 
Altitude**
- Change the color of the altitude and speed constraints to #ff94ff (Magenta waypoint circle not included in this PR)

### Before
97951050-e32a4500-1d66-11eb-9c22-54611f3d8308

### After
Screenshot (39)

### V2 Speed untouched
Screenshot 2020-11-09 014528
 

## Additional context

Discord username (if different from GitHub): Union Araken#4083

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

File: A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_SvgConstraintElement.js [hunk 1]
```diff
@@ -0,0 +1,61 @@
+class A32NXSvgConstraintElement extends SvgConstraintElement {
+    createDraw(map) {
```
Comment (ilyeshammadi) [inline A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_SvgConstraintElement.js:2]: I've tried to override this function to avoid duplicate code but in the end, found out that the code was almost the same.

File: A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_SvgConstraintElement.js [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+        const fontSize = map.config.waypointLabelFontSize;
+        let text = "CSTR";
+        let speedText = "";
+        if (this.source) {
+            if (this.source.legAltitude1 >= 10000) {
+                text = "FL" + (this.source.legAltitude1 / 100).toFixed(0);
```
Comment (davidwalschots) [inline A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_SvgConstraintElement.js:8]: You should take into account the transition altitude. When the constraint is above the transition altitude, output `FLxxx`.

Comment (ilyeshammadi) [reply A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_SvgConstraintElement.js:8]: Thanks for the feedback, I'm pretty new to aviation, can you please explain the rule that needs to follow in order to output FL100 instead of 10000 feet for example?
So If I understand correctly FL is tied to the transition altitude? if we're below transition altitude we need to show 12000 feet instead of FL120 for a transition altitude of 18000?

Comment (davidwalschots) [reply A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_SvgConstraintElement.js:8]: Please read [this article](https://www.skybrary.aero/index.php/Transition_Altitude/Level) to learn about transition altitude and transition level. Your understanding is correct. At or below the transition altitude, all altitudes are fully written out (or communicated when talking to ATC). Above the transition altitude flight level is used.

File: A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_SvgConstraintElement.js [hunk 3]
```diff
@@ -0,0 +1,61 @@
...
+            const canvas = document.createElement("canvas");
+            canvas.setAttribute("width", (this._textWidth + map.config.waypointLabelBackgroundPaddingLeft + map.config.waypointLabelBackgroundPaddingRight).toFixed(0) + "px");
+            canvas.setAttribute("height", (this._textHeight * (this.source.speedConstraint > 0 ? 2.2 : 1) + map.config.waypointLabelBackgroundPaddingTop + map.config.waypointLabelBackgroundPaddingBottom).toFixed(0) + "px");
+            this._label.appendChild(canvas);
+            const context = canvas.getContext("2d");
+            if (map.config.waypointLabelUseBackground) {
+                context.fillStyle = "black";
+                context.fillRect(0, 0, this._textWidth + map.config.waypointLabelBackgroundPaddingLeft + map.config.waypointLabelBackgroundPaddingRight, this._textHeight + map.config.waypointLabelBackgroundPaddingTop + map.config.waypointLabelBackgroundPaddingBottom);
+            }
+            context.fillStyle = "magenta";
```
Comment (MisterChocker) [inline A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_SvgConstraintElement.js:44]: if possible, use the color `--displayMagenta: #ff94ff` instead, can be found in the display common.css.

**Review by MisterChocker — CHANGES_REQUESTED** [review]

File: A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_SvgConstraintElement.js (hunk 3 above)
Comment (ilyeshammadi) [reply A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_SvgConstraintElement.js:44]: Will do thanks

File: A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_SvgConstraintElement.js (hunk 2 above)
Comment (ilyeshammadi) [reply A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_SvgConstraintElement.js:15]: Should be taking Transition Altitude into account now, thanks for the feedback 😄

File: A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_SvgConstraintElement.js (hunk 3 above)
Comment (ilyeshammadi) [reply A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_SvgConstraintElement.js]: @MisterChocker I've changed the color to `#ff94ff` but the numbers now are very hard to read since that color is less vivid, is it this color that is used in the real A320?

File: A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_SvgConstraintElement.js (hunk 2 above)
Comment (davidwalschots) [reply A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_SvgConstraintElement.js:15]: Getting there! All that's left is getting the SimVar value using `SimVar.GetSimVarValue`, as the transition altitude can be changed via the MCDU.

Comment (ilyeshammadi) [reply A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_SvgConstraintElement.js:15]: Already done in [here](https://github.com/flybywiresim/a32nx/pull/1812/files#diff-85c33a591b07d9a6297dea2ce064f26463ed1e8fee48aaf14a646dd33ec39046R518)

File: .github/CHANGELOG.md [hunk 4]
```diff
@@ -60,8 +60,12 @@
 1. [TEXTURES] upgraded to 4k Textures (pedestal,throttle unit) fixed decal texture - @Pleasure0102 (Pleasure)
 1. [PFD] Added FMAs ALT CST and ALT CST* as well as CLB magenta and DES or CLB blue - @MisterChocker (Leon)
 1. [CDU] Added CFDS display test, ATSU METAR/TAF/ATIS requests, and ATSU free text - @wpine215 (Iceman), @nistei (Nistei), @Edwin B
+<<<<<<< HEAD
+1. [ND] Added altitude constraints in flight level based on the transition altitude provided in MCDU Take Off Performace @ilyeshammadi (Ilyes)
+=======
 1. [ECAM] Improve flaps/slats panel design on upper ECAM, improve flaps/slats transition logic - @paul92ilm (Lussion)
 1. [CDU] Allow inserting landing QNH in inHg - @pessip (Pessi Päivärinne)
+>>>>>>> master
```
Comment (Benjozork) [inline .github/CHANGELOG.md:68]: Please resolve conflicts by removing lines 63, 65 and 68 :)

**Review by Benjozork — CHANGES_REQUESTED** [review]

File: .github/CHANGELOG.md (hunk 4 above)
Comment (ilyeshammadi) [reply .github/CHANGELOG.md]: Conflict resolved, thank you.

**Review by Benjozork — APPROVED** [review]
LGTM

**Comment by danbw9** [comment]
Name: danbw9#17028
Date of testing: 11/11/2020
Version of the sim: 1.10.11.0
PR Tested: #1812 
Object of test: Checking out the corrected FL constraint after transition altitude + colours

Testing technique: Checked out previous behaviour before PR installed and tried at two airports (EKCH and OMDB) - to compare with. 3-4 SIDs per where the SIDs have flight level and speed constraints included. 

Loaded up C&D in OMDB as if doing normal flight. Selected for example KUTLI4F off 30L in OMDB. Transition altitude is 10,000 feet. Final climb constraint on the SID is KUTLI @ FL160. Works as described. 

Just check the colours as on my side they were not consistent, specifically the ring around the waypoint. 

Double checked V2 when selected was displayed correctly and no changes there. 

Issues (If Any): Functionality correct, just a colour irregularity. 
Overall Rating: Good
Conclusions of the testing: LGTM. A cool detail which helps a lot with visual accuracy. I did notice that it and not the transition altitude based from the PERF TO page. I tried changing the transition altitude in PERF page and it did not affect anything. So if the transition altitude for a given airport/area is wrong in the database and needed to be edited it may not work. 
Also my magenta shades on the ND are not consistent. See screenshot below. And colours do not match with the the 'AFTER' screenshot in the references. Thanks for your work!

Screenshot (691)

**Comment by ilyeshammadi** [comment]
@danbw9 Thank you for the wonderful testing, indeed the ring does not have that new color (#ff94ff) since this PR focuses on the constraint speed and altitude.

File: A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_SvgConstraintElement.js [hunk 5]
```diff
@@ -0,0 +1,68 @@
+class A32NXSvgConstraintElement extends SvgConstraintElement {
```
Comment (lukecologne) [inline A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_SvgConstraintElement.js:1]: Should we really extend the SvgConstraintElement? IMO it would be better just copying the original asobo file, renaming it, and then do your changes in there, especially since we are trying to hard fork, where we would need to copy this file anyways. @Benjozork What do you think?

Comment (ilyeshammadi) [reply A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_SvgConstraintElement.js:1]: Well, I went in that direction first, but thought maybe extending is better since Asobo can add more things to the original class. But if we're talking a hard fork then It makes sense to just copy paste and add what we need.

Comment (Benjozork) [reply A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_SvgConstraintElement.js:1]: I think it would be preferable in this case to copy over the original file.

Comment (ilyeshammadi) [reply A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_SvgConstraintElement.js]: Done

**Comment by tareksabet** [comment]
before merging this PR and as you worked on the ALT Constrains can you check issue #938 and tell if you can fix it ?

**Comment by ilyeshammadi** [comment]
> @ilyeshammadi before merging this PR and as you worked on the ALT Constrains can you check issue #938 and tell if you can fix it ?

I need a reference to a document /video from the real world a320 that describes this behaviour and please something from the real world, not from another sim.

**Comment by ImenesFBW** [comment]
> > @ilyeshammadi before merging this PR and as you worked on the ALT Constrains can you check issue #938 and tell if you can fix it ?
> 
> I need a reference to a document /video from the real world a320 that describes this behaviour and please something from the real world, not from another sim.

Tarek is a IRL pilot I would listen to his feedback.

**Comment by tareksabet** [comment]
> > @ilyeshammadi before merging this PR and as you worked on the ALT Constrains can you check issue #938 and tell if you can fix it ?
> 
> 
> 
> I need a reference to a document /video from the real world a320 that describes this behaviour and please something from the real world, not from another sim.

image
image
This is all I have from my FCOM

**Comment by ilyeshammadi** [comment]
@tareksabet thank you, I will keep this issue in mind and plan it for another PR.

**Review by Carter633 — APPROVED** [review]
Name: British Avgeek UTube -- Carter633 #1436
Date of testing: Current date 15/11/2020
Version of the sim: 1.10.11.0
PR Tested: #1812
Object of test: Test new FL constraint functionality

Testing technique: Full Flight on VATSIM
Steps you've made to test the Pull Request:
1. Spawn cold and dark
2. Full MCDU input/setup - depart Innsbruck
3. Amended constraints prior to STAR to plan a smooth descent and to test functions

Flight notes
Full flight from LOWI to EGKK on VATSIM - livestreamed on youtube - no issues, all worked well and as expected!

Issues (If Any): None
Overall Rating: Good
Conclusions of the testing: Everything worked as expected - constraints showed on ND as FL nicely - great work

**Comment by ilyeshammadi** [comment]
@Carter633 thank you for testing this PR 😄
