### PR TITLE
bugfix/feat: DCDU buttons

### LINKED ISSUE #1311: [BUG] DCDU power state inconsistency
**Mod Version**

9ee9d033d792a3573db97e308cc5ebc4935f75bb

**Describe the bug**

Cutting power does not power off the DCDU

**To Reproduce**

Quickly cut off all the power

**Expected behavior**

DCDU goes dark, like the rest of the cockpit

**Actual behavior**

DCDU shows 30 second test, then back into normal mode.

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub): devsnek#0001

### LINKED ISSUE #1324: [BUG] DCDU Labels are Missing/Off when brightness knob is turned to 0
**Mod Version**

master

**Describe the bug**

DCDU buttons appear to be missing text.

**To Reproduce**

1. Load in to the A320
2. Turn integ lt knob to 0
3. The emissive textures on the buttons now appear to be missing.

image

**Expected behavior**

Labels should not disappear when brightness is turned down

**Actual behavior**

Labels disappear

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub): 2Cas#1022

### PR DESCRIPTION
**Pull request by lukecologne**
Fixes #1324 and Fixes #1311

## Summary of Changes

* The DCDU button labels no longer disappear when the integrated lighting is off
* The DCDU buttons now have sounds
* The DCDU buttons now have working animations
* The DCDU brightness switch now works as expected
* The DCDU buttons now use H events instead of LVars.
* The DCDU now powers off as expected

## Additional context

* If the brightness change is too slow, let me know and I will increase it

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Com/A320_Neo_Com.js [hunk 1]
```diff
@@ -44,16 +44,24 @@ class A320_Neo_Com extends BaseAirliners {
     }
 
     onInteractionEvent(_args) {
+        const eventString = String(_args);
+        const searchString = "DCDU_BTN_";
+        const index = eventString.indexOf(searchString);
+        if (index !== -1) {
+            const event = eventString.substring(index + searchString.length);
+            console.log("DCDU event captured: " + event);
```
Comment (Benjozork) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Com/A320_Neo_Com.js:52]: Remove `console.log` for performance

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Com/A320_Neo_Com.js [hunk 2]
```diff
@@ -85,24 +93,12 @@ class A320_Neo_Com extends BaseAirliners {
...
-            setTimeout(() => {
-                this.view.inopWrapper.style.visibility = "hidden";
-
-                SimVar.SetSimVarValue("L:A32NX_PANEL_DCDU_INOP_PUSHED", "Bool", 0);
-            }, INOP_SHOW_DURATION);
-        }
+        this.view.inopWrapper.style.visibility = "visible";
+        setTimeout(() => {
+            this.view.inopWrapper.style.visibility = "hidden";
+            SimVar.SetSimVarValue("L:A32NX_PANEL_DCDU_INOP_PUSHED", "Bool", 0);
```
Comment (Benjozork) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Com/A320_Neo_Com.js:100]: This can be removed now.

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Com/A320_Neo_Com.js (hunk 1 above)
Comment (lukecologne) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Com/A320_Neo_Com.js:52]: It's only called when you actually press a button. Shouldn't have an impact on performance

**Comment by camilo625** [comment]
Name: Camilo625 #5575
Date of testing: Current date 14/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1327 

Testing technique: Test on ground
Steps you've made to test the Pull Request:
1. Spawn C%D
2. Setup aircraft
3. Check DCDU

Overall Rating: Good
Conclusions of the testing: Looks nice, great work!

**Comment by ImenesFBW** [comment]
The DCDU stays on on only batteries 

Ca213pture


The rest is fine and working as documented.

**Comment by lukecologne** [comment]
> 
> 
> The DCDU stays on on only batteries

Fixed.

**Comment by lukecologne** [comment]
Wait, don't merge yet

**Comment by lukecologne** [comment]
Alright, good now.

**Comment by FlightSimmer7700** [comment]
need a test?

**Comment by Snapmatics** [comment]
> need a test?

Yes, fast!

**Comment by FlightSimmer7700** [comment]
Name: FlightSimmer7700#3468
Date of testing: Current date 14/10/20
Version of the sim: Version the tester uses 1.9.5
PR Tested: #1327

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Spawned at airport
2. looked at the dcdu
3. turned on the power
4.pressed buttons and listened for the sound
5.

Overall Rating: Good
Conclusions of the testing: Make a small descriptive to areas where it needs to be improved and recommendations.
All the animations and sounds look and sound good, Turns on with ground power and off when I take it off and leave only the battery
