### PR TITLE
Fix horizon

### LINKED ISSUE #126: The pitch lines do not match the horizon line on the PFD, they move independently as the aircraft changes attitude.
Microsoft Flight Simulator Screenshot 2020 08 25 - 20 00 18 42
Microsoft Flight Simulator Screenshot 2020 08 25 - 19 59 12 88
Microsoft Flight Simulator Screenshot 2020 08 25 - 19 59 35 10

### PR DESCRIPTION
**Pull request by 1Revenger1**
Fixes #126

**Summary of Changes**
Change the viewbox for the attitude lines to make horizon and attitude lines move with each other
Change the seperator between bottom and top horizon y and thickness to make it centered and match closer to an actual PFD
Reduce medium/short pitch line width to closer match actual PFD

**Screenshots (if necessary)**

**Before:**
image
image
image

**After:**
image
image
image

**Additional context**
For the line widths, I referenced these images from the reference photos channel in discord:
* https://cdn.discordapp.com/attachments/747724538095075369/748291724400656474/unknown.png
* https://cdn.discordapp.com/attachments/747724538095075369/748293186841215096/-pjZVGJfvHISJEI82UzqzRj4zo89kN764ulSC3_Dr0WnG4Uo8DptB7rXLQAt09P3Ahd67wxdnVphElO5qyPgvnbVxRJc6qMb3RNV.png
* https://cdn.discordapp.com/attachments/747724538095075369/748476271851339826/IMG_20200827_035643.jpg

### CODE REVIEW

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AttitudeIndicator.js [hunk 1]
```diff
@@ -1348,12 +1348,18 @@ class Jet_PFD_AttitudeIndicator extends HTMLElement {
         this.applyAttributes();
     }
     applyAttributes() {
+        let horizonHeight = 300;
+        let attitudeHeight = 250;
+        let horizonToAttitudeRatio = attitudeHeight / horizonHeight;
+        let deltaY = this.pitch * this.pitchAngleFactor * this.pitchGradFactor;
```
Comment (UncleClapton) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AttitudeIndicator.js:1354]: These could all be turned into constants since they aren't reassigned.

**Review by UncleClapton — CHANGES_REQUESTED** [review]

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AttitudeIndicator.js (hunk 1 above)
Comment (1Revenger1) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AttitudeIndicator.js]: `this.pitch` isn't a constant. I moved the others to above though in the constructor.

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AttitudeIndicator.js [hunk 2]
```diff
@@ -1348,12 +1352,15 @@ class Jet_PFD_AttitudeIndicator extends HTMLElement {
         this.applyAttributes();
     }
     applyAttributes() {
+        let deltaY = this.pitch * this.pitchAngleFactor * this.pitchGradFactor;
```
Comment (Benjozork) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AttitudeIndicator.js:1355]: Can be `const`.

Comment (1Revenger1) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AttitudeIndicator.js:1355]: oh, that's probably what @UncleClapton meant by making things constant - oops.

**Comment by ImenesFBW** [comment]
Competed a flight with it, seems to be working as described, will do some further testing. Thanks!

**Review by AdenFlorian — APPROVED** [review]
looks great, thanks!
