### PR TITLE
fix(displays): self-test no longer triggers when spawning in an in-flight state

### LINKED ISSUE #4940: Screen Self Tests run when spawning with engines running.
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-28T18:51:08+00:00",
  "ref": "master",
  "sha": "dbeb055429f12b7dc7e8a06def0ede2e720f6768",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

When spawning on the runway, the display self tests run, even though at this point the aircraft is fully configured for take-off. The issue is also present when starting on in the air

### Expected behavior

The displays should have already completed the self tests, and so therefore should immediately display the instruments etc. when spawning on the runway or in the air

### Steps to reproduce

1. Spawn on the runway or in the air (Not cold and dark)
2. In the cockpit, notice the displays run the self test routine

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

HPringles#7078

### PR DESCRIPTION
**Pull request by 2hwk**
Fixes #4940 

## Summary of Changes

Self-Test on main displays is no longer triggered when you load into an in-flight state.

For example, this fix covers scenarios such as:
- Loading in on the runway ready for take-off
- Loading in cruise
- Loading in landing at a runway
- Loading a saved flight (.pln/.flt)

## Additional context

Discord username (if different from GitHub): 2Cas#1022

## Testing instructions

For all the following scenarios:

- Loading in on the runway ready for take-off
- Loading in cruise
- Loading in landing at a runway
- Loading a saved flight (.pln/.flt)

Observe that self-test does not run when the plane is spawned. Turn the displays off for more than 10 seconds. Turn them back on. Self-test should run now. Turn the displays on and off (<10 seconds), the displays should not display self-test.

Now, load the plane in cold and dark on a gate. Displays should turn on and Self-Test should trigger after power is supplied (as before).

**Known Issues:**

~~Loading in a saved file when~~

~~1. the plane has been spawned at a gate in a cold and dark state~~
~~2. the plane is still on the ground~~
~~3. self-test has already been completed~~
~~4. displays are on~~

~~will still trigger self-test inconsistently on spawn, this depends on how fast the save file is loaded into the sim.~~

PFD Self-Test is broken in mid-flight, it will not run. This behaviour is not improved from master.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by davidwalschots — CHANGES_REQUESTED** [review]
As you're removing `A32NX_COLD_AND_DARK_SPAWN` usages, please remove all `A32NX_COLD_AND_DARK_SPAWN` mentioning, including those in the `*.flt`, `globals.js`, and `util.js`.

File: flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/DisplayUnit.js [hunk 1]
```diff
@@ -5,6 +5,7 @@ class DisplayUnit {
         this.isPowered = isPoweredFn;
         this.potentiometerId = potentiometerId;
 
+        this.systemsInit = Boolean(SimVar.GetSimVarValue('L:A32NX_COLD_AND_DARK_SPAWN', 'Bool') && SimVar.GetSimVarValue('L:A32NX_FMGC_FLIGHT_PHASE', 'Enum') === (FmgcFlightPhases.PREFLIGHT));
```
Comment (davidwalschots) [inline flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/DisplayUnit.js:8]: **issue**: `systemsInit` not descriptive.
**issue**: Lots of additional code for what can be a change to the expression setting `this.offDurationInMilliseconds`.

```suggestion
        const initialisingColdAndDark = SimVar.GetSimVarValue('L:A32NX_COLD_AND_DARK_SPAWN', 'Bool') && SimVar.GetSimVarValue('L:A32NX_FMGC_FLIGHT_PHASE', 'Enum') === FmgcFlightPhases.PREFLIGHT;
        this.offDurationInMilliseconds = initialisingColdAndDark ? DisplayUnitSelfTest.RequiredAfterBeingOffForMilliseconds : 0;
```

File: flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/SAI/A320_Neo_SAI.js [hunk 2]
```diff
@@ -1239,15 +1239,15 @@ class A320_Neo_SAI_SelfTest extends NavSystemElement {
         this.getDeltaTime = A32NX_Util.createDeltaTimeCalculator();
         const interval = 5;
         this.getFrameCounter = A32NX_Util.createFrameCounter(interval);
-        const cold_dark = SimVar.GetSimVarValue('L:A32NX_COLD_AND_DARK_SPAWN', 'Bool');
+        const coldDark = Boolean(SimVar.GetSimVarValue('L:A32NX_COLD_AND_DARK_SPAWN') && SimVar.GetSimVarValue('L:A32NX_FMGC_FLIGHT_PHASE', 'Enum') === (FmgcFlightPhases.PREFLIGHT));
```
Comment (davidwalschots) [inline flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/SAI/A320_Neo_SAI.js:1242]: **thought**: The `Boolean()` invocation is unnecessary.
**suggestion**: Remove it.

**Review by davidwalschots — CHANGES_REQUESTED** [review]

File: flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/DisplayUnit.js (hunk 1 above)
Comment (2hwk) [reply flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/DisplayUnit.js]: First issue resolved
Second issue, the code is not superflous, ``this.offDurationInMilliseconds += deltaTime;`` must be escaped

File: flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/SAI/A320_Neo_SAI.js (hunk 2 above)
Comment (2hwk) [reply flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/SAI/A320_Neo_SAI.js]: Done

**Comment by 2hwk** [comment]
In the end I couldn't discard ``A32NX_COLD_AND_DARK_SPAWN``. Until the loading in situation is more stable, not much else works other than setting a localvar in the relevant .flt files, and mitigating the cases where this is carried over when loading in player saved .flt

File: src/instruments/src/Common/displayUnit.tsx [hunk 3]
```diff
@@ -27,7 +30,7 @@ export const DisplayUnit: React.FC<DisplayUnitProps> = (props) => {
     useUpdate((deltaTime) => {
         if (timer !== null) {
             if (timer > 0) {
-                setTimer(timer - (deltaTime / 1000));
+                setTimer(Math.max(timer - (deltaTime / 1000), 0));
```
Comment (davidwalschots) [inline src/instruments/src/Common/displayUnit.tsx:33]: `Math.max` is unnecessary here.

File: src/instruments/src/Common/displayUnit.tsx [hunk 4]
```diff
@@ -53,10 +59,9 @@ export const DisplayUnit: React.FC<DisplayUnitProps> = (props) => {
             setTimer(null);
         }
     });
-
-    if (state === DisplayUnitState.Selftest) {
-        return (
-            <svg className="SelfTest" viewBox="0 0 600 600">
+    return (
```
Comment (davidwalschots) [inline src/instruments/src/Common/displayUnit.tsx:62]: I'm not sure if the previous code was intentionally emitting less DOM elements. @lukecologne  @Benjozork does either of you have an opinion on this?

Comment (2hwk) [reply src/instruments/src/Common/displayUnit.tsx:62]: Pretty much necessary to avoid an issue where the useUpdate hook would unhook itself from the event listener when loading in in-flight.

**Review by davidwalschots — APPROVED** [review]

**Comment by FlightSimmer7700** [comment]
Quality Assurance Tester

Discord: FlightSimmer7700#3468
Object of testing: #5153 
Tier of Testing: 1
Date: 25/6/21

Testing Process: 
Loaded in C&D, tried turning screens off and on to check self-test
Loaded on the runway and tried
Loaded in cruise
Loaded on approach

Negatives: 
- If you load "too quickly" as mentioned above but on the ground all the screens apart from the PFD's skip the self-test but the PFD's do the self-test
- (probably not related but would be nice if addressed) when a screen has been off for more than 10 seconds and then it is turned on and off continuously it eventually turns on, not sure if this is expected or if it should technically go into an infinite loop
- When loaded in mid-air when the PFD's are turned off and then on after 10 seconds don't do a self-test but other screens do

Not experienced the "loading in too fast" mid-air, the other screens always functioned as expected if loading fast or slow but the PFD's are the same all the time (not doing self-test)

Testing Results: Not Passed

Conclusions: Good start but has a few bugs which I'm not sure are fixable
Media:
PFD only self-test:
https://youtu.be/xUaeQekL6wA

On Off On Off On Off On Off:
https://youtu.be/u3NuPnifVdE

No PFD self-test mid-air:
https://youtu.be/5WS7vN5g39A

**Comment by 2hwk** [comment]
Ok, I guess the FMC LVars also have some inconsistent output during the loading cinematic... I'm going to have to do a bit of a rethink on my approach here.

**Comment by 2hwk** [comment]
> Quality Assurance Tester
> 
> Discord: FlightSimmer7700#3468
> Object of testing: #5153
> Tier of Testing: 1
> Date: 25/6/21
> 
> Testing Process:
> Loaded in C&D, tried turning screens off and on to check self-test
> Loaded on the runway and tried
> Loaded in cruise
> Loaded on approach
> 
> Negatives:
> 
> * If you load "too quickly" as mentioned above but on the ground all the screens apart from the PFD's skip the self-test but the PFD's do the self-test
> * (probably not related but would be nice if addressed) when a screen has been off for more than 10 seconds and then it is turned on and off continuously it eventually turns on, not sure if this is expected or if it should technically go into an infinite loop
> * When loaded in mid-air when the PFD's are turned off and then on after 10 seconds don't do a self-test but other screens do
> 
> Not experienced the "loading in too fast" mid-air, the other screens always functioned as expected if loading fast or slow but the PFD's are the same all the time (not doing self-test)
> 
> Testing Results: Not Passed
> 
> Conclusions: Good start but has a few bugs which I'm not sure are fixable
> Media:
> PFD only self-test:
> https://youtu.be/xUaeQekL6wA
> 
> On Off On Off On Off On Off:
> https://youtu.be/u3NuPnifVdE
> 
> No PFD self-test mid-air:
> https://youtu.be/5WS7vN5g39A

Point 1 and 2 has been addressed.
3 is tied to the loading cinematics/loading screen issue which is out of our control, I doubt there will be resolution in this PR. The current solution is to wait 30 seconds after the ready to fly button is available to actually start your flight.

**Comment by 2hwk** [comment]
Note that there is currently a bug in master with the MCDU being blank when spawning in mid-air, it's being addressed, and is not caused by this PR.

**Comment by FlightSimmer7700** [comment]
Point 1 is still not fixed 
image
Point 2 is fixed

**Comment by frankkopp** [comment]
Quality Assurance Tester Report

Discord: Cdr_Maverick#6475
Object of testing: #5153 
Tier of Testing: 1
Date: 28.06.2021

Testing Process: 


Negatives: (Any issues, doubts. - type N/A if none are found)

Testing Results: (Passed/Not Passed)

Conclusions: (Notes made, the positives in the PR, and anything extra you would like to mention - Delete Line if Nothing Extra is to be mentioned)

Media: (Pictures/videos if applicable - delete line if not applicable)

**Comment by frankkopp** [comment]
Quality Assurance Tester Report

Discord: Cdr_Maverick#6475
Object of testing: #5153 
Tier of Testing: 1
Date: 28.06.2021

Testing Process: 

Loading in on the runway ready for take-off ==> Not OK before "Ready to fly", turn off/on OK 
Loading in cruise ==> load ok, turn off/on not OK
Loading in landing at a runway ==> load ok, turn off/on not OK
Loading a saved flight (.pln/.flt) ==> load ok, turn off/on not OK

Negatives:
- Start on runway - PFD goes into test even before clicking  "FLY" [0]
- Start in Cruise - PFD CAPT & FO do not go into test after >10sec off [1]
- Start in Approach- PFD CAPT & FO do not go into test after >10sec off [2]
- Saved flight: PFD CAPT & FO do not go into test after >10sec off [3]

Testing Results: Not passed

Conclusions: as far as I could see none of the test cases worked completely. I hope did not do something wrong on my part?

Media: 

[0] https://youtu.be/FAqRrj_bQpw
[1] https://youtu.be/gLCHmPN-rFY
[2]  https://youtu.be/HumZ0wH9nS4
[3] https://youtu.be/1oLIi35IFqM

**Comment by 2hwk** [comment]
Ok, closing for now, the main point of this is to have consistent self-test behavior that is less broken, until that's achieved there's no point in merging if it is adding as many bugs as it is fixing, and not addressing the PFD (React) at all, since the goal is to eventually move everything to React.

**Comment by 2hwk** [comment]
Reopening as this would still be an improvement over current behavior in master, just less substantial than I hoped.

**Comment by marcman86** [comment]
Quality Assurance Tester Report
Discord:marcman86#4907
Object of testing: #5153
Tier of Testing: 1
Date: 10/07/2021

Testing Process:
- Spawned C&D at EDDP
- Turned on bat. and ext. power
- Tested normal self-test behaviour
- Tested 10s behaviour
- Spawned on runway at EDDP
- Tested 10s behaviour
- Spawned airborne over EDDP
- Tested 10s behaviour > PFD does not go in self-test when more than 10s off
- Spawned on approach to EDDP
- Tested 10s behaviour > PFD does not go in self-test when more than 10s off

Negatives: PFD issue discussed before

Testing Results: Passed
Conclusions: Works

Hope this helps :-)

**Comment by St54Kevin** [comment]
**Quality Assurance Tester**

Object of testing: #5153 
Tier of Testing: 1
Date: 12/07/2021

**Testing Process:**
1. Loaded onto runway and checked dispay upon spawn -> No selftest
2. Long turn off displays, short turn off displays -> correct behavior
3. Loaded airbone onto route and checked dispay upon spawn -> No selftest
4. Long turn off displays, short turn off displays -> correct behavior
5. Saved flight
6. Loaded on approach and checked dispay upon spawn -> No selftest
7. Long turn off displays, short turn off displays -> correct behavior
8. Loaded saved flight and checked dispay upon spawn -> No selftest
9. Long turn off displays, short turn off displays -> correct behavior
10. Loaded C&D and powered up -> normal selftest

**Negatives:** 
- Mid flight PFD not selftesting as esxpected and outlined above
**Testing Results:** Passed
