### PR TITLE
[CDU] Fix initial flight phase

### LINKED ISSUE #1349: [BUG] Wrong MCDU Page When Spawning In The Air
**Mod Version**

master

**Describe the bug**

The first page of the FMC is just a slash

**To Reproduce**

1. Spawn in in the air and look at the FMC
2.
3.

**Expected behavior**

The first page should be on the flight plan page

**Actual behavior**

The first page is just a slash until you press any button

**References**

[FMC Bug.zip](https://github.com/flybywiresim/a32nx/files/5381533/FMC.Bug.zip)

**Additional context**

Was this working before/when did the issue start occurring?
Since the last version
Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):
JacobK #9511

### LINKED ISSUE #1430: [BUG] Takeoff state of airplane when spawned in air
**Mod Version**
latest master as of 17.10.20

**Describe the bug**

When trying to spawn the aircraft in the air (to train landings), I get the T/O landing memo, the aircraft is in the takeoff performance page and ILS approach doesn't appear (it seems to work, but only shows LOC)

**To Reproduce**

1. Go into the airport select screen, select an airport (like EPWA), with approach ILS 33
2. Turn on the flight, observe the aircraft in the air

**Expected behavior**

I get an aircraft in a state that is ready for landing

**Actual behavior**

I get an aircraft in the takeoff state, constantly warning "don't sink" when landing.

**References**

**Additional context**

Was this working before/when did the issue start occurring? I'm not sure

Is this a problem in the vanilla unmodded game? No, I don't think so

Discord username (if different from GitHub): acro#2421

### PR DESCRIPTION
**Pull request by beheh**
Part of this was previously attempted at #929
Fixed #1430
Closes #1349

## Summary of Changes

Right now the MCDU is always initialized in the takeoff flight phase. This is never correct:
- when spawning cold and dark or on a runway, the flight phase should be preflight
- when spawning in the air it should be an appropriate flight phase (climb/cruise/descent/approach)

This PR:
- [x] Adds the missing preflight flight phase (future PRs will use this to change some MCDU pages)
- [x] Adds a way to set the flight phase in the .flt file to differentiate the situations
  *Note that in some cases it'll be overriden right away because the FMC decides the initial phase should transition to another.*

Now we have the spawn logic in place, we could also decide whether we want the MCDU to default to a different page than the MCDU MENU if we detect we're spawning in the air (which is the default). The PR doesn't change this though yet for now.
I could also no longer reproduce #1349 as part of building this.

## References

grafik

I don't have a reference for the reversion in the RTO situation from takeof back to preflight, but for now I'm assuming it's the inverse of the above + an in air check (as it was previously).

## Additional context

Discord username (if different from GitHub): BehEh#1234

### QA

Apart from the usual testing, please pay special attention to the following scenarios:
- PROG page title `TAKEOFF` is white (indicating preflight) when spawning at a parking position cold and dark
- PROG page title `TAKEOFF` is white (indicating preflight) when spawning on a runway
- PROG page title `TAKEOFF` turns green soon after TOGA/FLEX
- PROG page title `TAKEOFF` turns white again after rejecting a takeoff
- PROG page title `APPR` is green when spawning in the air on an approach
- PROG page title `CLB` or `CRZ` or `DES` is green when spawning in the air anywhere else
  *This seems a little random right now by the game, based on the exact height you spawn at. I want to improve the later flight phase transitions to make this a bit more consistent, but will do that in a future PR. At least it's no longer takeoff.*
- PROG page title switches to `TAKEOFF` in white (indicating preflight) after 30 seconds after landing

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

### CODE REVIEW

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js [hunk 1]
```diff
@@ -1092,25 +1106,44 @@ class A320_Neo_CDU_MainDisplay extends FMCMainDisplay {
...
+                this.currentFlightPhase = FlightPhase.FLIGHT_PHASE_TAKEOFF;
             }
         }
 
         //Reset to preflight in case of RTO
-        if (this.currentFlightPhase <= 2 && SimVar.GetSimVarValue("L:A32NX_Preflight_Complete", "Bool") == 1) {
-            if (!(highestThrottleDetent == ThrottleMode.TOGA || highestThrottleDetent == ThrottleMode.FLEX_MCT) && SimVar.GetSimVarValue("RADIO HEIGHT", "Feet") < 100) {
+        if (this.currentFlightPhase === FlightPhase.FLIGHT_PHASE_TAKEOFF) {
+            if (
+                SimVar.GetSimVarValue("RADIO HEIGHT", "Feet") < 100 &&
```
Comment (beheh) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js:1132]: I wasn't able to find a reference for this line. I'll just leave it as is for now, and invert the preflight => takeoff conditions below so we don't end up in a situation where the above preflight => takeoff condition fights with the takeoff => preflight conditions here.

**Comment by beheh** [comment]
This will also fix the LAT REV not showing NEXT WPT, as that's correctly hidden during takeoff.

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js [hunk 2]
```diff
@@ -1092,25 +1106,42 @@ class A320_Neo_CDU_MainDisplay extends FMCMainDisplay {
...
+                SimVar.GetSimVarValue("TRAILING EDGE FLAPS RIGHT ANGLE", "degrees") === 0 &&
+                SimVar.GetSimVarValue("LEADING EDGE FLAPS LEFT ANGLE", "degrees") === 0 &&
+                SimVar.GetSimVarValue("LEADING EDGE FLAPS RIGHT ANGLE", "degrees") === 0
+            );
+            const pitchTakeoffEngaged = !isAirborne && isFinite(this.v2Speed) && isTogaFlex && !flapsSlatsRetracted;
+            const isTakeOffValid = pitchTakeoffEngaged ||
+                (
+                    SimVar.GetSimVarValue("ENG N1 RPM:1", "Percent") >= 85 &&
+                    SimVar.GetSimVarValue("ENG N1 RPM:2", "Percent") >= 85
+                ) || groundSpeed > 90;
```
Comment (davidwalschots) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js:1129]: **suggestion**: Change the order of this boolean expression to reduce SimVar usage:
```js
const isTakeOffValid = pitchTakeoffEngaged || groundSpeed > 90 || 
    (SimVar.GetSimVarValue("ENG N1 RPM:1", "Percent") >= 85 && SimVar.GetSimVarValue("ENG N1 RPM:2", "Percent") >= 85);
```

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js [hunk 3]
```diff
@@ -1092,25 +1106,42 @@ class A320_Neo_CDU_MainDisplay extends FMCMainDisplay {
...
-            if ((highestThrottleDetent == ThrottleMode.TOGA || highestThrottleDetent == ThrottleMode.FLEX_MCT) && SimVar.GetSimVarValue("ENG N1 RPM:1", "Percent") > 15 && SimVar.GetSimVarValue("ENG N1 RPM:2", "Percent") > 15) {
+        if (this.currentFlightPhase <= FlightPhase.FLIGHT_PHASE_TAKEOFF) {
+            const isAirborne = !Simplane.getIsGrounded(); // TODO replace with proper flight mode in future
+            const isTogaFlex = highestThrottleDetent === ThrottleMode.TOGA || highestThrottleDetent === ThrottleMode.FLEX_MCT;
+            const flapsSlatsRetracted = (
+                SimVar.GetSimVarValue("TRAILING EDGE FLAPS LEFT ANGLE", "degrees") === 0 &&
+                SimVar.GetSimVarValue("TRAILING EDGE FLAPS RIGHT ANGLE", "degrees") === 0 &&
+                SimVar.GetSimVarValue("LEADING EDGE FLAPS LEFT ANGLE", "degrees") === 0 &&
+                SimVar.GetSimVarValue("LEADING EDGE FLAPS RIGHT ANGLE", "degrees") === 0
+            );
```
Comment (davidwalschots) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js:1123]: **question**: Do we have any failure modelling yet? If not, then I'm guessing we could replace this with a single SimVar call for now, only checking a single slat position as I believe flaps are never extended without slats.

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js [hunk 4]
```diff
@@ -1092,25 +1106,42 @@ class A320_Neo_CDU_MainDisplay extends FMCMainDisplay {
     }
     checkUpdateFlightPhase() {
         const airSpeed = SimVar.GetSimVarValue("AIRSPEED TRUE", "knots");
+        const groundSpeed = SimVar.GetSimVarValue("GPS GROUND SPEED", "knots");
```
Comment (davidwalschots) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js:1109]: **suggestion**: Move closer to usage to reduce SimVar calls.

**Comment by danbw9** [comment]
Hey, was just testing your PR, spawned C&D and in the MCDU Setup could not access TO PERF page? It goes to CLB page when I click on PERF.  Seems like it doesn't realise it is in pre flight.

**Comment by beheh** [comment]
I'll recheck. Could you let me know which airport/parking position that was?

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js (hunk 3 above)
Comment (beheh) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js:1122]: Thanks for the conern. We chatted briefly about this on Discord, and the outcome was that there's no concern as long as this is not in a loop, especially as the CDU is not refreshed very often compared to some of the other instruments.

**Comment by beheh** [comment]
Okay, I've now updated the PR to explicitely use a new varialbe in the `.flt` files to set an appropriate flight phase when spawning.
I've seen the flight phase slightly fluctuate between CLB/CRZ/DES when spawning mid-air, but I think that's because the Asobo logic to transition between those flight phases is a little lazy. I'll clean those up in a future PR.
For now, at least the aircraft never spawns in air with the FMC in the takeoff flight phase.

File: A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/cruise.FLT [hunk 5]
```diff
@@ -198,6 +198,7 @@ A32NX_OVHD_HYD_BLUEPUMP_OVRD=0
 A32NX_OVHD_HYD_LEAK_MEASUREMENT_G=1
 A32NX_OVHD_HYD_LEAK_MEASUREMENT_B=1
 A32NX_OVHD_HYD_LEAK_MEASUREMENT_Y=1
+A32NX_INITIAL_FLIGHT_PHASE = 3
```
Comment (beheh) [inline A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/cruise.FLT:201]: I choose 3 (= climb) here because the transitions are a bit sloppily implemented by Asobo. 4 (= cruise) sometimes ends up in 5 (= descent) based on the barometic height the aircraft spawns at (5000 AGL, but different barometric heights).
I'll clean those transitions up in a future PR and then we can revisit this.
