### PR TITLE
Move APU Core Logic to fix APU bug

### LINKED ISSUE #421: [BUG] no electrical power from APU
Started the APU only to find that once it said AVAIL on the button, no electrical power was coming from it.

So I had the APU running with zero electrical power to all 6 screens.... 

Used EXT power to power things up.... then when I turned off EXT power, things stayed on

### PR DESCRIPTION
**Pull request by AdenFlorian**
Fixes #421

**Summary of Changes**

Fixes #421 by moving any APU logic, that isn't directly tied to displaying things on the ECAM, out of the A320_Neo_LowerECAM_APU.js file and into A32NX_Core.

A32NX_Core is where I'd like to start putting logic that isn't tied to any screen.

It is hooked up to the EICAS update function, as there is only one EICAS, and it runs at cold and dark.

**Screenshots (if necessary)**

**Additional context**

### CODE REVIEW

File: A32NX/html_ui/Pages/A32NX_Core/A32NX_APU.js [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+    constructor() {
+        console.log('A32NX_APU constructed');
+    }
+    init() {
+        console.log('A32NX_APU init');
+        SimVar.SetSimVarValue("L:APU_FLAP_OPEN", "Percent", 0);
+        this.lastAPUBleedState = -1;
+    }
+    update(_deltaTime) {
+        const currentAPUMasterState = SimVar.GetSimVarValue("FUELSYSTEM VALVE SWITCH:8", "Bool");
```
Comment (AdenFlorian) [inline A32NX/html_ui/Pages/A32NX_Core/A32NX_APU.js:11]: this code was simply cut and pasted from the A320_Neo_LowerECAM_APU.js

File: types/types.d.ts [hunk 2]
```diff
@@ -42,6 +43,104 @@ declare global {
         AUTO
     }
 
+    type A320_Neo_LowerECAM_APU = {
```
Comment (AdenFlorian) [inline types/types.d.ts:46]: Just adding more types to work towards full type safety

File: docs/Classes.md [hunk 3]
```diff
@@ -0,0 +1,92 @@
+# Classes
```
Comment (AdenFlorian) [inline docs/Classes.md:1]: just some notes about the class heirarchies

**Review by tyler58546 — APPROVED** [review]
