### PR TITLE
Toga engine fix and ecam updates 

### LINKED ISSUE #110: ATHR unstable on TOGA
ATHR oscillates between full throttle and down some percent when on TOGA and no other modes like MCT,CMB etc

### PR DESCRIPTION
**Pull request by ThePilot916**
Fixes #110 

**Summary of Changes** Fixes the haphazard PR  #491 

Fixed ATHR unstable on TOGA
 - Updated engine N1, EGT and Oil pressure values to match A320Neo engine limits.(temperature is in rankine, pressure in pounds per sq feet)
 - N1 and EGT now have dynamic limits based on throttle state(arrow does not turn red beyond 100%N1 on TOGA upto 101.5% for 5min).
 - TOGA state limits on N1 and EGT are only allowed upto 5min on both engines after which it comes down to MCT limits.

APU Guage now features a dynamic EGT warning marker.

Increased gauge px thickness by 1px.

**Screenshots (if necessary)**

image

**Additional context**

### CODE REVIEW

**Comment by AdenFlorian** [comment]
did you mean to delete all of this?
image

**Comment by ThePilot916** [comment]
> did you mean to delete all of this?
> image

Did not, seems to be a failed pull. Fixed it with a new commit.

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js [hunk 1]
```diff
@@ -774,6 +775,21 @@ var A320_Neo_UpperECAM;
                     }
                 }
             }
+            var currentThrottleState = Math.max(Simplane.getEngineThrottleMode(0), Simplane.getEngineThrottleMode(1));
+            if(this.throttleMode != currentThrottleState){
+                this.throttleMode = currentThrottleState;
+            }
```
Comment (AdenFlorian) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js:781]: what's the point of this?

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js [hunk 2]
```diff
@@ -1494,17 +1540,16 @@ var A320_Neo_UpperECAM;
         getActiveFailures() {
             let output = {};
             this.hasActiveFailures = false;
-            this.hasWarnings = false;
+                        this.hasWarnings = false;
```
Comment (AdenFlorian) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js:1543]: formatting

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js [hunk 3]
```diff
@@ -1516,7 +1561,7 @@ var A320_Neo_UpperECAM;
             }
             return output;
         }
-
+
```
Comment (AdenFlorian) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js:1564]: formatting

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js [hunk 4]
```diff
@@ -1536,7 +1581,7 @@ var A320_Neo_UpperECAM;
             } else {
                 this.clearedMessages = [];
             }
-        }
+        }
```
Comment (AdenFlorian) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js:1584]: formatting

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js (hunk 1 above)
Comment (ThePilot916) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js:781]: So the N1 and EGT limits vary based on engine modes and for TOGA there's supposedly a 5min limit on the max limit and then it falls back to MCT limit, this'll have to hold the previous throttle state to check if its been TOGA or changed to TOGA so that the timer maybe reset to 5min(300s).

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js [hunk 5]
```diff
@@ -830,6 +848,34 @@ var A320_Neo_UpperECAM;
             this.divMain.appendChild(this.gaugeN1);
             this.allGauges.push(this.gaugeN1);
         }
+        getModeEGTMax(){
+            if(this.throttleMode == ThrottleMode.TOGA && this.timerTOGA > 0){
+                return 1060;
+            }
+            else if(this.timerTOGA <0){
+                return 1025;
+            }
```
Comment (AdenFlorian) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js:857]: how would the execution ever get past this when not in TOGA?
if its not in TOGA, then `this.timerTOGA` is going to be -1, so it will always return 1025.

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js [hunk 6]
```diff
@@ -667,7 +666,7 @@ var A320_Neo_UpperECAM;
             if (Simplane.getCurrentFlightPhase() > 2) {
                 this.activeTakeoffConfigWarnings = [];
             }
-
+
```
Comment (AdenFlorian) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js:669]: formatting

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js [hunk 7]
```diff
@@ -1494,17 +1540,16 @@ var A320_Neo_UpperECAM;
...
                 const messages = this.messages.failures[i].messages;
                 for (var n = 0; n < messages.length; n++) {
                     const message = messages[n];
                     if (message.id == null) message.id = `${i} ${n}`;
                     if (message.isActive() && !this.clearedMessages.includes(message.id)) {
+                    if (message.isActive()) {
                         this.hasActiveFailures = true;
-                        if (message.level == 3) this.hasWarnings = true;
-                        if (message.level == 2) this.hasCautions = true;
                         if (output[i] == null) {
```
Comment (AdenFlorian) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js:1553]: did you mean to touch this?

Comment (ThePilot916) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js:1553]: was left out in the last fix, added it with the formatting fix.

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js (hunk 1 above)
Comment (AdenFlorian) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js:781]: you're not doing anything in that if statement though. If you wanted to do some right when the state actually changed, it would have to go inside this if statement right?

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js (hunk 5 above)
Comment (ThePilot916) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js:857]: The region is for it to be in TOGA, if you exceed TOGA timer it falls back to MCT limit i.e 1025 instead of 1060.

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js (hunk 1 above)
Comment (ThePilot916) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js:781]: its updating the stored value for throttle state, that is its function.

Comment (AdenFlorian) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js:781]: in that case, no need for the if, just set it every frame, it won't hurt anything

File: A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js [hunk 8]
```diff
@@ -830,6 +848,34 @@ var A320_Neo_UpperECAM;
...
+                return 1025;
+            }
+            if(this.throttleMode == ThrottleMode.CLIMB){
+                return 875;
+            }
+            if(this.ThrottleMode == ThrottleMode.AUTO){
+                return 850;
+            }
+            else{
+                return 750;
```
Comment (AdenFlorian) [inline A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js:868]: could you add a comment that says when this would trigger? is it for a specific throttle mode?

Comment (ThePilot916) [reply A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js:868]: That is for the last remaining mode IDLE/GND Start

**Comment by AdenFlorian** [comment]
Will need a way to reproduce the issue before we can merge this (#110), I don't think I've ever seen this happen for me.

**Comment by ThePilot916** [comment]
> Will need a way to reproduce the issue before we can merge this (#110), I don't think I've ever seen this happen for me.
When on TOGA if your engine EGT exceeds 2000rankine the issue comes in, its not supposed to do so until 2399rankine(1060 degree celcius) 

N1, N2 and EGT max were also set wrong.

"This will be looked into and is common!"
-arvinjarvin

PS: the issue has other people reporting the same.

**Comment by AdenFlorian** [comment]
> When on TOGA if your engine EGT exceeds 2000rankine the issue comes in

How can I get my engines to do that?

**Comment by ThePilot916** [comment]
By far of what I've observed when it gets triggered, it varies based on temperature, IAS, attitude
(guessing its due to the airflow to the engines?, I'm no pilot so can't say for certain), N1.

One easy way to force it would be to go on TOGA and nose dive and monitor EGT to climb beyond 837(that was the previous limit,2000 rankine) and then you'll see it fluctuate(this is what I used to force it and check in case it wasn't triggered by existing conditions)

**Comment by AdenFlorian** [comment]
thanks, was able to reproduce by raising the ambient temps.

**Comment by AdenFlorian** [comment]
tested taking from arizona with this weather temp setting, and looks good!
image

**Review by AdenFlorian — APPROVED** [review]
